### ISSUE TITLE
Proposal for content strategy - Jennifer/Janel

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1003]
Add a proposal for content strategy to 2018 marketing folder

**Comment by jcwlib** [comment]
https://docs.google.com/document/d/1NXJX7D9uf2dpVqfOMMvhSKmifAl1NSsDOLchXC44NXU/edit

**Comment by jhibbets** [comment]
I finally had a chance to look at this and think this is just want we
needed to start the newsletter.
