### ISSUE TITLE
Determine markering meeting cadence

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1010]
Can you help us determine a marketing meeting cadence so we can list that in the project plan and get it on the shared NC Open Pass calendar?

**Comment by wildca01t** [comment]
My recommendation is considering every 2 weeks cadence.  We keep this 2-week rhythm till ramping up to once a week when approaching major events - city camp and nc datapalooza.  Thoughts? If you are in agreement, I'll add to project plan... Plus schedule the next one...

**Comment by jhibbets** [comment]
I think that should work well. Maybe keep the first 3-4 an hour in length,
then scale back to 30 minutes after we get into a good rhythm. If you can
find out what day of the week and time works for everyone, that would be
great!
