### ISSUE TITLE
Draft first newsletter

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1012]

**Comment by jcwlib** [comment]
working draft created in MailChimp - still need some details to finish out the first newsletter

**Comment by jhibbets** [comment]
We should have the meet-up details early this week. We got most of the
title/abstracts from speakers on Friday.

**Comment by jhibbets** [comment]
Here is what we have so far: I think we can ship this. It would be great to send the newsletter on Tuesday, May 8th in the morning.

Action is to sign-up at: https://www.meetup.com/All-Things-Open-RTP-Meetup/events/248911255/

A one-of-a-kind innovation lab and program for Wake County -- Bill Greeves, Wake County
A new direction for the Raleigh open data offering -- Bonnie Danahy, City of Raleigh 
An Open Solution for North Carolina’s Digital Presence -- Phillip Lamb, NC Digital Commons
How developers can get started with open date -- Speaker TBD

**Comment by jcwlib** [comment]
first newsletter sent
