### ISSUE TITLE
Migrate NC Open Pass site to WordPress

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1016]
start the website migration so that we can post blog posts on the parent domain

**Comment by jhibbets** [comment]
@jcwlib You should be able to migrate the CityCampNC blog posts to the new site now. I've moved Staging to a new directory /civictech and the homepage should redirect to the new WP location. Most of the images were broken, I think I was able to fix most of them.  I opened up a ticket about the header, to make sure I did it right. Sorry this took so long, DNS changes messed me up.
