### ISSUE TITLE
Setup CDN and share login with marketing@ group email

### ISSUE THREAD

**Issue by FrankCJones** [ncopenpass/NCOpenPass#1018]
Using a CDN, we can improve the site performance and manage the DNS without needing access to the domain management. Cloudflare is one option for setting this up.

**Comment by ChrisTheDBA** [comment]
What is the cost associated with this? From the cloudflare website is
appears to be 80-100 per month.

Chris Mathews

**Comment by FrankCJones** [comment]
The price starts at $0 and goes up with more features. The free plan is
sufficient for our needs. https://www.cloudflare.com/plans/

Frank
-sent from my phone

**Comment by jhibbets** [comment]
I have hosting through JustHost that we can use that everyone can have
access to and it has WordPress as an option.

**Comment by jhibbets** [comment]
A CDN is out of scope for our needs right now.
