### ISSUE TITLE
Develop a survey to acquire information on data sets, from the NCOpenPass community

### ISSUE THREAD

**Issue by jmpmcmanus** [ncopenpass/NCOpenPass#1042]

**Comment by jmpmcmanus** [comment]
Created a survey, on SurveyMonkey. It currently has five questions. I would like to get feedback and additional questions.

**Comment by jhibbets** [comment]
@jmpmcmanus I shared the password to the NC Open Pass survey monkey account with you

**Comment by jcwlib** [comment]
introduction to the survey -https://docs.google.com/document/d/16mk3_lySLIbEq3_YVWvoZFYQUglgtXeov0PI8d4Q4-E/edit
