### ISSUE TITLE
NC Open Pass Flyer/Business Card

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1043]
Able to put at COR Museum Raleigh M.A.I.N. events table in August/September. 

Possibly make it more general so that we can use for networking at other events. 

Jennifer drafting after Janel provides information

**Comment by jcwlib** [comment]
prototype posted https://drive.google.com/open?id=1-ZHmMpdihR1cLQEQRWC4zK-ls2JmKiYx

**Comment by jhibbets** [comment]
Looks good to me. Ship it! And thank you.

**Comment by ChrisTheDBA** [comment]
I like the bottom one and the green makes me feel nauseous.

Chris Mathews

**Comment by jhibbets** [comment]
I also like the bottom one, without the green square. Feels more open.

**Comment by snewt-n** [comment]
Wasn't the top just bleed edges etc? Third vote for bottom one, if it wasn't.

**Comment by snewt-n** [comment]
PS Jennifer they're beautiful!

**Comment by jcwlib** [comment]
Ready to go with printing order for Civic Camp

**Comment by jtawes** [comment]
Just to clarify again for everyone - the top one is not a 'design' it is the same design as the bottom one the top one just includes the cut lines/bleed lines for the printer (this is standard in printed items).

**Comment by ChrisTheDBA** [comment]
Chris Mathews

The card was closed 7 days ago. I assumed that meant it was resolved -
either ordered or not needed.

**Comment by jtawes** [comment]
My apologies for prematurely closing this ticket. I assumed it referenced the 'design' of the cards only and once the design was approved and thought I should close the ticket. I see now that for these items the ticket is to be used to track the item all the way through ordering and receipt of shipment. I will be more mindful in the future.

**Comment by ChrisTheDBA** [comment]
No problem. I just ordered them. They will be here Sept 11 along with the
2.5x6 banner.
Chris Mathews
