### ISSUE TITLE
Portable internet for CoM

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#105]

**Comment by ChrisTheDBA** [comment]
I might have some contacts with AT&T and Verizon, let me check.

**Comment by ChrisTheDBA** [comment]
AT&T contact fell through. Where do we stand on this? I will ask at CoM this Sunday about their bandwidth.

**Comment by dtraleigh** [comment]
No update from me. I can make it a priority for this week. Chris, you
mentioned you were checking our Verizon? I will find two other alternatives
for consideration.

**Comment by ChrisTheDBA** [comment]
I have a contact and he is going to price it for us. Stan Sellers(stan.sellers@verizonwireless.com) - 919-632-9992

**Comment by ChrisTheDBA** [comment]
CoM uses TWC for their internet. So there are actually three seperate netwowrks available to wireless access. Cable but I think we're probably good. cableWIFI, TWCWIFI and CoM-Guest.   Need to check I will encourage people to bring a MiFi for heavy lifting.

**Comment by jhibbets** [comment]
I have a lead here. Met someone at Verge NC last night: TourTech connected: shannon@tourtech.com  contact shannon at (919) 261-1110 x 102 - she seemed interested and could entertain an in-kind sponsorship. We need to move fast on this (to potentially get logo's on marketing material), can someone contact her today?

**Comment by ChrisTheDBA** [comment]
Calling now.

**Comment by dtraleigh** [comment]
So is this issue closed? What's left here?
