### ISSUE TITLE
Migrate CityCamp team page

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1056]
Need to take this page: http://citycampnc.org/organizers/

and update this page:
http://staging.ncopenpass.com/about/organizers/

Would like to keep the circle style images
Need to download and upload images to new staging site

remove the following team members:
	
Natalie Noel
Bill Scanlon
Mital Patel
Ashley McClelland
Suzanne Beaumont
Sam McClenney

**Comment by jtawes** [comment]
Done
