### ISSUE TITLE
Looking to update the generic email (Mailchimp send email)

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1064]
Let's also use this: ncopenpass-admin@googlegroups.com

But if you can still list my name as the sender (name) I think it's helpful to have a person tied to a newsletter. If you disagree, no worries, update this as you see fit.

**Comment by jcwlib** [comment]
Jason -

I know that MailChimp won’t let me send from the googlegroups.com domain.

That was the initial issue when I tried to use the marketing email address
instead of your personal email.

We can keep sending from your email.

—Janel

**Comment by jhibbets** [comment]
Well then....

**Comment by jhibbets** [comment]
Let's try this: mailchimp@ncopenpass.com

**Comment by jhibbets** [comment]
@jcwlib - This email isn't working yet. I'll let you know when I've got the DNS issues resolved and the MX record in place.

**Comment by jcwlib** [comment]
Jason - is this email up and running or should I continue to use your
personal email?

**Comment by jhibbets** [comment]
Please just use my email for now. I'll check the MX records this week.

**Comment by jhibbets** [comment]
Update to NCOpenPass@gmail.com
