### ISSUE TITLE
Draft Flyer for Innovation Raleigh partnership

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1068]
To be used at First Responders' outreach events

**Comment by jcwlib** [comment]
@snewt-n could you help with this task as well?  We need to make a flyer to have at the 9/11 First Responders breakfast that explains the partnership between Innovate Raleigh and NC Open Pass and our first responder program.  Here is a link to the background of the partnership https://drive.google.com/open?id=18Htle1VvK2qk4XLa2ftU0qFlgBS0CzlDCOXXhnVcBLM

**Comment by jcwlib** [comment]
@snewt-n we also need the flyer to list out the civic camp details as well

**Comment by jtawes** [comment]
Is there a formal name for this project? I understand that this is a partnership with Innovate Raleigh and NC Open Pass to specifically support tech initiatives geared to the First Responder Community but I don't see a title and didn't know if I missed it somewhere.  Is it being called "The First Responder Program"? I'm trying to title the flyer that details this.

**Comment by jcwlib** [comment]
There is no specific name for the project.

You could use First Responder Initiative for a title

**Comment by jtawes** [comment]
This is a rough first draft - is this on the right track?

**Comment by jtawes** [comment]
Does this work?
First Responders Flyer DRAFT
<https://drive.google.com/open?id=1t7bsTG8sQdQZWlRbVWyrecICo0iVJdZe>

**Comment by jcwlib** [comment]
@jtawes - getting there - but we are missing a key point that we are encouraging them to join us at Civic Camp and that they get a free admission.  

Potential changes:
1) Move website URLs into the boxes about the organizations. 
2) Move the orgs blocks down to the footer and perhaps shorter
3) Remove first paragraph under the header
4) Text in header needs to be a different color
5) Move Civic Camp promotion to be in the top part of the flyer
6) Can we combine the paragraph about the design sessions with the actual ideas box?

Let me know if a visual of these changes would be easier to follow - thanks!

**Comment by jtawes** [comment]
Second draft is now available in First Responders shared drive:

First Responders Flyer
<https://drive.google.com/open?id=17dLjq61MFExLrp1_38ARcLSjsN2c4r60>

**Comment by jtawes** [comment]
Are we having a call today?

**Comment by jcwlib** [comment]
Jennifer - thanks for all your hard work on this flyer.  We are close!

Let's remove the second paragraph at the top and replace it with this text:

The first responder community is invited to participate in this year's
Civic Camp at the Red Hat Annex and Artspace in downtown Raleigh.  We are
offering free registration to first responders. Friday, September 21 will
include an introduction to Civic Camp, keynotes, panels, and unconference
sessions.  In the evening on Friday, various lightning talks (5 minutes or
less on a topic) will happen as well as networking and social time.
Finally on Saturday, September 22, there will be a hackathon for first
responder solutions as well as other projects ending in pitches from the
hackathon teams to kickoff the NC Open Pass DataPalooza competition.

**Comment by jcwlib** [comment]
We have a 9 am deadline on 9/10 to send the final version to Bridget

**Comment by jtawes** [comment]
I uploaded a second draft to the "First Responders Initiative" folder in
the shared drive, let me know what changes you need:

First Responders Flyer
<https://drive.google.com/open?id=19LFdbh_SkxnuM28UEejfG-U8mps9DcNP>

**Comment by jcwlib** [comment]
Here is the feedback I sent earlier about version #2

Jennifer - thanks for all your hard work on this flyer.  We are close!

Let's remove the second paragraph at the top and replace it with this text:

The first responder community is invited to participate in this year's
Civic Camp at the Red Hat Annex and Artspace in downtown Raleigh.  We are
offering free registration to first responders. Friday, September 21 will
include an introduction to Civic Camp, keynotes, panels, and unconference
sessions.  In the evening on Friday, various lightning talks (5 minutes or
less on a topic) will happen as well as networking and social time.
Finally on Saturday, September 22, there will be a hackathon for first
responder solutions as well as other projects ending in pitches from the
hackathon teams to kickoff the NC Open Pass DataPalooza competition.

**Comment by jtawes** [comment]
I made those edits, I guess I should have been more clear, this is version
3.

**Comment by jcwlib** [comment]
Thanks, Jennifer - I must have missed the third version.  I'll send this
over to Bridget for printing.
