### ISSUE TITLE
Update CityCamp DNS and add redirect

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1075]
Waiting on blog migration #1058

**Comment by jcwlib** [comment]
In the meantime, can you also add a message on the homepage pointing folks to the ncopenpass.com/civic-camp page?

**Comment by jhibbets** [comment]
CityCamp NC is now NC Open Pass Civic Camp. Be sure to visit http://ncopenpass.com/civic-camp/ for all the details about this years Civic Camp.

**Comment by jhibbets** [comment]
Instead of setting up new MX records, I created NCopenpass@gmail.com
