### ISSUE TITLE
Call for speakers newsleter - Wed Aug 8

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1089]

**Comment by jhibbets** [comment]
@jcwlib landing page is here: http://ncopenpass.com/civic-camp/civic-camp-call-for-speakers/

**Comment by jcwlib** [comment]
Sending Wednesday 8/8

--call for Civic Camp speakers 
--reminder NDoCH
-- brigade announcements

**Comment by jcwlib** [comment]
Promote NC RiOT event on August 21
