### ISSUE TITLE
NC Open Pass Logo

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1092]
from Chris -
Do we have the logo with the "benzene" ring, not in green but transparent? 

Jennifer is working on this request

**Comment by snewt-n** [comment]
Jennifer/Janel - What do you mean by not in green but transparent? I know Carsi & I both had working versions on it, just need to be clear on what you're asking for to help point ya in the right direction

**Comment by ChrisTheDBA** [comment]
it's for the t-shirt, The logo will be one color. The green benzene ring
needs to be a negative component so the t-shirt color will show through.

Chris Mathews

**Comment by jcwlib** [comment]
Final designs - 
https://drive.google.com/open?id=0B9xGF61MFIr6alFKQ2JTOFJCY1NoZmdYOFdkNEE3VDV4NTI0

https://drive.google.com/open?id=0B9xGF61MFIr6NGNkOTd1T0FzNE83S2gzQ0dvSTJtWlp4SFNB
