### ISSUE TITLE
Update for partners - more prominent

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1096]
Janel, some requests for you, no rush.

1) Can we work on this page a bit:
http://ncopenpass.com/about/partners/

The logo sizes are inconsistent is the main issue I'm seeing.

2) Can we make the partners more prominent throughout the site. I'm wondering if a widget/banner in the footer where we can make the logo's the same scale and maybe in grey, also clickable to their site.

3) Could we also give some love to our partners on this page:
http://ncopenpass.com/nc-open-pass-events/

same thoughts on smaller logo's that link back to their respective sites

**Comment by jtawes** [comment]
I have resized the logos on the about/partners page and added a gallery of the sponsors to the bottom of the nc-open-pass-events page. I am working on adding direct links to the gallery images.

**Comment by jhibbets** [comment]
Thanks, looks great! Can we add that gallery to each subsequent event page
as well, that would be assume.

**Comment by jtawes** [comment]
Sure, I just wanted to be sure you were happy with it before duplicating it. Making the gallery images have links to their respective sites will require me to add a plugin, I will be working on that soon.

**Comment by jhibbets** [comment]
I think having the links are a nice to have, maybe we can have the gallery
just link to the sponsor page?

**Comment by jtawes** [comment]
By default, clicking on the images just pulls up a larger version of the image. I will work on either getting it to link to the sponsors page or individual sites.
