### ISSUE TITLE
Update eventbright with ATO discount option

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1098]

**Comment by jhibbets** [comment]
Cleaned up HTML
Moved old events to the bottom
Updated profile
Removed old tickets
Changed early bird ticket date to expire on 8/31

https://www.eventbrite.com/e/nc-open-pass-2018-tickets-42176718701

**Comment by jcwlib** [comment]
social media post about early bird extension set for tomorrow
