### ISSUE TITLE
Create 2018 Civic Camp Flyer

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1099]
Jennifer Tawes - use language from last year's flyer and adjust for new schedule and partnerships on the hackathon with Innovate Raleigh and AT&T

https://drive.google.com/open?id=0B6evljh09h0QUm1oSjQxYm4yNkU

**Comment by jcwlib** [comment]
Janel's quick and dirty version to use at the design sessions https://drive.google.com/open?id=1JwybXwCEno4kD7lp6QtKoGhfKGHOvADG

**Comment by jtawes** [comment]
I have finished this, what file format would be most useful and what folder would you like it saved to?

**Comment by jcwlib** [comment]
Pdf and in the marketing folder is fine

**Comment by jtawes** [comment]
It's there now, let me know if we need any changes. If not, I'll move this issue to done.

**Comment by jcwlib** [comment]
Looks great - can you take off the design session line though and add "DISCOUNTED PRICES FOR STUDENTS AND GOV’T EMPLOYEES" instead?  We want to use this flyer going forward and not specifically for the design sessions.

**Comment by jtawes** [comment]
Hi Janel,

I deleted the file that was on the shared drive and uploaded the new one
with changes. Let me know if you need any other edits.

Thanks!
Jennifer

**Comment by jcwlib** [comment]
Thanks!  The edits look good to me.  I'm going to mark this item closed
