### ISSUE TITLE
T-shirts for Civic Camp

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1108]

**Comment by jcwlib** [comment]
@TaxLadyTracy see ticket 1092 for links to designs

**Comment by TaxLadyTracy** [comment]
I have emailed my tshirt guy to see what format he needs for this.

**Comment by TaxLadyTracy** [comment]
@jcwlib he said jpg file will work.  can you email them directly to me at tracy.mathews1125@gmail.com

**Comment by jtawes** [comment]
I just emailed the png and jpg file of the transparent logo to Tracy.

**Comment by TaxLadyTracy** [comment]
Shirts have been ordered.  TMathews
