### ISSUE TITLE
Transloc Corp participation

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#111]

**Comment by lenaecb** [comment]
Are we looking for sponsorship or just speaking? Or both?

**Comment by ChrisTheDBA** [comment]
Both. EIther.

**Comment by lenaecb** [comment]
Good deal. Approached them about both so will let you know what they decide. Where can I find the sponsorship package?

**Comment by ChrisTheDBA** [comment]
It's in the 2016 folder the file is called 2016 Prospectus

**Comment by lenaecb** [comment]
Don't think we'll be able to get a sponsorship pulled together for this from TransLoc this year but definitely something we can consider for next year. 

However, if we're looking for speakers from our company (either prominent or in lightening rounds) let me know so I can get that going with folks.
