### ISSUE TITLE
Civic Camp - Printing needs

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1111]
What needs to be printed? Banners, etc.

**Comment by jcwlib** [comment]
tracking in this spreadsheet - https://docs.google.com/spreadsheets/d/1L3bP3Gj4421--GA3x4n1x5CDHS4BV0DSCcbHheOnj7A/edit?usp=sharing

**Comment by jcwlib** [comment]
standing banner is from VistaPrint

**Comment by jcwlib** [comment]
technically we can use this ticket to track the printing of the business cards - they are included in the linked spreadsheet above.  ticket 1043 was to track the graphics work which is complete
