### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1112]

**Comment by jtawes** [comment]
What size stickers? Just the logo for NC Open Pass or include Civic Camp?

**Comment by jcwlib** [comment]
we can talk more at 11, but I check out the spreadsheet I linked in the marketing notes and ticket 1138

**Comment by jtawes** [comment]
I just found the spreadsheet! Sorry about that.

**Comment by jtawes** [comment]
Done

**Comment by jcwlib** [comment]
Reopening - to track the actual ordering

**Comment by jcwlib** [comment]
New StickerMule account is created and credentials shared with @ChrisTheDBA and @jtawes - need to upload designs with the quantities and then the order can be placed

**Comment by jhibbets** [comment]
FYI - Your proofs are ready for R223572342 (via NCOpenPass gmail account)

**Comment by ChrisTheDBA** [comment]
Order on the way
