### ISSUE TITLE
Civic Camp - Print signs for A-frames

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1113]
Leo to send sizes.

**Comment by snewt-n** [comment]
@dtraleigh Leo last year A Frame posters were 24.5"x36.5" - did we want to stick with those sizes?

**Comment by TaxLadyTracy** [comment]
We didn't have the a frame last year those were the inside signs

**Comment by snewt-n** [comment]
oh whoops I feel silly @TaxLadyTracy I thought a-frames were easels

**Comment by dtraleigh** [comment]
I'm out of town for the weekend. On Monday, I plan to use the usual meeting
time to knock out tasks. I'll post the size we need then.

Here's basically what I have. I'm sure the sizes are pretty standard.
Again, I have two so we need 4 posters. (front and back)

https://goo.gl/images/UZ59gv

**Comment by dtraleigh** [comment]
24"W x 36"H is the size of the posters for the a-frames signs. Again, we have two brown ones and they are front and back.

**Comment by dtraleigh** [comment]
For reference, this is them. http://a.co/d/aQRJJln
