### ISSUE TITLE
Civic Camp - logistics blog post

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1114]
Where to park, what to expect, etc.

**Comment by jcwlib** [comment]
Last year's post - http://ncopenpass.com/blog/navigating-around-downtown-raleigh-for-citycamp-nc/

Let's plan to post on Monday, Sept 17 - draft ready for review by Thursday, Sept 13

**Comment by dtraleigh** [comment]
Got it.

**Comment by dtraleigh** [comment]
@jhibbets @ChrisTheDBA @jcwlib  Who can give me an account to the ncopenpass site so I can draft a blog post? Writer access is fine.

**Comment by jcwlib** [comment]
@jtawes and @FrankCJones can one of you give Leo a website account

**Comment by jtawes** [comment]
Just sent Leo an email.

**Comment by dtraleigh** [comment]
@jcwlib Logistics blog post draft is ready for review. Please edit freely or let me know if anything you think is missing. Wasn't sure of the right category.

**Comment by jtawes** [comment]
I set up a page for it rather than a post, if it is ok with you I’ll move the content to the page?

**Comment by dtraleigh** [comment]
Have at it!

**Comment by jtawes** [comment]
I've added the content to http://ncopenpass.com/civic-camp/civic-camp-venue/

**Comment by jcwlib** [comment]
Thanks @jtawes and @dtraleigh - looks great!
