### ISSUE TITLE
Civic Camp - Lanyards

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1117]
Badges. Buy and prepare

**Comment by dtraleigh** [comment]
Need them designed, simple with logo.

**Comment by jcwlib** [comment]
@jtawes need to design a badge template that has NC Open Pass logo with @ncopenpass twitter handle and #civiccampnc hashtag. @TaxLadyTracy will then use this template when printing the name badges

**Comment by jtawes** [comment]
Where can I get dimensions for the lanyards that will be ordered? Is it something that will be printed and slid into a plastic sleeve? Is it a horizontal or vertical orientation?

**Comment by jcwlib** [comment]
From Tracy: Avery 5390 badge template - adding @snewt-n to this item as well

**Comment by jtawes** [comment]
Will the lanyards be oriented vertically or horizontally?

**Comment by TaxLadyTracy** [comment]
Just need the name badge template.  I opened this ticket for me to order the lanyards no artwork for lanyards.

**Comment by TaxLadyTracy** [comment]
Lanyards have come in and ready for name badges.  Closing this ticket.
