### ISSUE TITLE
Review and update marketing contacts list

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1134]
https://docs.google.com/spreadsheets/d/1KOXHZM4t1LB2jmx00XlCmXbCjIBxzaBDBQ7iVB4R6UE/edit?usp=sharing

**Comment by zachambrose** [comment]
@wildca01t  can you pick up your names/organizations from last year? @zachambrose, Yes!

**Comment by zachambrose** [comment]
Everyone, can you look at the names from 2017 (Copy of Marketing) and see if there any that aren't currently claimed on the 2018 tab that you take?  Thanks!

**Comment by jhibbets** [comment]
Mine have been updated and sent.
