### ISSUE TITLE
Create Graphics needed for Civic Camp signs

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1138]
Reference this spreadsheet 

https://docs.google.com/spreadsheets/d/1L3bP3Gj4421--GA3x4n1x5CDHS4BV0DSCcbHheOnj7A/edit?usp=sharing

**Comment by jcwlib** [comment]
- 4 "Civic Camp this way" signs for 2 A frames - dimensions 24'W x 36'H
- 3' x 3' Podium Sign - Civic Camp Logo (perhaps with @ncopenpass handle and #civiccampnc hashtag)
- '3 x 5' Welcome Sign - "Welcome" in middle with "Follow and tweet the event @ncopenpass #civiccampnc
- Need directional signs for Artspace (Friday evening events)
 From Leo: for the artspace directional signs, can you add that we are in "Gallery Two"? It's not difficult to find but it does mean you have to go in the lobby, up the stairs/elevator, and down a hall  
- Need directional sign for Red Hat Lobby pointing out where in the Annex the rooms are. 
Here is a map and more details of the rooms we are using.

**Comment by ChrisTheDBA** [comment]
The largest we can get is 24" by 36" Those are $55 each.
