### ISSUE TITLE
Table inventory

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#114]
Need to close the loop with Ian Henshaw regarding tables, extension cords

**Comment by ChrisTheDBA** [comment]
Sent email to Ian H

**Comment by ChrisTheDBA** [comment]
2 @ 6'x2 1/2' White Plastic
4 @ 6"x2 1/2' Melamine Wood
5 @ 4'x2' Melamine Wood
 we'll need more

**Comment by dtraleigh** [comment]
Any thoughts on doing a rectangular table setup versus a circle table
setup? My current thinking is to rent a lot of rectangle tables and create
a table setup similar to what we had at the commons last year.

I will proceed with getting quotes for the rectangular tables unless other
think a circle table setup might work better.

**Comment by ChrisTheDBA** [comment]
We will need tables. Long rect will make sense for Friday morning, but round ones for fri afternoon ans Saturday. Can you look at both?

**Comment by dtraleigh** [comment]
I will look into it. My first idea is to have the front half of the room
(facing the stage) with rectangle tables. The back half of the room can
have the circle tables. This way, we have both kinds for different groups,
small and large.

**Comment by ChrisTheDBA** [comment]
I think the round ones are more conducive of conversations while the rectangular are for audiences looking at the stage. So , in short, good call.

**Comment by dtraleigh** [comment]
Yeah, maybe have extra circle tables set to the side so that we
"transition" from the presentation portion (rectangle tables) of the Friday
morning to the collaborative/conversation portion of Friday
evening/Saturday. (add more circle tables)

**Comment by dtraleigh** [comment]
Chris, is Ian committed to providing those tables as well as delivery?

I have an idea of what we need now but by renting them, the company also
delivers. I need to nail down those logistics if we're also getting tables
from Ian. Can you start an email thread?

**Comment by dtraleigh** [comment]
I cannot make the 8/8 Citycamp meeting but I do have my "table rental
proposal" put together. This is what I'd like to go with, please look it
over and let me know what folks think.

It's all here:
https://docs.google.com/a/dtraleigh.com/document/d/1YNocB3deOyaQx4h2yTnx69SYnlo3lGWJ5kMBdUDqLLE/edit?usp=sharing

In short, with Ian providing some tables, we will rent the rest from
Deejay's Rentals. Quote is for $372.56.
- This is for tables only (combination of circle and rectangle) I'll look
  into table covers/linens later, there may be a much cheaper option than
  renting through Deejay's also.
- They will deliver the tables to venue on Thursday 1-4pm.
- They will pick up the tables at venue on Saturday 3-6pm.

I'll give the group a few days to digest this and then I'd like to book it.
(spend money) :)

Then, this item is closed.

**Comment by ChrisTheDBA** [comment]
That looks great.

**Comment by dtraleigh** [comment]
Table rental has been booked. With Ian and Deejay's Rental delivering on Thursday and picking up on Saturday, we are good for tables.
