### ISSUE TITLE
Correct Red Hat logo

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1147]
Please update the Red Hat logo on the site. The Red Hat logo can not be stacked and must have shadowman on the left, despite what Google searches might present to you ;)

**Comment by jtawes** [comment]
![red_hat_logo_redhat](https://user-images.githubusercontent.com/38951776/44357272-96a50880-a47f-11e8-9db4-a69635e99612.png)
Is this the one to use then?

**Comment by jhibbets** [comment]
Yes. It should already be uploaded in the media folder on on Drive.
