### ISSUE TITLE
Write Civic Camp blurb for CAC newsletter

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1150]

**Comment by jhibbets** [comment]
Civic Camp (formerly City Camp NC) is an annual civic tech event that brings citizens, government change agents, and businesses together to openly innovate and improve our communities. It's happening in Raleigh on September 21-22, 2018 at the Red Hat Annex and Artspace. For more details, visit: http://ncopenpass.com/civic-camp/
