### ISSUE TITLE
Update organizers page

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1161]
http://ncopenpass.com/about/organizers/

1) Move Leo down to regular size
2) Add Janel to the top 4 (bigger image)
3) Add: Jennifer, Frank, Sophia, Stephanie, Tony, Tracy, and Jim

Please make sure I didn't miss anyone from the organizers active sheet.

**Comment by jcwlib** [comment]
Add Lisa and update the text at the top to not be Civic Camp specific

**Comment by jtawes** [comment]
I'm sending out an email to everyone, Lisa isn't on the Organizers Contact Info 2018 spreadsheet, what is her email address? Thanks!

**Comment by jtawes** [comment]
I have updated the Leadership Team and moved Leo's picture. I sent an email out to all of those listed above to be added and am now awaiting a response regarding what information to include and the image they would like posted.

**Comment by jtawes** [comment]
Done
