### ISSUE TITLE
Create sample invitation language for personal invites

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1164]
Need reg page to link to .

**Comment by jcwlib** [comment]
We have two documents started in the Marketing folder already

https://docs.google.com/document/d/1aCPzDkE_hnL3ZAHJDJY_7vXw_xLVrueT8WCLNlMS7AQ/edit?usp=sharing

https://docs.google.com/document/d/1MfvfuT1CoN4ZE4DTtt92Hy0IJItHpnxW1trVkeqAGzs/edit?usp=sharing

Can we combine and reuse what is in these documents?

**Comment by jcwlib** [comment]
http://ncopenpass.com/civic-camp/civic-camp-registration/

**Comment by snewt-n** [comment]
Yeah so that's just the one I sent last year, but templat-ized -- I thought it'd be useful to keep the actual template one as a template, and update with this year's info in a separate doc. If y'all don't want that's fine.

**Comment by jcwlib** [comment]
Updated this document now that schedule and speakers are set https://docs.google.com/document/d/1MfvfuT1CoN4ZE4DTtt92Hy0IJItHpnxW1trVkeqAGzs/edit?usp=sharing
