### ISSUE TITLE
Name badges

### ISSUE THREAD

**Issue by TaxLadyTracy** [ncopenpass/NCOpenPass#1173]

**Comment by TaxLadyTracy** [comment]
This is for me to keep track of my task.  
Avery labels 5390 to be printed horizontal.
leave a space for me to put a clear sticker with participants name.

**Comment by jtawes** [comment]
We can set up the template to print the participants name if you have a
spreadsheet of names. Just let me know.

**Comment by ChrisTheDBA** [comment]
Just need the graphics. have all that in place.
Chris Mathews

**Comment by TaxLadyTracy** [comment]
Thank you but I have a process.  Names don't usually get printed until the day before so I need to do that myself.

**Comment by jtawes** [comment]
Is this what you have in mind?

**Comment by TaxLadyTracy** [comment]
Sorry @jtawes  I don't see anything so I can't say

**Comment by jtawes** [comment]
Here, try this link:

Lanyard Design
<https://drive.google.com/open?id=1R5zNbSUBhnselo7Grstw6Aj48ECc_TAy>

**Comment by snewt-n** [comment]
Looks good, should it have the dates on it? Do we have  a laser printer so it doesn't smear with all that blue?

**Comment by ChrisTheDBA** [comment]
All we need is a logo to replace the one on this picture.



Chris Mathews

**Comment by jtawes** [comment]
Chris, I don't see which picture you are referring to. Do you have a link?

**Comment by ChrisTheDBA** [comment]
It's just a picture off my phone of last year's badge.

https://drive.google.com/file/d/1rc5ETcXEHWvymoBSKQxG_sWDA0lTQyWF/view?usp=sharing

Chris Mathews

**Comment by jcwlib** [comment]
hashtag needs to be updated to #civiccampnc as well.

**Comment by TaxLadyTracy** [comment]
You beat me to it...I was just asking Chris before I commented.

**Comment by jtawes** [comment]
That is the hashtag I put on the design I uploaded. Do you want me to
change the design?

**Comment by jcwlib** [comment]
Jennifer -

Please update your design to not have the blue background behind the logo
and the twitter handle and hashtag.

--Janel

**Comment by TaxLadyTracy** [comment]
Jennifer check the spelling that's what we are talking about #civicampnc or
#civiccampnc?  Just don't want to print these out and find out it's wrong.

**Comment by TaxLadyTracy** [comment]
Please keep in mind name badges are printed from my house not a outside
printer and I do not charge NC Open Pass for my ink :)

**Comment by jcwlib** [comment]
It should be  #civiccampnc

**Comment by jtawes** [comment]
More like this?

Lanyard Design Option 2
<https://drive.google.com/open?id=1TW4vGN5qug6MIOEQdtBrHiiwkML2eOSd>

**Comment by ChrisTheDBA** [comment]
good, but change the hashtag.
Chris Mathews

**Comment by jcwlib** [comment]
Yes - but the hashtag needs to be #civiccampnc - with two c's

**Comment by TaxLadyTracy** [comment]
and if you want the hash tag and twitter handle larger that would be fine
too.

**Comment by TaxLadyTracy** [comment]
And I know it may be petty but could we please stop calling this a lanyard
design.  It is a name badge and that's what I look for :)

**Comment by jtawes** [comment]
Updated the hashtag, do you want me to take out the green color?

**Comment by TaxLadyTracy** [comment]
No I am good with the green and blue!!  Looks great

**Comment by jtawes** [comment]
Final name badge design uploaded to shared drive (Name Badge) folder
Name Badge
<https://drive.google.com/open?id=1se-VxHm9Op4t9kbVQ3VEwSoD9EmhyAzv>

**Comment by TaxLadyTracy** [comment]
@jtawes  I printed a test and this does not fit the template for my labels.  Can you just send us the artwork and we will complete it?

**Comment by jtawes** [comment]
Try this PDF first, it should be the right dimensions, the other file was
the artwork only, this one has the template from avery included: Avery
Template Name Badges
<https://drive.google.com/open?id=1z1GI7H9uiDXPJzyEZNEzl2GX1Er6dCcc>

If that doesn't work, here is the artwork for one badge (two file formats):
Single Name Badge as a PNG File
<https://drive.google.com/open?id=1jIHE6arJaJ-TiLsl01p_LZmeaQO3ehaO>
Single Name Badge as a JPG File
<https://drive.google.com/open?id=1Lez1Z_ODwEsxvXjJetH2whPalguc7xRs>
