### ISSUE TITLE
Find out when organizers can get into Annex

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#1174]

**Comment by jhibbets** [comment]
Friday, confirmed that security will be there at 7am. However, I or another Red Hatter will need to be present.  I will work on that. I got distracted at forgot to ask about Saturday, but let's plan on 7:45 ish.  I will confirm.

**Comment by jhibbets** [comment]
Confirmed 7:45 for Saturday. Note, we'll be starting at 9:15
