### ISSUE TITLE
Update Civic Camp Speaker Page

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1178]
Need to add pictures and bios - grouped by keynote and lightning talks

**Comment by jhibbets** [comment]
grouped by keynote, **panels,**  and lightning talks

**Comment by HoneyBadger126510** [comment]
I'm working on the speakers page right now. Marlo Gaddis is listed in the schedule as a keynote speaker but I don't have speaker info on her in the keynote speaker spreadsheet. Is it located somewhere else?

**Comment by HoneyBadger126510** [comment]
Just finished a first pass at the page, there are some speakers that need information on their topic, and some that need editing in their bio. Do we have panelists for both panels? Also I haven't added contact links for everyone yet. But take a look and feel free to send me any edits. I'll work on it more tomorrow and Sunday.

**Comment by jcwlib** [comment]
@jtawes thanks for tackling this task so quickly.  

1) Let's order the speakers in each section, alpha by last name. 
2) Melanie Mazanec is only doing a lightning talk - please remove from the keynote list 
3) @jhibbets do we have a list of people on Bonnie's panel?
4) Need to add emcee - Lori Bush
5) Remove Carole Williams, Keith Stewart, Evan Diehnelt from Lightning Talks - they are not on the final schedule
6) @jhibbets - do we have information for Janelle Bailey - she's on the schedule but not in the submissions.

**Comment by HoneyBadger126510** [comment]
1. Done
2. Done 
4. Do I add her as a keynote? If not, where would you like her and with what title?
5. Done

**Comment by jcwlib** [comment]
Here is a page for Lori Bush - I would list her at the top as she is emceeing Friday morning (keynotes and panelists) https://www.townofcary.org/mayor-council/town-council/council-members/lori-bush

**Comment by jtawes** [comment]
It seems a little awkward to title her as "emcee", any alternatives?

**Comment by ChrisTheDBA** [comment]
We've used emcee in the past and it hasn't seemed awkward.

BTW, Chief Alvarez is Fayetteville Fire Dept, not Wake County Public Schools
Chris Mathews

**Comment by jtawes** [comment]
Not a problem. Do you want a separate header line that is "Emcee" or place
her inside the "Keynote Speakers"?

Also fixed Alvarez, thanks!

**Comment by HoneyBadger126510** [comment]
Added Lori Bush

**Comment by jcwlib** [comment]
need to add judges to the page once @zachambrose and @jhibbets finalize them

**Comment by jcwlib** [comment]
Open Data Panel details were sent via email from Chris (9/12) and Marlo submitted her talk topic, bio and headshot via the keynote speaker form.  Judges are confirmed -see Zach's email from yesterday (9/11)

**Comment by jtawes** [comment]
Panelists and judges have been added.

**Comment by jcwlib** [comment]
I tweaked Marlo's profile as well

**Comment by jtawes** [comment]
Do we have a fourth panelist for John Stephen's group or will it just be
three?

**Comment by jcwlib** [comment]
I believe the 4th panelist is Jill Bjers https://www.meetup.com/Open-Charlotte-Brigade/members/114660122/ @ChrisTheDBA  - correct?

**Comment by jtawes** [comment]
Done

**Comment by jhibbets** [comment]
Confirmed the 4th panelist is Jillzey.

**Comment by jcwlib** [comment]
@jtawes - we have an additional speaker for Friday night - Corky Over from AT&T First Net - he provided details in the keynotes spreadsheet - https://docs.google.com/spreadsheets/d/11NZJ7bWNhqgrMdcwnD5Xs7R1U4ngPwkqgfObHaGTh98/edit#gid=1081861876

**Comment by jtawes** [comment]
Added Corky to speakers page under 'Keynote Speakers'
