### ISSUE TITLE
Update Partners page

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1179]
@jtawes the WeWork hyperlink on the partner page and the bottom of the Civic Camp main page isn't right. The url doesn't directly go to their website. 

Also we need to add Innovate Carolina - logo is in the sponsor logo folder.

**Comment by HoneyBadger126510** [comment]
Done

**Comment by jcwlib** [comment]
@jtawes I don't see WeWork on the main Partners page anymore.

**Comment by HoneyBadger126510** [comment]
Sorry, fixed it. I had to change the galleries to get the links to work.

**Comment by jcwlib** [comment]
thanks!
