### ISSUE TITLE
Create Civic Camp Sponsor Poster

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1185]
ready to draft this poster for printing

**Comment by jtawes** [comment]
I'm working on this right now, do we have a contact at WeWork we can reach out to and ask for an 'eps' or 'svg' file of their logo? I only have a jpeg and I'm afraid it will look grainy when it is printed at this size.

**Comment by ChrisTheDBA** [comment]
Coordinate with @snewt_n. I believe she already did it
Chris Mathews

**Comment by jtawes** [comment]
Here is the first draft of the partners poster
![CivicCampPartnersPoster.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6b412c71616500119ddf73/125516c66e82c728ace21e0d46cb9d8c2a81a0a882f98f42b649fe913b55177c3a10a63932c9a138ad4d71040c1b5ca6535d5910a9fa882ba7b539748a5d0cb9846d5d25973416a5ee9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3d180d1e89f75535a49c42da15.png)

**Comment by jtawes** [comment]
I contacted Sophia and made corrections:
![CivicCampPartnersPosterV2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6b412c71616500119ddf73/125516c66e82c728ace21e0d46cb9d8c2a81a0a882f98f42b649fe913b55177c3a10a63946d7a164fd52690e050a1de853524d41faaddc28a7b63d738f580becd6390a74c46c40a5bf8b49ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b061e81f85d35a9904bcf5ee406.png)

**Comment by jcwlib** [comment]
updated poster looks good to me @zachambrose do things look right to you?

**Comment by snewt-n** [comment]
please alphabetize names of sponsors within level to avoid the appearance of preference

**Comment by jtawes** [comment]
![CivicCampPartnersPoster.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6b412c71616500119ddf73/125516c66e82c728ace21e0d46cb9d8c2a81a0a882f98f42b649fe913b55177c3a10a63932c9a138ad4d71040c1b5ca6535d5910a9fa882ba7b539748a5d0cb9846d5d25973416a5ee9003ad43eb7edf10d8eff6df0ed2e22f24ee818e4a3d19051a89fc5d32a2914dda15.png)

**Comment by jcwlib** [comment]
@ChrisTheDBA  - ready for printing
