### ISSUE TITLE
Write blog post around the lightning talks

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1186]

**Comment by jcwlib** [comment]
draft started and comments are welcome https://docs.google.com/document/d/1zEIaEWHYvHt7JTQ_vCtjLPcMZn76Lp-9lRCvEoGjmGc/edit?usp=sharing

**Comment by jhibbets** [comment]
Reviewed, made some minor edits/additions. approved.

**Comment by jcwlib** [comment]
saved as draft on website - will post next week

**Comment by jhibbets** [comment]
Can we schedule posts on the WordPress site? If so, I would schedule and close this card.

**Comment by jhibbets** [comment]
Oops. my board wasn't referenced. Good to go here.
