### ISSUE TITLE
Write blog post about keynote speakers

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1187]

**Comment by jcwlib** [comment]
drafted a short and sweet blog post - it could use some love =( https://docs.google.com/document/d/1wlk1ep0qOS517O_3gekpIffsLl_8YTV6VWO6BvZnYNc/edit?usp=sharing

**Comment by jhibbets** [comment]
I have reviewed and made additions. Approved.

**Comment by jcwlib** [comment]
Posted on webite and scheduled on social media
