### ISSUE TITLE
Draft WRAL TechWire blog post

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1189]
need to draft a blog post that highlights the speakers, prize money, safari access, DataPalooza kickoff

**Comment by jcwlib** [comment]
@jhibbets here is a draft using last year's framework.  Not sure what photo you want to include https://docs.google.com/document/d/1o0sN-hp-dHhlK6oZub7OeGuvopONZH9cKNtfPafguDo/edit?usp=sharing

**Comment by jcwlib** [comment]
added blurbs about the cash prize, O'Reilly access and a placeholder for the QGIS class

**Comment by jhibbets** [comment]
I have reviewed this and made update. As soon as we get the other pieces, this is ready to ship. I am happy to ship to Rick/WRAL Techwire. Might hold off until Sunday to send.

**Comment by jcwlib** [comment]
@jhibbets thanks for the review and edits.

**Comment by jhibbets** [comment]
@jcwlib Once @zachambrose confirms the sponsors, I'll send this to WRAL on Sunday.

**Comment by jcwlib** [comment]
@jhibbets - looks like we are good to go - @zachambrose, @ChrisTheDBA  - any concerns?

**Comment by ChrisTheDBA** [comment]
Well, yes but not with the post. looks good
Chris Mathews

**Comment by jhibbets** [comment]
Send to Rick
