### ISSUE TITLE
Track donated tickets for scholarships

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1192]

**Comment by zachambrose** [comment]
5 from data.world
Total - 5 scholarship tickets

**Comment by zachambrose** [comment]
4 from UserVoice
Total -  9 scholarship tickets

**Comment by zachambrose** [comment]
6 from O'Reilly
Total - 15 scholarship tickets

**Comment by zachambrose** [comment]
1 from Ann at DevOps days
Total - 16 scholarship tickets

**Comment by jcwlib** [comment]
Posted generally on twitter about scholarships being available - listed the new gmail account as the way to request them @jhibbets

**Comment by jcwlib** [comment]
Included in the newsletter going out tomorrow as well.

**Comment by jhibbets** [comment]
Note  I gave out two scholarships.
