### ISSUE TITLE
Write blog post about unconference

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1193]
repurpose the post from 2017

**Comment by jcwlib** [comment]
draft started and open for comment - https://docs.google.com/document/d/1_PGto4BpgB6qOB6b2y1P8ZkFRGa-Zg_iQdQcTDinnXU/edit?usp=sharing

**Comment by jhibbets** [comment]
@jcwlib this will need a second set of eyes, as I've added some new material. but good to go from my side.

**Comment by jcwlib** [comment]
@jhibbets - I like the new material.  I made some small edits - i've saved as a draft on website and will post next week.

**Comment by jhibbets** [comment]
+1
