### ISSUE TITLE
Add Safari trial to Civic Camp slide deck

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1195]

**Comment by zachambrose** [comment]
@jhibbets we can reassign if someone else is doing the slide deck.

Here is the direct url: http://oreilly.com/getsafari?code=NCOP18  or you can offer oreilly.com/safari, promo code NCOP18.

**Comment by jcwlib** [comment]
First Net Developer Portal https://developer.firstnet.com/firstnet

**Comment by jhibbets** [comment]
done
