### ISSUE TITLE
Recording Presentations

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1196]
As an enhancement to the video recordings, I'd like to do a mashup of the presenter plus the presentations. I'd like to run a recording of the laptop screen that is presenting.

@jhibbets will all the speakers and presentations be combined into one big one or at least be run on one laptop? (compared with each presenter plugging in their own device?)

**Comment by jhibbets** [comment]
My preference is to use one laptop with one large presentation.

**Comment by dtraleigh** [comment]
Awesome. That should be easy then. I can run the laptop that runs the
presentations so recording is easy.
