### ISSUE TITLE
Drinks for Annex

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#1197]
We will plan on water and lemonade for attendees and stay away from the drink cooler

@jhibbets does that sound like a plan?

**Comment by jhibbets** [comment]
Sounds good. Maybe have some tea?

**Comment by jhibbets** [comment]
Need anything else from me here? TBH I think we can use some of the beverages in the fridge, we'll just hide the snacks.

**Comment by TaxLadyTracy** [comment]
I think I'm good this was just my reminder.  I did order tea and I know
there is a water refill station on site so that helps.
