### ISSUE TITLE
Remove Carsi Tong from mailing lists

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1199]

**Comment by jcwlib** [comment]
@jtawes - remove Carsi from the organizers page as well.

**Comment by jcwlib** [comment]
I removed Carsi from the organizers page

**Comment by jhibbets** [comment]
Done. I also removed Adam Martin, Ashsley, and Natalie.

**Comment by jtawes** [comment]
I'm still awaiting a response from an email I sent out to the additional
organizers for pictures and info. I sent a follow up email this morning.
