### ISSUE TITLE
Flickr to Instagram

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#120]

**Comment by ChrisTheDBA** [comment]
See how to link Instagram and Flickr - maybe IFTTT

**Comment by lenaecb** [comment]
Def IFTTT moment I am sure

**Comment by ChrisTheDBA** [comment]
IFTTT is a website that automates website and app interconnections like auto post to twitter when a FB post is made, send instagram posts to flickr account in this case

**Comment by lenaecb** [comment]
Yes I understand what it is, I was saying that yes I agree this can be done via IFTTT

**Comment by dtraleigh** [comment]
Is our Flickr that active? Why not just post to Instagram directly?

**Comment by jhibbets** [comment]
Traditionally, our Flickr see a ton of activity /after/ the event.

**Comment by ChrisTheDBA** [comment]
The strategy is to reach people where they live hence interconnect as much social media as possible. But I vote to lose Friendster and MySpace.

**Comment by lenaecb** [comment]
Don't you have to be a member to actually upload photos to it? I don't have the login but I can see that there are only 12 members with @dtraleigh & @jhibbets providing 80%+ of the photos... I think if we want more tagging that giving only a single platform option that requires less work than Instagram is worth a focus. To your point about where people live, I'd be interested to see the traffic numbers going to the CityCamp flickr page.

**Comment by lenaecb** [comment]
Not trying to be difficult here but also think being where people are most frequently and consolidated the channels we use will make everyone's lives a little easier.

**Comment by dtraleigh** [comment]
The Flickr group was started 6 years ago when CityCamp first started so
there was activity on it back then. (at least I thought so)

Now, I've used it as a dumping ground for photos, giving them a creative
commons license for anyone to use as they need. In my opinion, the photos
were there for sharing AFTER the event. Throughout the event, I walked
around with a DSLR and shot tons of photos but organized and uploaded them
a few days later.

In the year 2016, smartphone cameras can take pretty decent indoor photos,
especially low-light (during lightning talks) that we can probably rely on
phones for capturing photos. They can be shared during the event and
compiled afterwards for that "archive" that Flickr has become.

Anyway, I like taking photos so during the event would love to help
contribute to social. Just tell me what to do. :)

**Comment by lenaecb** [comment]
I think there is a place for both and we'll def push Instra this year (noticed in searching just now that we had people using #CityCampNC to tag their insta photos for 2015 and there was about 35 or so contributors). @ChrisTheDBA - did you say you setup the Insta acct?
