### ISSUE TITLE
Add data.world to partners page as Silver sponsor

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1200]

**Comment by HoneyBadger126510** [comment]
Done

**Comment by jtawes** [comment]
zach could you please check ncopenpass.com/about/partners and let me know if that is correct, some of the sponsors aren't listed on the worksheet and I want to make sure their levels (diamond/platinum/silver etc) are correct

**Comment by jcwlib** [comment]
Here is what we have in the TechWire post:

Diamond partner: Innovate Raleigh

Platinum partners: HQ Raleigh, Innovate Carolina, Red Hat, WeWork

Gold Partners: O’Reilly, Raleigh 4U (Economic Development City of Raleigh)
Silver Partners: All Things Open (ATO), data.world

Bronze Partners: UserVoice, DevOpsDays Raleigh

Community partners: Raleigh MAIN Events
