### ISSUE TITLE
Red Hat passes

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1205]

**Comment by jhibbets** [comment]
@zachambrose @ChrisTheDBA  did either of you coordinate with Red Hat about their passes / scholarships. I'm happy to do this, I just don't want to do it if it's been done already.

**Comment by ChrisTheDBA** [comment]
I will email Yolanda.

Chris Mathews

**Comment by jhibbets** [comment]
What's the over under that see sends it to me?

**Comment by ChrisTheDBA** [comment]
I don’t want none of that action.

**Comment by jhibbets** [comment]
FYI - Last year I gave the Red Hat  scholarships to ChickTech.
