### ISSUE TITLE
Review ticket types

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1207]
All - I just updated the eventbrite ticket types to make the names more clear. I originally had NC Open Pass on all types. I removed that and added which days/portions of the the event each ticket was good for. I also added a free ticket to lightning talks only and lowered the number of available tickets.

Can you please have a look and give me feedback, anything not clear, needs updating, or missing ticket type?

https://www.eventbrite.com/e/nc-open-pass-2018-tickets-42176718701

**Comment by jcwlib** [comment]
Looks good to me - I like the flexibility!

**Comment by ChrisTheDBA** [comment]
Very explicit, but a lot of text and I gave up. I hope I'm the exception.
"The goldfish effect"

Chris Mathews
