### ISSUE TITLE
Civic camp event blocks on website

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1208]
Can you make sure all the event civic camp blocks on the site have the correct times?

This is the master schedule: http://ncopenpass.com/civic-camp/civic-camp-schedule/

For example, this page has the wrong times listed:
http://ncopenpass.com/civic-camp/

**Comment by jcwlib** [comment]
@jtawes I would recommend we take the image of the Civic Camp Flyer off the main page.

**Comment by jtawes** [comment]
Do you want to place it somewhere else? I just made the edits and re-uploaded it.

**Comment by jcwlib** [comment]
Oh - I forgot that you had the original files - that works ;)

**Comment by jtawes** [comment]
I deleted the incorrect flyers and uploaded the edited version to the shared drive.
