### ISSUE TITLE
citycampnc.org site is missing public html files

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1210]
If you try to visit the citycampnc.org / .com sites, you'll see we get an error message - "Error establishing a database connection"

I opened a support chat with the hosting company, Just Host, and discovered that the Word Press install is missing. In fact, all files in public HTML folder are gone.

I'm not how this happened. The WP database is still in tact. The last change I made was to update the db directly for the website location (https vs http). 

Does anyone else know what's going on here or have a way to restore the site?

**Comment by jhibbets** [comment]
@frankCJones @Jtawes - just a quick update here. I manually uploaded 4.3 v of Wordpress last night but held short of doing the installation. I am on the phone now with the hosting company seeing if they have a back-up to restore. the one I took before the migration to open pass site was in my /tmp folder and removed during a recent reboot. 

If either of you has any idea what happened here, that would be helpful to troubleshoot.

the last change I made was to update the URL from https -> http. Upon further inspection, the database that I thought was on the site was empty. :(

**Comment by jhibbets** [comment]
Just got off the phone with support. They found a back-up from Sep 5 they are going to try and restore. no gaurentee's, if it works, we get what we get. Things may be out of place and I'm not sure when the redirects were implemented.

I should have another update within 12-24 hours.

**Comment by FrankCJones** [comment]
I can add this site to the backup system I use for WordPress Management with my clients. The reason I have not done this already is that the system also inserts a footer with a link to my business. If this is acceptable, that will solve the backup problem and we will have daily copies of the site. I could restore the site from that backup if this happens again.

**Comment by dtraleigh** [comment]
Could we not just use a backup plugin that uploads them to our google
drive? Would that fix it? I'm familiar with one that's free, should work
for us I'd think.

**Comment by FrankCJones** [comment]
@dtraleigh There is no issue with using a plugin that uploads the backup to Google Drive. Someone will need to periodically check that this task is completed and the backup files are created. They will also need to monitor the group Google Drive to ensure the files are not deleted as they were from the server, or restore them if they are deleted.

**Comment by jcwlib** [comment]
@FrankCJones - please go ahead and setup your automated backup system on ncopenpass.com -  we discussed it at the meetup last night and it is acceptable to have your business in the footer of the site.
