### ISSUE TITLE
Marketing for GQIS training

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1217]
We could use some help with promoting the QGIS training for Saturday. Perhaps:
 - [x] short blog post with CTA to register using ticket type: Civic Camp - QGIS training only (Saturday) - note seating is capped at 40
- [ ] social media
- [ ] mention in next newsletter

Participants should bring their own laptop.

What other details do you need?

ref: #1158

**Comment by jcwlib** [comment]
right now I have the first mention on social media scheduled for Tuesday (9/18) but we can be flexible based on responses from Jeff
