### ISSUE TITLE
Content Strategy - 7/29

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#122]

**Comment by lenaecb** [comment]
@suzanneccnc @jhibbets - can you guys take a look at the current draft so we can continue filling in the content? Please look at the themes per week starting next week in the Marketing Plan doc (tab: Content / Social Calendar) - https://docs.google.com/spreadsheets/d/1LBTa_evehF0wddkS-OcJx6Ej5hFpp7wHA1Z9p8_bKf8/edit#gid=1074395530

**Comment by suzanneccnc** [comment]
@lenaecb Makes sense. Thanks for thinking this through. What's next for
this?

**Comment by lenaecb** [comment]
@suzanneccnc re: Please look at the themes per week starting next week in the Marketing Plan doc (tab: Content / Social Calendar). We need to solidify those target themes then fill in what content will work to fit that theme and week. @jhibbets would like your eyes on it too

**Comment by suzanneccnc** [comment]
I looked at the themes this morning; like them. Will add thoughts on
content tomorrow.
