### ISSUE TITLE
Write blog post about CfA Hurricane Florence efforts

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1222]
highlight civic tech effort from CfA
- [ ] what was the end result of the shelter resource
- [ ] how did it happen
- [ ] CTA - register for civic camp this week
Wait until Monday to post

**Comment by jcwlib** [comment]
I can schedule on social media for mid-day post - 12:00 pm or 1:00 pm - just let me know

**Comment by jcwlib** [comment]
Posted on website and sent out on social media
