### ISSUE TITLE
Newsletter - 9/18

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1224]
Planning to send out a newsletter on Tuesday - Wednesday at the latest - focusing on Civic Camp registration and detailed schedule

**Comment by jcwlib** [comment]
Decided to send out Wednesday - focusing on the new blog content as well as registration

**Comment by jcwlib** [comment]
test email sent out for review

**Comment by jhibbets** [comment]
Test looks good to me.

**Comment by jcwlib** [comment]
sent
