### ISSUE TITLE
Vendor selection for tshirts - 8/8

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#123]

**Comment by ChrisTheDBA** [comment]
Going with Goldner & Shannon from last year

**Comment by suzanneccnc** [comment]
Thanks for jumping in. Where are you in working with them? Contract?
Quantity? Sizes? Color? Do they have logo artwork from before? At this
point, what else can I help with here?
Best regards,
Suzanne

**Comment by ChrisTheDBA** [comment]
Getting the details now.

**Comment by lenaecb** [comment]
awesome, thanks @ChrisTheDBA. @suzanneccnc can you take the lead for all marketing collateral things? I believe we have a ticket on our waffle board for all those need but just in case here's a quick hit list (our in our [mktg plan doc](https://docs.google.com/spreadsheets/d/1LBTa_evehF0wddkS-OcJx6Ej5hFpp7wHA1Z9p8_bKf8/edit#gid=1760850001)) - 
- Parking signs/directionals (outside)
- Directional signs (interior)
- Welcome sign w/ sponsor names 
- 8.5x14 posters 
- 9x5 postcards
- CityCampNC stickers
- CityCampNC cups

All these items will need to be discussed with @ChrisTheDBA and @jhibbets based on budget but we should try and get a jump on them

**Comment by ChrisTheDBA** [comment]
Looking at last year's invoices it appears that Goldner has our artwork and die so that should save us some hassle.  We still have a pile of stickers from last year so that will save too.

I am working the details on the Google Fiber donation. If that comes in we should be in high cotton as far a budget goes.

**Comment by lenaecb** [comment]
@suzanneccnc - I've assigned this card to you. Can you help with organizing the vendor info here with @ChrisTheDBA ?

**Comment by TaxLadyTracy** [comment]
Lenae and Suzanne can you email me at tracy.mathews1125@gmail.com please so I can have your email in my list :)
I need to know if you would be opposed to a unisex shirt vs a womans cut shirt.  Thanks!

**Comment by TaxLadyTracy** [comment]
Goldner & Assoc quote info for Bella+Canvas shirts
Men’s
XS-XL $8.35
XXL $10.85
Woman’s
S-XL $7.15
XXL $10.05

**Comment by ChrisTheDBA** [comment]
Local vendor Action Graphics %7/shirt

Proof pic on Google Drive

**Comment by lenaecb** [comment]
Just followed up with an email to you @TaxLadyTracy

**Comment by suzanneccnc** [comment]
@ChrisTheDBA @lenaecb OK. OK. Please let me know where we are for t-shirts. Here's what I think I understand: vendor: Goldner & Assoc; we have quote from them, but not sure of details (are those prices based on minimum quantity). NEED HELP WITH FOLLOWING: quantity of t-shirts (by size, at least some advice based on past of how many of each size - like by %), color of t-shirt, contact info for Goldner.

**Comment by suzanneccnc** [comment]
@ChrisTheDBA @lenaecb Yes, I can take lead on collatoral items listed. @ChrisTheDBA Can you advise on quantity of stickers we have vs. how many were ordered last year? Also, did we use any particular vendor for printing? Cheers!
