### ISSUE TITLE
Update ATO team registration form

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1231]

**Comment by zachambrose** [comment]
@jhibbets The form is in the open data folder. We need to update (or remove) the day and time for the pitches at ATO. Hopefully we can confirm a time and include it in the form.

**Comment by jhibbets** [comment]
Yep, we've got a room for you, no problem.  So you need the session to start at 12:30 and end at 1:30 on Monday the 22nd?  

Also, is the description pretty much the same as in 2017?  Please forward the description you'd like us to use and we'll get it posted ASAP. 

Thanks!  And apologies again for the delay!

**Comment by jhibbets** [comment]
https://docs.google.com/forms/d/1TpeHpnQEVUiqTqmDho4zeqXY4DnCTPSQV241MGIBGHQ/edit
