### ISSUE TITLE
Draft follow-up message for Civic Camp attendees

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1235]

**Comment by jcwlib** [comment]
@jhibbets - ready for review - at the end of this document 

https://docs.google.com/document/d/1phdCsVeuEVIm8OFRo5SuPmvFYN0uSwbBVujNxKe1WGU/edit

**Comment by jhibbets** [comment]
Looks good!

**Comment by jcwlib** [comment]
message scheduled in MailChimp - still need to reconcile paper registration list with electronic before closing this ticket
