### ISSUE TITLE
Organizer page

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1246]
Jennifer - why aren't you on the organizers page?

**Comment by jtawes** [comment]
I have another waffle ticket related (#1161), there are multiple people to add and I sent out emails twice asking for information from each person (title,organization,photo that they wanted included). I was waiting for a response so I could put everyone on there but I haven't heard back from anyone. I just forgot about myself while waiting I guess :)

**Comment by jtawes** [comment]
Done
