### ISSUE TITLE
Add speaker: Eric Marsh

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1247]
Can we add:

Eric Marsh, Strategic Initiative Analyst at Durham County, to the Innovate Durham lightning talk

 - [x] speaker page
 - [x] schedule page
 - [x] social media guide (if on social media)

I'm busy pulling all the presentations together ^jh

**Comment by jhibbets** [comment]
Twitter is: @TheMarshMethod

**Comment by jtawes** [comment]
Does he have a title for his talk or a description? I have his bio

**Comment by jcwlib** [comment]
I believe he is speaking with Ben in the Innovate Durham Lightning talk. So
whatever you have for Ben - you can put with Eric

**Comment by jtawes** [comment]
Done!

**Comment by jhibbets** [comment]
Thanks. that's correct, he is co-presenting with Ben. Sorry for not
including that detail, I copied it from an email.
