### ISSUE TITLE
CityCamp 2016 Announcement Graphic(s) - 8/1

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#125]

**Comment by lenaecb** [comment]
Sent email to Carsi 8/1 (helped with design last year) - ctong3@ncsu.edu

**Comment by lenaecb** [comment]
Reached out to Carsi to help create a simple promotion banner

**Comment by suzanneccnc** [comment]
@ChrisTheDBA @lenaecb Is Carsi doing the banners, posters, postcards? Let me know where to jump in here.

**Comment by lenaecb** [comment]
@suzanneccnc see note above from yesterday - I am in contact with her. Right now she is working on a 2016 banner image for us. When we're ready for posters and such we should reach out but I think we need to get all those ducks in a row so it's not all one off requests.

**Comment by suzanneccnc** [comment]
Agreed.
