### ISSUE TITLE
Create digital grid and publish blog post

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1253]

**Comment by jhibbets** [comment]
We borked the mobile version, waiting to update that.

**Comment by jhibbets** [comment]
@jcwlib

1) can you switch:

Using Data to Convince People to Attend Public Schools  / Open Data for Advocacy

Greg Herschlag / Doug Johnston at 3pm

with

Organizing Volunteer coding during emergencies

Phillip Lamb at 4pm

so that  Organizing Volunteer coding during emergencies is at 3pm and Using Data to Convince People to Attend Public Schools  / Open Data for Advocacy
 is at 4pm.

2) remove Wakes Transparency Portal Chris Mathews from the board

3) Replace item 2 above with Let’s start a data science writing group within the brigades

Chris Mathews from 3pm

So move Let’s start a data science writing group within the brigades from 3pm in Brunswick to 4pm Carteret

**Comment by jcwlib** [comment]
All set!
