### ISSUE TITLE
Draft September Newsletter

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1256]
- [x] recap of Civic Camp
 - [x] data survey promotion
 - [x] promote meetups on Oct 2 & Oct 9
 - [x]  ATO teams signup
 - [x] what we're reading

**Comment by jhibbets** [comment]
Discount code for ATO is 

Regarding a discount for Civic Camp attendees/your list, sure, we're happy to.  Pass along CivicCamp20, which is good for 20% off.

**Comment by jcwlib** [comment]
test email sent out

**Comment by jcwlib** [comment]
newsletter sent
