### ISSUE TITLE
Draft event survey - Civic Camp

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1261]

**Comment by jcwlib** [comment]
survey is drafted 

The plan is to send the survey to everyone who registered and have the first question ask if they attended the event or not. 

If yes, there are questions about the event and suggestions for the future. 

If no, we ask why not and also some questions about the future. 

For everyone that provides feedback, they will be entered in a drawing for a free DataPalooza registration.

**Comment by jcwlib** [comment]
survey link included in post-event message to attendees
