### ISSUE TITLE
Send DataPalooza summary to ATO organizers

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1263]
"Also, is the description pretty much the same as in 2017?  Please forward the description you'd like us to use and we'll get it posted ASAP. "

Maybe we add in the description the submission form to try and get a few new teams and ask Todd to include the call for teams in a newsletter they send out

https://docs.google.com/forms/d/1TpeHpnQEVUiqTqmDho4zeqXY4DnCTPSQV241MGIBGHQ/edit

**Comment by jcwlib** [comment]
NC Open Pass Datapalooza is an open data competition created in the Triangle to catalyze positive community and economic impact. The annual competition draws together local creators, designers, and developers to build teams to leverage open data strategies to create innovative and sustainable means of improving the local community and economy.
 
NC Open Pass is partnering with All Things Open again this year to host our pitch competition. Teams will pitch their open data concepts to a panel of judges in the hopes of being selected for three finalist spots for the DataPalooza finale on November 8, 2018. 

For more information on this year's DataPalooza event visit http://ncopenpass.com/datapalooza/

**Comment by zachambrose** [comment]
Done.
