### ISSUE TITLE
Need an link that goes straight to the Lightning Talk speakers

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1265]
@jtawes - I tried to figure it out, but I couldn't =( 

Can you make an anchor link to the Lightning Talk header on the speaker page?

**Comment by jtawes** [comment]
I've made the css id for the speakers page at the Lightning Talks header, where do you need the link?

**Comment by jcwlib** [comment]
In a blog post I have drafted in the Marketing folder/ Blog Posts.

It is called Civic Camp Recap and there is a paragraph on Friday evening.

**Comment by jtawes** [comment]
Done
