### ISSUE TITLE
Make booth schedule for ATO

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1267]

**Comment by jcwlib** [comment]
draft posted here - https://docs.google.com/spreadsheets/d/1Kpc7jty0PMiu8QsM9KRiorP2jy9WCfn13f1_Lj4eeSU/edit?usp=sharing

**Comment by ChrisTheDBA** [comment]
On Sunday Brigade Congress doesn't end until noon so we won't be back
earlier than 5 PM
Chris Mathews

**Comment by jcwlib** [comment]
Okay- we can only setup until 6:00 pm that day.  Let me know if it makes
sense for us to meet up before you leave for Charlotte or just aim to meet
up between 5 and 6:00 pm.
