### ISSUE TITLE
Press Release #1 Announce CC 2016 - 8/9

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#127]

**Comment by lenaecb** [comment]
Link to 2015 PR - https://docs.google.com/document/d/1x6EWGfpwDFvD7-tJRoxh06y8G0mcM8gaVBiOdS2UPKA/edit

**Comment by lenaecb** [comment]
New 2016 PR release ready for review @jhibbets @ChrisTheDBA . It needs a little input from you guys because there is some info I don't know. Find the link here: https://docs.google.com/document/d/1zrfArCBsMIr0nrbXaWeL10ZeP4JgyTMf0K0v3OupFWE/edit?usp=sharing

**Comment by ChrisTheDBA** [comment]
I've added my notes

**Comment by lenaecb** [comment]
Live PR post - http://citycampnc.org/2016/08/20/sixth-annual-civic-technology-unconference/
