### ISSUE TITLE
Send WRAL techwire article

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1275]

**Comment by jhibbets** [comment]
Sent: https://docs.google.com/document/d/187X0k753CS042U-sFkoBYYXbUvuosmdkxV7Q_6erjXs/edit#

**Comment by ChrisTheDBA** [comment]
Typo in Jennifer's name.
Chris Mathews

**Comment by jhibbets** [comment]
Thanks for catching that, updated in our blog past just now.

**Comment by ChrisTheDBA** [comment]
post, not past :) got ya
Chris Mathews

**Comment by jcwlib** [comment]
Made some minor tweaks in the Google Doc and the published post on the
website

**Comment by jhibbets** [comment]
Thank you.
