### ISSUE TITLE
Add DataPalooza registration link

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1277]
Here is the link for DataPalooza reg, can we add this to the homepage and DataPalooza pages?

https://www.eventbrite.com/e/nc-open-pass-datapalooza-tickets-50593487483

**Comment by jtawes** [comment]
I have added the links on the home page to register and a link to the DataPalooza home page. 

I am working on creating the new pages for DataPalooza with the same format used for Civic Camp. As soon as they are up, I will add links on the home page as well.

I temporarily left the Civic Camp links on the homepage beneath the DataPalooza information (I deleted the "Register" button). Do you want me to leave this up for now or go ahead and delete this from the home page?

**Comment by jhibbets** [comment]
Thanks. I think we should leave Civic Camp stuff up for about a week, then
maybe move what we have on the homepage to the Civic Camp landing page.

**Comment by jhibbets** [comment]
We can close this if you think we're done with this card.
