### ISSUE TITLE
Create meetup for October 9

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1282]
just capturing details on the meetup we "announced" at the end of Civic Camp

 - [x] Draft MeetUp post
 - [x] Confirm Annex availability
 - [x] Announce MeetUp
 - [x] Invite existing team members to sign-up, ask for a team name, description, and needs in to be added to MeetUp comments section

**Comment by jhibbets** [comment]
Draft is here - I plan to announce in the morning after I confirm Annex availability.

https://www.meetup.com/Triangle-Code-for-America/events/255015049/?isFirstPublish=true

**Comment by jhibbets** [comment]
Just need to complete the Red Hat Event form to confirm booking.
