### ISSUE TITLE
Scan in W-9's

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1284]
And change permissions on the folder you upload them to to private -- it's open by default.

**Comment by ChrisTheDBA** [comment]
Why do they need to scanned in and uploaded? We have done it in the past
because we e-mail them to our fiscal sponsors. Is there someone other
than Tracy that needs to see them. if there is, that's fine but I am not
aware who that is.

Chris Mathews

**Comment by jhibbets** [comment]
I thought we uploaded them for documentation purposes.

**Comment by ChrisTheDBA** [comment]
In the three years I've done it. We only scanned them in to email them to
CFA. Once CFA tells me they are good, I delete/destroy them.

Chris Mathews

**Comment by zachambrose** [comment]
+1

**Comment by jhibbets** [comment]
that's fine, I just thought it was part of our process and that we were
keeping them for records/tax purposes.
