### ISSUE TITLE
Write a hackathon schedule blog post

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1286]
Oct 2 - meet-up (Durham)
Oct 9 - meet-up (Raleigh)
Oct 22 -ATO
Oct 30 - meet-up ?
Nov 8 - DataPalooza

**Comment by jhibbets** [comment]
Draft is read for review. I think we should try to publish and promote on Thursday (Sep 27)

@zachambrose @jcwlib - please review and make any edits

**Comment by jcwlib** [comment]
@jhibbets - edits made and I put the blog post back into a draft mode.  Somehow it was published (perhaps by me - sorry)

FYI - FirstNet is not an open source platform.  I like the reference to our partner, but it is a little misleading that a team could win with a project built on FirstNet.  

Also, there is another cash prize from Innovate Raleigh in the pipeline.  Do we need to promote that opportunity?

@jtawes - the hyperlinks are really lost (especially in the opening paragraphs) and not easy to see unless you know where to mouse over.  Any way to help with that styling?

**Comment by jtawes** [comment]
I can change the color of the hyperlinks, just let me know when you are
done editing Janel and I'll update the draft.

**Comment by ChrisTheDBA** [comment]
IR has agreed to fund an additional prize for FirstNet. But to date,
Brigette has not sent the check.

Chris Mathews

**Comment by jcwlib** [comment]
Good to know. I just sent Bridget a reminder regarding the prize money

**Comment by jtawes** [comment]
Bolded and underlined the hyperlinks and they also highlight in green on hover. Saved as draft. Let me know if you need anything else done.

**Comment by jcwlib** [comment]
Just looking through the partners perks document
<https://docs.google.com/document/d/1VNDutMmhA52SeakzTaMPriV7SJaA1ry5UCLGPaXohx4/edit?usp=sharing>-
WeWork is donating two 3 months memberships as prizes. We should probably
add that to the blog post.

**Comment by jhibbets** [comment]
Just to clarify, the intention of this blog post it to outline the
timeline. We should do another post next week announcing the competition,
prizes, and how to submit the teams. I'll publish this in the morning and
then add a comment to the ATO meet-up that Chris and I were at tonight.

**Comment by jhibbets** [comment]
Thanks for all the edits, style updates, etc. I really appreciate it. I've scheduled the post to go live at 6:00.

**Comment by jcwlib** [comment]
scheduled on social media for posting at noon today
