### ISSUE TITLE
Fold in Ipreo to Sponsor list

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#1287]
In exchange for the space for DP, what level does it get them at? I will get a logo and put it on the drive.

**Comment by ChrisTheDBA** [comment]
I would say Gold($2500).

Most spaces in DT Raleigh are at least $2000. We got off cheap with
ArtSpace because I asked and asked.
Chris Mathews

**Comment by ChrisTheDBA** [comment]
Question:

Will having the vendors with display tables be an issue? Is there room?

When Preet from WeWork picked up her stuff on Saturday, she said she'd see
us at DataPalooza. I guess that means they will have their marketing there.

Chris Mathews

**Comment by jcwlib** [comment]
We can probably make it work.  We are planning to use the lobby area right
outside of the conference room and training room.

**Comment by dtraleigh** [comment]
Yes, it should work. I'm thinking vendors set up in the back of the big
room should work.

**Comment by dtraleigh** [comment]
Ipreo logo is in the Sponsorships -> Sponsor Logos folder.

**Comment by jtawes** [comment]
Added IPREO to gallery on homepage and to Partner's page. I'll update the Partners Poster but wait to finalize before printing.

**Comment by jcwlib** [comment]
I believe the outstanding items on this ticket is covered by #1300. @dtraleigh - do you agree?

**Comment by dtraleigh** [comment]
I think we would need them online and that should cover it.

http://ncopenpass.com/civic-camp/civic-camp-partners/

**Comment by jcwlib** [comment]
Leo -

They are listed here actually -> http://ncopenpass.com/about/partners/

This URL is specific to Civic Camp
http://ncopenpass.com/civic-camp/civic-camp-partners/

**Comment by dtraleigh** [comment]
ahh cool. Then good there.
