### ISSUE TITLE
Add WRAL Techwire as media sponsor

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1293]
- [x] Add to sponsor sheet
 - [x] Add to DataPalooza sponsor sheet - contact is James Amato <jamato@wral.com>
 - [x] Add to overall sponsors
 - [x] Add to DataPalooza sponsor board

**Comment by jtawes** [comment]
Add Techwire under the "Community Sponsor" or make a new heading of "Media
Sponsor"?

**Comment by jhibbets** [comment]
Let's keep it simple and use community sponsor. Logo was just uploaded to
the google Drive folder.

**Comment by jtawes** [comment]
TechWire added to homepage and partners page, will add to DataPalooza pages as completed.

**Comment by zachambrose** [comment]
Added to the sponsor worksheet.
