### ISSUE TITLE
Update NC Open Events

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#1295]
Add the following two MeetUps:

Code for Durham MeetUp Oct 2
 https://www.meetup.com/Triangle-Code-for-America/events/jrhtlpyxnbdb/

NC Open Pass MeetUp Oct 9
 https://www.meetup.com/Triangle-Code-for-America/events/255015049/

**Comment by jtawes** [comment]
Done, check it out and let me know if you would like any changes...if none, then ticket can be closed :)

**Comment by jhibbets** [comment]
Looks great @jtawes, my only feedback is that they should be in chronological order

**Comment by jtawes** [comment]
Done
