### ISSUE TITLE
Update Partners Poster - Due 10/10

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1300]
- [x] add Ipreo (gold level)
 - [x] add WRAL TechWire (community partner)
 - [x] remove event specific branding and year
 - [x] just have NC Open Pass branding and twitter handle at the bottom

**Comment by jtawes** [comment]
Uploaded to shared drive https://drive.google.com/open?id=1VT-od_edZjSkAJ1p8_qFfpllNiKGBY8Y

**Comment by jcwlib** [comment]
@jtawes - there is still Civic Camp branding at the bottom

**Comment by jtawes** [comment]
Sorry, updated https://drive.google.com/open?id=1rrhs5juHvnLS8V6Z_s1JTjzc7jNOEnbL
deleted the incorrect one.

**Comment by jcwlib** [comment]
Need to adjust HQ Raleigh's level and then ready for printing

**Comment by jcwlib** [comment]
https://drive.google.com/open?id=1yP_SZWIsvVy0i8UXduXKqYB_-WjZk4uB
