### ISSUE TITLE
DataPalooza: Printing Needs

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1305]
- [ ] A Frames to direct attendees to elevators
- [ ] General Welcome Signs
- [ ] Updated Partner poster

needs #1300
needs #1304
needs #1306

**Comment by jcwlib** [comment]
Link to A Frame graphic - https://drive.google.com/open?id=1gHzz1bsY2Q2SnCJJiH8WGt_fKWOXbSqG  - @jtawes please confirm

**Comment by ChrisTheDBA** [comment]
The file you linked has CivicCamp on it.

Chris Mathews

**Comment by jcwlib** [comment]
Sure does - Let me double check
