### ISSUE TITLE
Create Generic NC Open Pass A-Frame Graphics - Due 10/10

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1306]
Need to take the existing Civic Camp A-Frames and just have them be generic NC Open Pass branding

**Comment by jtawes** [comment]
24 by 36 Generic NC Open Pass uploaded https://drive.google.com/open?id=192kIKRYnmPZ7y0ToO8FETzahUtsqi6Ic

**Comment by jcwlib** [comment]
ready for printing
