### ISSUE TITLE
Set up DataPalooza run of show

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1312]

**Comment by zachambrose** [comment]
I put a draft in the Logistics folder. Can you guys see what you think? Any ideas on ways to tighten it up? 

https://docs.google.com/document/d/1uzgcBSzyboBrwzCfpI2qaFS3Hu4eJbr-HA5XsUGEDA0/edit?usp=sharing

**Comment by jcwlib** [comment]
Looks good to me - I made a few minor tweaks and we are missing the 2017 winner

**Comment by dtraleigh** [comment]
Added the guest Wifi info. (no password, you have to accept the Terms in a
browser)

If you want me, or someone, to do a welcome, then I can cover logistics.
Should be short and sweet.

**Comment by zachambrose** [comment]
That sounds great. Feel free to add any specifics that you want, @dtraleigh .
