### ISSUE TITLE
Add DataPalooza Schedule to website

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1315]

**Comment by jtawes** [comment]
Where can I find the schedule?

**Comment by jcwlib** [comment]
https://docs.google.com/document/d/1uzgcBSzyboBrwzCfpI2qaFS3Hu4eJbr-HA5XsUGEDA0/edit?usp=sharing - just the schedule part =)

**Comment by jtawes** [comment]
Done

**Comment by jcwlib** [comment]
Looks good!
