### ISSUE TITLE
Email people about recruiting teams

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1328]
Ryan Nilsen, Ryan Thornburg, Tony Kershaw, Raj Narajan, HQ, AU, Nest, Bullpen

**Comment by zachambrose** [comment]
Did Ryan Nilsen, Ryan Thornburg, Tony Kershaw, Raj Narajan, HQ, AU, Nest, Bullpen

**Comment by jhibbets** [comment]
NCRioT (Tom), Innovate Durham, Jim Scarbarough, Derrick Minor

**Comment by zachambrose** [comment]
Leo did Loading Dock

**Comment by jhibbets** [comment]
Reached out to a contact at WakeTech
