### ISSUE TITLE
Sponsor logos due for art/website/signage/etc

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#135]

**Comment by suzanneccnc** [comment]
@ChrisTheDBA @lenaecb Where do sponsor logo's need to appear? On postcards? On t-shirts (I hope note)? on banners/signs? on posters? Let me know where to jump in?

**Comment by ChrisTheDBA** [comment]
Most are in the sponsors folder on Google drive

**Comment by lenaecb** [comment]
@ChrisTheDBA @suzanneccnc  - are we good to push the poster designs for sponsors over to Carsi?

**Comment by lenaecb** [comment]
signage design requests are with Carsi

**Comment by lenaecb** [comment]
We've got the specs for the prints. @ChrisTheDBA will you be getting these printed?
