### ISSUE TITLE
Update Open Page links

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1363]
Durham County -- https://durhamnc.gov/1487/Open-Government
Chapel Hill - https://www.chapelhillopendata.org/page/home1/
Greensboro - https://data.greensboro-nc.gov/
Mecklenburg County - http://maps.co.mecklenburg.nc.us/openmapping/
Cary - https://data.townofcary.org/pages/homepage/
Asheville - https://data.ashevillenc.gov/
Remove NGA Ebola Support - requires a login
Remove Bill and Melinda Gates Vaccine Tracking System - requires a login
ARCGIS Open Data Gallery - link doesn't work
Department of Education - link doesn't work

**Comment by jtawes** [comment]
Updates done
