### ISSUE TITLE
Create Finale slide deck

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#1369]

**Comment by zachambrose** [comment]
Deck is in the presentation folder. Please feel free to make any edits or let me know if you see any changes that need to be made.

**Comment by jcwlib** [comment]
I made some minor tweaks - saved in a Google Sheets format in the same
folder.

FYI - Isn't HQ Raleigh supposed to be a GOLD partner not Platnium? Slides
show them at the Platinum level.

**Comment by zachambrose** [comment]
Done. Thx @jcwlib !
