### ISSUE TITLE
Pull out DataPalooza Survey results

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1375]

**Comment by jhibbets** [comment]
FYI - survey looks good!

**Comment by jcwlib** [comment]
Full results are saved to Google Drive as well. Pulled out responses from open-ended questions and highlights of the other questions
https://docs.google.com/document/d/1exjBroziY6AuyHG3o1DH00Od3Hsx3U1DgJkCpLaO62A/edit?usp=sharing
