### ISSUE TITLE
Need a additional logo to share with partners

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1384]
Need to create a logo file for us to send to partners.

The main NC Open Pass logo with a smaller script of "brought to you by Open Raleigh Brigade"

**Comment by jhibbets** [comment]
If we need to shorten it, we could use:

By Open Raleigh Brigade

**Comment by jtawes** [comment]
Something like this? :
![NCOPLogo-01.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6b412c71616500119ddf73/125516c66e82c728ace21e0d46c6b7b513ae8cae80a4ef12e611b2843b492d762a10e17132d0b52cba112a515e5c4ba841595810a9f98b7af7bf3b79dc4e17ff933c0120996048e6edc00db513bb27814e80b2ba894ac6ef3d20e58b8f5d73.png)

**Comment by jhibbets** [comment]
I like it!

**Comment by jtawes** [comment]
Placed in shared drive: https://drive.google.com/open?id=198TGyi64TTrSPWIiNJLgX7EzudX6PMIW
