### ISSUE TITLE
Find speaker for Open Data 101 session

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1394]
--reach out to Bonnie, Bill S, someone at Wake County, Durham County

--could be introduction to city/county data

**Comment by ChrisTheDBA** [comment]
ASked Anise Vance - Durham.

**Comment by ChrisTheDBA** [comment]
Anise prefers focusing on the keynote. Let's think of another person to give the OpenData 101 talk/workshop.

**Comment by ChrisTheDBA** [comment]
Not done yet.
