### ISSUE TITLE
Call for Volunteers

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#140]

**Comment by ChrisTheDBA** [comment]
i will get you Dana calder from IronYard email for possible volunteers

**Comment by lenaecb** [comment]
@dtraleigh - do you want me to do some social media posting about this and a potential blog post? Let me know what I can help with!

**Comment by dtraleigh** [comment]
Sure go ahead! Volunteers are definitely needed and I can coordinate.

**Comment by lenaecb** [comment]
Ok, cool. In the past, have y'all posted some blog content? And who has been the point of contact for those that want to signup - you @dtraleigh ?

**Comment by dtraleigh** [comment]
Blog post and facebook group posts usually produces a few volunteers. I
think if you post it in the meetup group also, a few people might see.

We don't need volunteers throughout the entire event. The most need is for
Friday morning and Saturday evening, after the event. I can be the contact
for that and ask folks when they want to help.

**Comment by aikimark** [comment]
I've got my Thu evening and all day Fri blocked off for this.  Not sure about my Saturday availability.  When do you want me to show up on Thursday and Friday?

**Comment by dtraleigh** [comment]
Thursday 1-4pm is when we need the most help to get the place ready. We are
planning to have it good to go then. AFTER the event is over Thursday
night, we need help moving things around so if you can stay afterwards, we
could use the help.

Friday morning will depend on how productive we are Thursday night.

**Comment by aikimark** [comment]
I now have 1-9:30 blocked off on my Thu calendar.  Do you have any free parking spaces for the volunteers?

**Comment by dtraleigh** [comment]
No. No set aside parking for the event.

**Comment by lenaecb** [comment]
@dtraleigh - this a good blog post for Call for Volunteers? It's live. http://citycampnc.org/2016/09/19/call-for-volunteers-help-make-citycamp-a-success/

**Comment by ChrisTheDBA** [comment]
I fixed a spelling mistake…also all the sessions will be in one room(sectioned
off) and there is no a/v setup
Chris Mathews

On Mon, Sep 19, 2016 8:11 PM, lenaecb notifications@github.com
wrote:
@dtraleigh  - this a good blog post for Call for Volunteers? It's live. 
http://citycampnc.org/2016/09/19/call-for-volunteers-help-make-citycamp-a-success/
