### ISSUE TITLE
Send out interest form to organizers

### ISSUE THREAD

**Issue by jcwlib** [ncopenpass/NCOpenPass#1417]
-[ ] meetup attendees
-[ ] potential organizers who did not attend
-[ ] current organizers from past years

**Comment by zachambrose** [comment]
I emailed to the potential organizers.

**Comment by zachambrose** [comment]
And asked last year's organizers to update their contact info. @jhibbets messaged on the meetup page.

**Comment by zachambrose** [comment]
Actually the email to last year's organizers will go out tomorrow
