### ISSUE TITLE
Order tshirts - 9/2

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#143]

**Comment by ChrisTheDBA** [comment]
Shirts are ordered. On our way to pay today.

**Comment by suzanneccnc** [comment]
What colors?

**Comment by ChrisTheDBA** [comment]
Sent out a link 4 days ago. Picture on Google Drive

**Comment by ChrisTheDBA** [comment]
Order placed w/ Action Graphics - 175 various sizes mens/womens White on heather navy and 16 navy on light gold for organizers. This was 350-400 less than Goldner for the same shirt.

**Comment by lenaecb** [comment]
@ChrisTheDBA - what was the total cost? And when should we expect them to arrive?
