### ISSUE TITLE
Finalize catering number

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#147]

**Comment by ChrisTheDBA** [comment]
22 pizzas Thursday, breakfast and lunch ordered for both days

**Comment by lenaecb** [comment]
@ChrisTheDBA - is the pizza from Donato's again?

**Comment by ChrisTheDBA** [comment]
Yes Donato's Seaboard Station
Chris Mathews

On Tue, Sep 20, 2016 6:17 PM, lenaecb notifications@github.com
wrote:
@ChrisTheDBA  - is the pizza from Donato's again?

**Comment by lenaecb** [comment]
Awesome, and breakfast for Friday and Sat is from where?

**Comment by ChrisTheDBA** [comment]
Ian Henshaw has the info, let me ask.
Chris Mathews

On Tue, Sep 20, 2016 6:27 PM, lenaecb notifications@github.com
wrote:
Awesome, and breakfast for Friday and Sat is from where?

**Comment by ChrisTheDBA** [comment]
New York Bagel and Deli III - Cary NC
Chris Mathews

On Tue, Sep 20, 2016 6:31 PM, Chris Mathews christhedba@gmail.com
wrote:
Ian Henshaw has the info, let me ask.
Chris Mathews

On Tue, Sep 20, 2016 6:27 PM, lenaecb notifications@github.com
wrote:
Awesome, and breakfast for Friday and Sat is from where?
