### ISSUE TITLE
Speaker gifts (specifically keynote)

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#152]

**Comment by dtraleigh** [comment]
Ahh yes. I did these last year and it definitely helps to knock this out in
advance if possible.

**Comment by dtraleigh** [comment]
I'm wondering if this has any work on it. I felt like this was tough to put together last minute. (as I did last year)

**Comment by lenaecb** [comment]
I agree. Not that I have experience with it at CCNC I know from other events that this is always a big thing that gets pushed off. I think we should start the gift idea and ordering asap

**Comment by suzanneccnc** [comment]
@dtraleigh Did you have any luck getting in-kind donations? thinking about Videri and CounterCulture who are sponsors for Creative Mornings...

**Comment by suzanneccnc** [comment]
Oh, @dtraleigh did you get any feedback from the speakers? What were the gifts last year; "local" is what I heard...

**Comment by dtraleigh** [comment]
Sorry. I haven't been working on this one and wasn't aware that I had an
action here.

What feedback do we need?

Last year, nothing in the gift bags were donated as I just scrambled to put
them together. Asking for a donation takes longer so we could start doing
that now.

The gift bags last year, IIRC, had some gift cards, Starbucks, iTunes,
Larry's beans coffee, and videri chocolate. For the keynote, I added a few
local items of interest from Deco Raleigh. We spent about $800 on all of it.

**Comment by jhibbets** [comment]
Leo, On our planning call last might we just wanted to know what was in
the gift bag, so no further action is needed. Suzanne is working on
this. Let's see if we can keep this to $500.

Jason

**Comment by dtraleigh** [comment]
Perfect.

**Comment by ChrisTheDBA** [comment]
Leo,
Do you remember how many SWAG bags you did?
Chris Mathews

On Tue, Aug 30, 2016 9:22 AM, Leo Suarez notifications@github.com wrote:
Sorry. I haven't been working on this one and wasn't aware that I had an
action here.

What feedback do we need?

Last year, nothing in the gift bags were donated as I just scrambled to put
them together. Asking for a donation takes longer so we could start doing
that now.

The gift bags last year, IIRC, had some gift cards, Starbucks, iTunes,
Larry's beans coffee, and videri chocolate. For the keynote, I added a few
local items of interest from Deco Raleigh. We spent about $800 on all of it.

**Comment by dtraleigh** [comment]
I made 20 (I think) bags, one for each lightning talk speaker, panelist,
keynote, and moderator.

**Comment by ChrisTheDBA** [comment]
I think $800 is doable. Bonus points for coming in less and extra awarded for
getting in-kind. Any businesses right in the vicinity of Nash Hall that would be
good candidates.
Jen pahlka is a special case 1) not local 2) Key note
Chris Mathews

On Tue, Aug 30, 2016 9:32 AM, Leo Suarez notifications@github.com wrote:
I made 20 (I think) bags, one for each lightning talk speaker, panelist,
keynote, and moderator.

**Comment by jhibbets** [comment]
FYI - we have 21 speakers in total: http://citycampnc.org/speakers/

**Comment by suzanneccnc** [comment]
Great! Thanks for the headcount.

**Comment by TaxLadyTracy** [comment]
Suzanne are you going to have these ready to go or do I need to get gift
bags and such?  Also can you share what will be in the bags.  Thanks!

**Comment by jhibbets** [comment]
I forgot to mention this earlier. It be awesome if we had a hand-written
thank you card that we could include and the planning committee could sign.
I'd like to deliver that on-site as opposed to mailing it after the fact.

**Comment by ChrisTheDBA** [comment]
last year we did a combo of on-site and after the fact, in person follow-up. got to work that relationship! :)

**Comment by TaxLadyTracy** [comment]
Ok assign me to do.the notes and I will get everyone to sign the cards like
I did last year.  Thanks for the reminder about that Jason.

**Comment by suzanneccnc** [comment]
I just got back in town and will plan to work on it through this weekend.
That ok with everyone?
Best regards,
Suzanne

**Comment by jhibbets** [comment]
I just don't want to collect mailing addresses,that's all. I will
follow-up with speakers to thank them again after the event.

**Comment by TaxLadyTracy** [comment]
Let me know by the weekend where we stand I will be doing shopping and need
to know about the gift bags.

**Comment by suzanneccnc** [comment]
I've got the gift bags covered. I will complete this weekend.

**Comment by TaxLadyTracy** [comment]
Awesome thanks !

**Comment by ChrisTheDBA** [comment]
Sounds good!
Chris Mathews

On Thu, Sep 15, 2016 7:43 AM, TaxLadyTracy notifications@github.com
wrote:
Awesome thanks !

**Comment by suzanneccnc** [comment]
HeyThere! Here is the final selection for speaker gifts. Please weigh-in as soon as possible:
1. Do we want all speaker gifts to be the same, or can keynote speaker gifts be somewhat bigger?
2. All suggestions are locally sourced and most are from local artists/businesses.
3. Please review speadsheet which has details and several proposals to consider: https://docs.google.com/spreadsheets/d/1Vtach1tK1ai4CuBoxJhVdBoigLk0zi6TY9L3y1rmSNY/edit?usp=sharing
4. Collage of images of gift concepts: https://drive.google.com/file/d/0B-aCFOXBPGwgZm1iUFZUVHRxbFE/view?usp=sharing
5. Prices do not include any tax and whatever is spent on wrapping (which won't be much and will be simple.)
6. If there is universal mutinous resistence to all gift concepts, then I will put together chocolate/coffee/etc. bags...

**Comment by TaxLadyTracy** [comment]
All should be the same and the keynote have a little extra.  Gift bags can
be from dollar tree

**Comment by jhibbets** [comment]
Proposal 1 looks good to me. Thanks for looking into all those and doing
research. I'd like to get a little something extra for Jen since she is
coming so far. Maybe we add one more item just for her.

Jason

**Comment by lenaecb** [comment]
Same as @jhibbets note above. Looks great!

**Comment by suzanneccnc** [comment]
How about a swap out Jen's chocolate bar for a small box of Videri truffles? Does that fulfill your thoughts about something a little extra for her?

**Comment by jhibbets** [comment]
In addition to sounds great :)

**Comment by suzanneccnc** [comment]
picking up copies of Savor the South books on Wednesday; So&So Books giving us a 20% discount.

**Comment by suzanneccnc** [comment]
gifts purchased, wrapped and ready for delivery.

**Comment by jhibbets** [comment]
Thanks!
