### ISSUE TITLE
Update media page (website) when ready

### ISSUE THREAD

**Issue by lenaecb** [ncopenpass/NCOpenPass#153]

**Comment by ashumz** [comment]
@jhibbets is this something we still need to do or can we close this out?

**Comment by jhibbets** [comment]
If we have new media then yes. We'd have to look-up if we have any new
press hits / articles.

**Comment by jhibbets** [comment]
@ashumz - listing of media/press is in the prospectus! https://docs.google.com/document/d/1nlYCbqcFvOdUrMnRirAHPbZxtnf8j0XW8ybKbdnmsMk/edit#
