### ISSUE TITLE
parking, directional signs (outside)

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#160]

**Comment by TaxLadyTracy** [comment]
I will see what we have from last year to help cut down on cost.

**Comment by ChrisTheDBA** [comment]
With it being downtown. I don't see us being able to post signs. We'll try to get a banner for the raling /fence in front of the building and a tent sign too.

**Comment by suzanneccnc** [comment]
We could use yard sign, like political signs. Weren't there some for parking directions last year? They were helpful. I may be able to borrow the wire frames for these signs, if that would cut down the cost. @ChrisTheDBA are you working the banners for fence and tent? Let me know if/where to pick up this task.

**Comment by ChrisTheDBA** [comment]
There are signs but posting signs downtown has been labeled littering. Not always but sometimes. We don't want to risk the slap on the wrist and fines.
