### ISSUE TITLE
directional signs (interior)

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#161]

**Comment by TaxLadyTracy** [comment]
We can't tape anything to the walls so please keep this in mind.

**Comment by ChrisTheDBA** [comment]
I think this is a non starter. Cant tape to walls and the space is one big open room so...thoughts?

**Comment by dtraleigh** [comment]
No interior signs needed in my opinion.

**Comment by TaxLadyTracy** [comment]
That's my thought too!

**Comment by suzanneccnc** [comment]
Do we need signage for breakout rooms, bathrooms, registration table, etc? We could post a map on a sandwich board, easel (although they always fall over!)

**Comment by dtraleigh** [comment]
The layout of the space is fairly simple so I don't think these are needed.

**Comment by suzanneccnc** [comment]
OK; will note item as complete, then, since we don't need the signs.
