### ISSUE TITLE
welcome sign with sponsor info

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#162]

**Comment by TaxLadyTracy** [comment]
If you get the artwork together we can get them printed at Office Max in Garner where we have a company account.

**Comment by lenaecb** [comment]
@TaxLadyTracy - Not sure you were on the email but we have the layout ready for this. Will you and @ChrisTheDBA be taking lead on the print via the Office Max you mentioned?

**Comment by TaxLadyTracy** [comment]
Yes ma'am

**Comment by lenaecb** [comment]
:) thank you @TaxLadyTracy - as always, the best!
