### ISSUE TITLE
order lanyards

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#163]
with CityCamp NC logo

**Comment by ChrisTheDBA** [comment]
We need to move on these soon if we want branded lanyards. our lead time killed us last year.

**Comment by ChrisTheDBA** [comment]
http://www.distributorcentral.com/websites/actiondesignspromo/item_information.cfm?SupplierItemGUID=FD59D7BC-2997-4DB1-9402-D8ABD698D6FE&strip=1&catalogGUID=18F2680E-6D0F-4D9F-BE23-A5777CD3112D

Our t-shirt guy can help.

**Comment by jhibbets** [comment]
I like the green, 3rd from the left. It's about 400 for qty 250. What's the
comparative cost?

**Comment by TaxLadyTracy** [comment]
Chris is sending him the artwork so we can get them ordered.

You like the regular green or lime green?

**Comment by jhibbets** [comment]
regular green

**Comment by lenaecb** [comment]
Were we able to get these ordered? Haven't  heard

**Comment by ChrisTheDBA** [comment]
They are scheduled to arrive on Friday

**Comment by ChrisTheDBA** [comment]
Wont be here on time so we have a generic backup in place
