### ISSUE TITLE
posters

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#164]
8.5 x 14 posters - what info?

**Comment by lenaecb** [comment]
poster designs are with Carsi

**Comment by jhibbets** [comment]
I thought we killed the posters? Can you clarify?

**Comment by lenaecb** [comment]
Yes, sorry, signage. There are multiples of these; I meant the foam board signage we talked about. I will move this to done since it's not reflective of the actual in progress
