### ISSUE TITLE
CityCamp NC logo'd cups, etc.

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#166]
for lunch

**Comment by ChrisTheDBA** [comment]
I have been told we have plenty of stickers

**Comment by lenaecb** [comment]
We have 2 of these cards open for cups, one if to do and one in progress... not sure which is correct

**Comment by ChrisTheDBA** [comment]
Ran out of time to assure delievery

**Comment by lenaecb** [comment]
I thought we decided 2 mtgs ago we didn't need logo cups that we were getting regular store bought?
