### ISSUE TITLE
Review EventBright

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#169]
@lenaecb, can you review the description on this page: https://www.eventbrite.com/e/citycamp-nc-2016-tickets-26649421136

**Comment by lenaecb** [comment]
@jhibbets I have reviewed it and left comments/edits in this Google doc to consider - https://docs.google.com/document/d/1UgprmarE6xfI1t7OMBHQXJVSrdARkFM1sn4OrAu8Hl4/edit?usp=sharing

**Comment by lenaecb** [comment]
Also - why can you select a 3 different dates on the actual invite (not when you click the 'Tickets' button)? I think this is to account for those coming on single days... not sure, but it's kinda confusing.

**Comment by suzanneccnc** [comment]
I like the description but find the date/time selector confusing. Because
it doesn't alter any of the information presented, just reloads the page.
Did I miss something?

**Comment by lenaecb** [comment]
@jhibbets - do you want me to make those edits mentioned in my doc? Or, do you want to make them or discuss them?

**Comment by jhibbets** [comment]
I haven't seen the recommended changes yet. A little behind. The three
dates are because we want to entice people to come for free on thu evening
and all day saturday.

**Comment by lenaecb** [comment]
@jhibbets  No worries - I went in and made the small tweaks just now.  Did realize I had editing access

**Comment by jhibbets** [comment]
done
