### ISSUE TITLE
Confirm Amy Gaskins as keynote speaker

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#180]
15 minute slot, need email, organization

**Comment by jhibbets** [comment]
Is Amy confirmed?

**Comment by ChrisTheDBA** [comment]
Confirmed and info in hand. Will add to speakers form.

**Comment by jhibbets** [comment]
I emailed her and requested she complete the keynote speaker form.

**Comment by ChrisTheDBA** [comment]
What is the URL of the form?

**Comment by jhibbets** [comment]
Keynote and CIO panel form:

   -

   https://docs.google.com/forms/d/e/1FAIpQLSfeh-38F8onjmN-yVxdEhYpnZfSqywGvzoMu_shOuXG_v1Hmw/viewform

Lightning talk form:

   -
   https://docs.google.com/forms/d/174euckXa-tRtZ4uqq5BGMOBBuEkOGSZ2CXNTiTsJp2k/edit
