### ISSUE TITLE
Zach: Reach out to Becky Tippet

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#183]

**Comment by jhibbets** [comment]
Zach, here is the email I sent to existing LT speakers. Feel free to re-purpose.

We have begun preparation for the speakers at this years CityCamp NC. And that means you. Can you help us out by completing the following form for your talk on September 22, 2016.

https://docs.google.com/forms/d/e/1FAIpQLSfWQHdKHVqf3jrnuqEqIo-THr2N34l7SzLSknZKRgNbcxIBfg/viewform

If you have any questions, please let me know.
[NAME]

**Comment by zachambrose** [comment]
Becky is going to fill out the form.  There is a very small chance she'll have jury duty in VA then, but she'll have a better idea in the next week or two.  We talked about her presentation and I think it will be a good fit.
