### ISSUE TITLE
Friday Lunch

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#200]

**Comment by ChrisTheDBA** [comment]
We are looking at Noodles & Company - $10/head

lot's of choices
will bring menu to next meeting to share and get input

targeting 75-80 headcount on order. last years was too much.

**Comment by dtraleigh** [comment]
I'm not disagreeing but at first, that number seems low. Do we think some
people just aren't eating lunch on Fridays? Are they going out or leaving
at lunch time?

I always thought we always had easily over 100 at this point in the event
so wonder what else people are doing.

**Comment by ChrisTheDBA** [comment]
Last year we did 115 for Friday and 100 for Saturday based on the registration numbers at the beginning if the week. That was right about 100% coverage. We ended up having Interfaith Food Shuttle come in and haul off about 40% of the food. 

I really don't know. Since last year we were out where no one could really leave. People were just not eating their fair share/getting smaller portions/watching their weight(?)

**Comment by dtraleigh** [comment]
Maybe it's the portion sizes. For example, if Noodle's and Company SAYS
that order X is for 10 people but in actuality it's for 15, then you over
ordered.

Weird. Oh well, thanks for humoring me.

**Comment by ChrisTheDBA** [comment]
I think we're saying the same thing. Last year our order was Moe's taco & fajitas for 100 since that was about the number of registrations. And I'd we gave away food for for 50+
That means we over ordered by 1.5x. 

This year we're going with 75-80 x 1.5 = 105-110 total. of course this is based on the estimate that we will have the 1.5x factor.
