### ISSUE TITLE
Sat Lunch

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#201]

**Comment by ChrisTheDBA** [comment]
open to ideas - last year was sandwiches

**Comment by dtraleigh** [comment]
If we can swing it, I vote for Jimmy John's over Subway. Sandwiches and
cookies. :)

**Comment by ChrisTheDBA** [comment]
I agree JJ is better but it's about 12/head and we're trying to keep it at or under 10. Subway was the only sandwiches in our price range. This year I'm bumping by $2.

I still think we need less food over all. At least 4 people walked out with entire trays of food. We went home with a couple ourselves and feed the neighbors<sigh>

Now it the time to think and call around any/everything on the table just try for $10/head

**Comment by ChrisTheDBA** [comment]
Is there one of those new food truck spots there? I might have an idea.

**Comment by dtraleigh** [comment]
CoM does have a spot for a food truck to back into. It's along Morgan
Street. They claim it works well. We could ask King about it.

**Comment by ChrisTheDBA** [comment]
Between them and the other church ? Definitely a question to ask King this weekend. Do we need a special permit?

**Comment by dtraleigh** [comment]
From my understanding, they don't need a permit because it's technically a
parking spot on private property, even though it doesn't look like it.
Scope it out when you go over there, along Morgan, to the right of the
door, there's space to massage a truck in there and can serve.

**Comment by dtraleigh** [comment]
https://goo.gl/maps/2Ap6sBPXgoJ2

See the google car reflection? Right in there.

**Comment by ChrisTheDBA** [comment]
hmmmm, is that the spot. Looks tight for a truck. I will measure it on Sunday.

**Comment by ChrisTheDBA** [comment]
Ok, the spot is a non-starter. Talking to King yesterday, he said the space is too small for a truck/trailer. So they'll be using it for bike/skateboard/stroller racks.

**Comment by ChrisTheDBA** [comment]
That means we're on the lookout for a cost effective lunch source.
