### ISSUE TITLE
Table Covers

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#205]

**Comment by TaxLadyTracy** [comment]
Leo I wanted to talk to you Monday about this.

**Comment by dtraleigh** [comment]
OK great.

**Comment by dtraleigh** [comment]
Tracy, I went out and scouted for some table covers and saw the plastic ones you mentioned. I went in thinking the fabric or vinyl would be better but I'm now not entirely convinced we'd get much value out of spending that much more money. :)

I do however want to purchase these table clips in order to hold the covers down. I just see a laptop sliding across and moving things all over the place and these seem reasonable.

https://www.amazon.com/dp/B01HAU2BM2/ref=wl_it_dp_o_pC_nS_ttl?_encoding=UTF8&colid=8HY9LDS4SFS1&coliid=I31DDXZOULV2I

Any alternate ideas or objections? If  not, I'm going to get them a little later along with a bunch of plastic table clothes. Probably in citycamp green, or whatever is close to it.

**Comment by TaxLadyTracy** [comment]
Not sure how well those will do with the plastic covers.   Also will they
fit the tables we are renting?

**Comment by ChrisTheDBA** [comment]
I think they'll be OK. At least we should try them. We will need to be somewhat careful in putting them on.

**Comment by dtraleigh** [comment]
The round tables have a lot of clearance. The rectangle tables have a lip
that starts about 5 inches inside. I think we should be ok.

**Comment by TaxLadyTracy** [comment]
Sounds good!  I have used tape in the past to keep them on tables and we
have plenty of duct tape lol :)

**Comment by dtraleigh** [comment]
Ordered/bought these.
