### ISSUE TITLE
Twitter Wall

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#22]
Do we want to find/build a twitter wall

**Comment by dtraleigh** [comment]
Examples?

**Comment by ChrisTheDBA** [comment]
http://www.wallofsocial.com/

https://www.google.com/search?q=twitter+wall&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwib3NuX47TLAhUBYSYKHetGBOYQsAQIXA&biw=1745&bih=828

**Comment by lenaecb** [comment]
What would this be used for and where?

**Comment by ChrisTheDBA** [comment]
It would be the tweets & instragram & and other social media from participants at the event running on the screens during the event

**Comment by suzanneccnc** [comment]
I think this would be a great idea. Another device for bringing everyone
together. I don't know anything about set-up/cost. Is it within our
wheelhouse to do this?

**Comment by ChrisTheDBA** [comment]
I've seen some very nice ones for $$$$, but I was thinking free/open source. Otherwise we have more important use for our funds.

**Comment by jhibbets** [comment]
When we did ours for ATO it was expensive. We paid for a service to stream
in the content from Twitter and Instagram (which I think we can get
free/cheap options here) and then we paid for monitor rental.

**Comment by suzanneccnc** [comment]
Have we ever approached local manufacturers (Lenovo) or alternative sources
(Kramden Institute) regarding lending/borrowing monitors?

**Comment by jhibbets** [comment]
No to my knowledge, but if we'd like to pursue this, then please move
forward and see about in-kind sponsorships.

**Comment by suzanneccnc** [comment]
@jhibbets @ChrisTheDBA Has anyone reached out to Lenovo, either this year or in the past? Contact? If not, I'll try to work old contacts of mine.

**Comment by ChrisTheDBA** [comment]
not happening this year
