### ISSUE TITLE
Update speaker page with current info

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#222]

**Comment by ChrisTheDBA** [comment]
The theme offers a speaker/staff page - what do you think of this? http://citycampnc.org/speaker-grid/

**Comment by jhibbets** [comment]
I can play around with it. Goal lats night was to get the info up. It still
needs to be updated with headshots and bios.

I also like the idea of a staff page, highlights the volunteers!!

**Comment by ChrisTheDBA** [comment]
We can do both. Different tags on the staff page can filter from there

**Comment by lenaecb** [comment]
@jhibbets - wrote you an email about this. Think we can get edit the speaker pages this week? Also, we haven't done a call for volunteers. Do we need one?

**Comment by jhibbets** [comment]
done: http://citycampnc.org/speakers/
