### ISSUE TITLE
Getting to and From CityCamp

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#223]
Directions to parking and how to navigate around Bikefest. (which closes down Fayetteville Street and other side streets that weekend)

http://www.capitalcitybikefest.com/about-us/venue-map-parking-info

**Comment by lenaecb** [comment]
@dtraleigh - want to try and get a promo out to our attendees via email and create a blog post called' Navigating CityCamp 2016" that would include parking info. Chris mentioned you might have that covered. Can we sync on that?

**Comment by dtraleigh** [comment]
Yes. Would you like me to start it and then you can look over? I can begin
with the basics.

**Comment by lenaecb** [comment]
Yes, that'd be great!

**Comment by dtraleigh** [comment]
@lenaecb take a look. I've added a post for this. Go ahead and polish it off if it works for you and then schedule it.

**Comment by dtraleigh** [comment]
Published.
