### ISSUE TITLE
Code Sprints - email sent

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#225]

**Comment by jhibbets** [comment]
I think this is all wrapped up?

**Comment by marshallj** [comment]
Working on getting a description for the Durham project for the website. Aside from that, yes done.

Jason Marshall

**Comment by marshallj** [comment]
Just updated the website with Asheville and two Durham projects. That should be a wrap. 5 total code sprint projects.
