### ISSUE TITLE
link with Girl Devlop It "Hackathon How Tos"

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#228]
event is being held Sept. 15; do we want to provide a link to their event from our webpage? Do we want to advert our event in conjunction with their event? www.meetup.com/Girl-Develop-It-RDU/events/233533151

**Comment by suzanneccnc** [comment]
@ChrisTheDBA @jhibbets Thoughts?

**Comment by ChrisTheDBA** [comment]
I would suggest a guest blog post with some of the info and links to the meetup

**Comment by suzanneccnc** [comment]
OK, do you want to request one of the bloggers we already have invited or
ask GDI to write a post or perhaps one of us?

**Comment by ChrisTheDBA** [comment]
I think it's on them to write it. We already have one from the past years and I just did one on doing unconference sessions.

**Comment by suzanneccnc** [comment]
OK. I'll reach out to GDI contact and suggest they do a blog post. Not
being a blogger myself it is not clear looking at the website how to submit
a blog for posting. Can you tell me how that would be done and then I can
include it with my outreach to GDI.

**Comment by ChrisTheDBA** [comment]
They just write document. It gets edited and then Lenae, Jason or one of us will post it.

**Comment by lenaecb** [comment]
@suzanneccnc - yes, they can submit it to me in any format for review and then we can post it for them
