### ISSUE TITLE
Digital Connector invites

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#238]

**Comment by ChrisTheDBA** [comment]
We've already connected with Linda and Bradley. That's where Richard Marshall came from. Good o foramlly invite but make note of it.

**Comment by jhibbets** [comment]
Just wanted to push the registration, that's all

**Comment by ChrisTheDBA** [comment]
Linda has signed up. Russell Marshall has signed up and submitted his lightning talk. Bradley is getting the kids going!
