### ISSUE TITLE
Invite elected officials - town of garner

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#243]

**Comment by suzanneccnc** [comment]
How about Wake Forest: Marion Jones (mayor), Jennifer Rall (urban forestry
coordinator)?
Best regards,
Suzanne

**Comment by ChrisTheDBA** [comment]
I can take Garner. First name basis with the mayor and others we do fellowshup
fridays at the Beered Lady!
Chris Mathews

On Mon, Aug 29, 2016 10:24 PM, suzanneccnc notifications@github.com wrote:
How about Wake Forest: Marion Jones (mayor), Jennifer Rall (urban forestry
coordinator)?
Best regards,
Suzanne
