### ISSUE TITLE
Setup tour for Church on Morgan

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#25]

**Comment by dtraleigh** [comment]
Looks like Friday 4/22 would be a good day to do this. King White would be giving us the tour and that works real well for him. Morning, 9am, is what he's proposing.

Can anyone make this? I can but I've seen the space. What is the best way for me to communicate this "Tour of Church on Morgan" to the planning team?

**Comment by ChrisTheDBA** [comment]
That works for me. Tell King, Tracy and I are in. I figure the three of us will be responsible for logistics. If you're comfortable with the layout, i get it you don't need to see it again.

**Comment by dtraleigh** [comment]
OK great. 9am it is then. Let's meet at Church at Morgan and I'll tell King
the same.

**Comment by jhibbets** [comment]
Can someone set-up a calendar invite, that would be great.

**Comment by dtraleigh** [comment]
Done.
