### ISSUE TITLE
The Grid

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#254]
I think we said that we're good here but I wanted to make sure once again. We have everything we need for voting and to build a grid against the back wall?

**Comment by jhibbets** [comment]
We need 8/5x11 paper, and we recently discussed having a pre-printed form
for pitches to include session title, name, and an area for voting.

Since we can't have stuff on the walls, do we want to bring in a rolling
white board?

Jason

**Comment by TaxLadyTracy** [comment]
Yes i have the markers and the paper for this.

**Comment by TaxLadyTracy** [comment]
I thought we talked of using the glass near the entrance instead of the
walls but if you have access to a rolling white board that's great!

**Comment by ChrisTheDBA** [comment]
King is double checking but windows look good

**Comment by dtraleigh** [comment]
The grid on the windows should be fine. Just need to keep in mind that if the paper is thin, light through it might not be very readable. Plus, it'll look bad from the outside but we'll figure something out day of.
