### ISSUE TITLE
Booth for ATO

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#255]
Todd wants a booth/table for ATO at CityCamp. Who is working on that?

**Comment by TaxLadyTracy** [comment]
I am signed up and will be there with bells on!!

**Comment by jhibbets** [comment]
This is for a table at CityCamp to promote ATO. Not booth duty for Code for
Raleigh @ ATO :)

**Comment by ChrisTheDBA** [comment]
We should be fine. I will keep this open at  reminder and contact Todd to get his preference for space.

**Comment by TaxLadyTracy** [comment]
Gotcha!
