### ISSUE TITLE
home page images aren't loaded for me

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#265]
I'm not seeing any images on the home page, which makes it impossible to see the options in the main body. I can send you a screenshot.

**Comment by jhibbets** [comment]
working in Chrome, not in FF -- for me, it's all all images, including the logo in the header that aren't displaying.

**Comment by ChrisTheDBA** [comment]
I just opened in FF and looks same. your cache?
Chris Mathews

On Wed, Sep 14, 2016 1:02 PM, Jason Hibbets notifications@github.com
wrote:
working in Chrome, not in FF -- for me, it's all all images, including the logo
in the header that aren't displaying.

**Comment by jhibbets** [comment]
I cleared cache and did a shift+reload. same results. I'll check later. the images were just there, so this might be a problem with my browser

**Comment by jhibbets** [comment]
I cleared cache and restarted my browser, and I'm getting the following CSS error:

"JQMIGRATE: Migrate is installed, version 1.4.1" jquery-migrate.min.js:2:541
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. BackgroundFramework.js:504:0
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. BackgroundFramework.js line 470 > eval:3:0
no element found

**Comment by ChrisTheDBA** [comment]
disabled server side caching. check it outplease

Chris Mathews

On Wed, Sep 14, 2016 1:18 PM, Jason Hibbets notifications@github.com
wrote:
I cleared cache and restarted my browser, and I'm getting the following CSS
error:

"JQMIGRATE: Migrate is installed, version 1.4.1" jquery-migrate.min.js:2:541
Use of getUserData() or setUserData() is deprecated. Use WeakMap or
element.dataset instead. BackgroundFramework.js:504:0
Use of getPreventDefault() is deprecated. Use defaultPrevented instead.
BackgroundFramework.js line 470 > eval:3:0
no element found

**Comment by ChrisTheDBA** [comment]
Can't duplicate

**Comment by jhibbets** [comment]
Maybe we could contact the theme people for support?

Here is a new error I got after updating the site tonight:

downloadable font: OS/2: bad linegap: -32 (font-family: "kt-icon" style:normal weight:normal stretch:normal src index:1) source: http://citycampnc.com/wp-content/themes/pinnacle_premium/assets/css/fonts/kt-icon.woff?a-vp28cu pinnacle.css:1:78045
Use of getUserData() or setUserData() is deprecated.  Use WeakMap or element.dataset instead. BackgroundFramework.js:504:0
no element found mod_pagespeed_beacon:1:1
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by jhibbets** [comment]
Just tested at home, I think it's just me.

**Comment by jhibbets** [comment]
Ha. the problem only happens on citycampnc.com, when I switch to .org, the homepage is fine.

**Comment by ChrisTheDBA** [comment]
The theme people seem to say this is related to the cached copy of a font.
Seems to be isolated to a single users browser. Not wide spread. Tracy suggested
turning it and back on again.
Chris Mathews

On Wed, Sep 14, 2016 10:13 PM, Jason Hibbets notifications@github.com
wrote:
Ha. the problem only happens on citycampnc.com, when I switch to .org, the
homepage is fine.
