### ISSUE TITLE
Enter/udpate guest post for John Stephens -CIO panel

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#277]

**Comment by jhibbets** [comment]
Jason has the lead, will hand off to @lenaecb for final review, publishing, and promotion.

**Comment by lenaecb** [comment]
Awesome! Will be on the look out for it

**Comment by jhibbets** [comment]
It's ready for your review, in Wordpress.

**Comment by lenaecb** [comment]
done and published/promoted
