### ISSUE TITLE
Update website for datajam prize money

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#281]
We're going to offer a $1000 first place prize and a $500 best use of ESRI technology prize at Data Jam.

**Comment by lenaecb** [comment]
How/where do you want me to put this information?

**Comment by ChrisTheDBA** [comment]
I wouldn't do this as citycamp. the big we are trying to is get out of this
business and let Zach cover it
Chris Mathews

On Mon, Sep 19, 2016 6:38 AM, lenaecb notifications@github.com
wrote:
How/where do you want me to put this information?
