### ISSUE TITLE
update WP theme

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#3]

**Comment by jhibbets** [comment]
jh > Maybe after the event? http://govpress.co
cm > This might even be a good session/hackathon project for UX/graphics folks  Pitch it and see about feedback.
dtr > I can tinker with this. Is it still too early to overhaul the site? Maybe I'll schedule time in July to do this if that's ok with folks.
jh > My thought is that we should work on this at brigade meetups
dtr > Cool. That works.

**Comment by ChrisTheDBA** [comment]
def hack night activity
