### ISSUE TITLE
Twitter list of speakers

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#303]
Hey @lenae what do you think about making a twitter list for all our speaker? 2016-speakers?

http://citycampnc.org/speakers/

Is that something you can help with?

**Comment by suzanneccnc** [comment]
Got it!

**Comment by lenaecb** [comment]
Sure, do you want some sort of widget like you mentioned or @suzanneccnc do you have something else in mind?

**Comment by ChrisTheDBA** [comment]
separate but related - do you need a cheat sheet with all the handles for live tweets?

**Comment by jhibbets** [comment]
I'll post that on the schedule page

**Comment by lenaecb** [comment]
Yes, I would love a cheat sheet. @jhibbets - to your earlier question, were you thinking a widget? If not i can also get these into the speaker/schedule page

**Comment by suzanneccnc** [comment]
Sooo, Jason posted most of the twitter handles with the speakers' bios.
Here is a cheat sheet:
https://docs.google.com/spreadsheets/d/1ueZ-5HLOyjtQ4zefsO-KLYJ3rnckX-RtoV2Mkrw4gS8/edit?usp=sharing

**Comment by jhibbets** [comment]
Pro tip - ask for Twitter handles when you get  their other details, like
bio and headshot :)

**Comment by jhibbets** [comment]
Just to be sure I'm clear, I meant a list called 2016-speakers on Twitter.com via the @citycampNC handle. As in, adding our speakers to a list that need to be created

https://twitter.com/citycampnc/lists

**Comment by lenaecb** [comment]
https://twitter.com/citycampnc/lists/speakers-2016/members - ready to go. Use how you wish

**Comment by ChrisTheDBA** [comment]
Can you add @tourtech and @churchonmorgan or point me to how to do it
Chris Mathews

On Wed, Sep 21, 2016 8:22 PM, lenaecb notifications@github.com
wrote:
Closed #303.

**Comment by lenaecb** [comment]
@ChrisTheDBA - i have added both to the list as well
