### ISSUE TITLE
Need: 16 GB USB thumbdrive

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#305]
I talked with Zach form CoM today and we are going to record the talks via a USB connection into their equipment. Does anyone have one we can borrow? If not, I"ll go purchase one. Ideally, USB 2.0+ speed.

**Comment by dtraleigh** [comment]
I only have a 32Gb one for use. :P

**Comment by jhibbets** [comment]
Supersize me! thanks
