### ISSUE TITLE
Easels

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#308]
What is the easel situation? Without a/v room each room we need the option for sessions to write somewhere

**Comment by jhibbets** [comment]
I have 4 easels I can bring

**Comment by ChrisTheDBA** [comment]
we have two
Chris Mathews

On Tue, Sep 20, 2016 6:35 PM, Jason Hibbets notifications@github.com
wrote:
I have 4 easels I can bring

**Comment by dtraleigh** [comment]
I have none. Please bring those and let me know if we need more. So that's
6 total, yes?

**Comment by jhibbets** [comment]
My 4 are packed up and ready to go.
