### ISSUE TITLE
do we have code for america stickers?

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#315]
We should put them out at the reg table if we have some

**Comment by TaxLadyTracy** [comment]
Yes LOTS of them!!  Also citycampNC ...since you are the keeper of the swag
does Red Hat have anything to donate for the bags or stickers to sit out :)

**Comment by jhibbets** [comment]
I'll bring some stickers

**Comment by TaxLadyTracy** [comment]
Thanks!!!!!
