### ISSUE TITLE
Code for Raleigh celebration suggestions

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#365]
Code for Raleigh is looking to get together in December to celebrate a great year and talk about 2017. If you have any ideas on where to meet-up, please comment on this issue.

**Comment by ChrisTheDBA** [comment]
Pizza is usually a safe consensus option...and beer. Isn't Ruckus centrally located?

**Comment by dtraleigh** [comment]
That would work. Ruckus on Avent Ferry?

**Comment by aikimark** [comment]
How about one of the locations away from downtown, such as Harrison Ave or Tryon Rd?

**Comment by ChrisTheDBA** [comment]
I was actually thinking of Tryon and Walnut, but we have a car so location is open.

**Comment by marshallj** [comment]
Would love to talk, but don't think I can swing an up and back trip.
