### ISSUE TITLE
Update mailchimp footer

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#387]
Still says CityCamp Raleigh, needs to say NC Open Pass, Code for Raleigh somewhere, maybe have something like, Solving civic problems for our community as the tag line where is says you are a Raleigh civic hero.

I think we have a PO box address we can use, but not sure.

**Comment by jhibbets** [comment]
@ChrisTheDBA  Do we have an address?

**Comment by ChrisTheDBA** [comment]
Not that I am aware of. "How is this for a tagline "Building community for
a better tomorrow through civic design, technology, and data."

Chris Mathews

**Comment by suzanneccnc** [comment]
"better" doesn't strike me quite right...empowered?, engaged?, informed?,
inclusive?, progressive?...something uplifting but not condemning current
solutions...

**Comment by ChrisTheDBA** [comment]
from the Code for America website...https://www.codeforamerica.org/who
