### ISSUE TITLE
Parse Greensboro Message for Initiatives

### ISSUE THREAD

**Issue by toobulkeh** [ncopenpass/NCOpenPass#391]
Here is Greensboro's  City Manager message - https://www.youtube.com/watch?v=u8yQQtatToU

I need to watch this and parse meaning / Greensboro's goals/initiatives into a NC OpenPass Challenge that fits our templates here: https://docs.google.com/document/d/1MhoT2MCrjgWScfgHkdtKlFGpgQEm0iyKU5DhJ-_0Q-E/edit

The idea is to parse out what goals we can and compare them to Wake/Raleigh/Durham/ChapelHill goals that align nicely

**Comment by aikimark** [comment]
I recruited a developer, Randy, who lives in Greensboro.  Recommended that he contact us.

**Comment by toobulkeh** [comment]
Goal #1: Economic Development. Ensure strong functioning of City services and resources to positively influence and support economic and community development, including making downtown Greensboro a destination location to enhance the economic vitality of the entire city.

Goal #2: Infrastructure. Protect, maintain and enhance the City's public infrastructure to improve the quality of life in Greensboro that is sustainable and cost effective.

Goal #3: Public Safety. Promote public safety and reduce crime by being visible and active in the community and by being responsive to all residents. Continue to work to create a proactive environment that encourages, educates, and develops programs in collaboration with all City departments. GM 911, GBO Fire Department, GBO Police Department

Goal #4: Customer Service. Create a positive customer experience and employee workforce where the customer is respected, appreciated, and valued. Attract, develop, and retain talented leadership throughout the city. Includes Development of enhanced methods of communications and outreach with citizens and businesses. Open Data Portal, City Career Fairs, Quarterly PM Report.

Goal #5. Fiscal Stewardship. Strengthen efficiency and improve effectiveness of City programs to optimize service delivery while promoting transparency and accountability to the public. Budget Development, Effective and efficient use of City resources (Program inventory).

From Jim Westmoreland, Greensboro City Manager.
