### ISSUE TITLE
Add Greensboro Data to Challenge Templates

### ISSUE THREAD

**Issue by toobulkeh** [ncopenpass/NCOpenPass#396]

**Comment by toobulkeh** [comment]
Take initiatives from https://waffle.io/codeforraleigh/NCOpenPass/cards/58ec0b333518c700882fe059

build into challenge templates Bill is going to start

**Comment by toobulkeh** [comment]
Hey @jhibbets and @ChrisTheDBA -- are tasks deleted from Waffle? The link above is not working for me.

**Comment by toobulkeh** [comment]
Here's the data in GitHub (not Waffle) - https://github.com/codeforraleigh/NCOpenPass/issues/391

**Comment by toobulkeh** [comment]
Added to templates:
https://docs.google.com/document/d/1EXbWQPWnLM68CzGk5beV65ElPmL3OwF-mTswYHncBtY/edit

https://docs.google.com/document/d/1Jr23k3UpaquJhxuWMvQXh1LFgCU2puvm5igqdWgbOZA/edit

https://docs.google.com/document/d/1SPbfKcQCV-kZAuX1HWQ40kmFZfNFMFgBpMQrPpevQUA/edit

**Comment by ChrisTheDBA** [comment]
Closed issues will age off the waffle board display, but stll available on
the github issue page.

Chris Mathews
