### ISSUE TITLE
Password Vault/LastPass

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#399]

**Comment by jhibbets** [comment]
Just set-up LP for: Eventbright (CityCamp NC + NC Datapalooza), Twitter (CityCamp NC + NC Datapalooza), Hootsuite, and survey monkey. Mailchimp should have a personal invite

**Comment by jhibbets** [comment]
I can not access Youtube account, Instagram, or Dropbox, who has access to that??? @lenaecb @ashumz

**Comment by ashumz** [comment]
No info on this one from my end - sorry!

**Comment by ChrisTheDBA** [comment]
I have updated Instagram. How are they being stored?

**Comment by jhibbets** [comment]
Youtube should be squared away.

**Comment by ashumz** [comment]
still need access for all of these @jhibbets for ashley.mcclelland@ibm.com

**Comment by jhibbets** [comment]
done
