### ISSUE TITLE
Content marketing plan for videos

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#41]

**Comment by ChrisTheDBA** [comment]
I looked on the google drive for when these will be promoted? Alas, I wasn't able to locate the appropriate doc...

**Comment by lenaecb** [comment]
It is not because they are not all uploaded and I am not sure how we feel about the quality. We can most definitely push the out via social and even create a post to get hype up for the talks this year but we'll need to get them all uploaded (or at least select some favorites).

**Comment by ChrisTheDBA** [comment]
I uploaded all them over a year ago I don't know what happened to them

**Comment by ChrisTheDBA** [comment]
All of the videos have been uploaded as of April 22 and they are set to private

**Comment by lenaecb** [comment]
If we can get these all turned from private to public I can add them to the list of promotion/content mktg

**Comment by lenaecb** [comment]
@ChrisTheDBA @jhibbets - can we get last year's speakers turned on? I am not sure what we can do to cut them down at this time or if that's necessary.

**Comment by ChrisTheDBA** [comment]
All are active and anonymously viewable on YouTube

**Comment by lenaecb** [comment]
Awesome, thanks. Am going to probably do a blog post for the full series as well as promote individual recordings.
