### ISSUE TITLE
[phase 2: aug 14th] email past attendees 
 of citycamp and datapalooza about open registration

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#410]
from jason: send an announcement to last year NDoCH, CityCamp NC, and Datapalooza attendees letting them know that NC Open Pass is open and to save the dates for the 3 events this year (note that NDoCH is Civic Spark Day this year)

**Comment by ashumz** [comment]
on today's call we came to the understanding that we should be clear about all available registration options when we reach out to this group of people. while there is value in announcing nc openpass registration being open, the pricing difference between early bird nc openpass reg ($40) and a citycamp student registration ($10) is large enough that, if I only want to attend citycamp, I want to make sure I know I still have that option. 

We need to have a standalone citycamp nc *only* registration option available at the time we reach out to this audience, or at least have clarification via a pricing table on an initial blog post on the citycamp blog that the option WILL be available in the future 

cc @jhibbets @natalienoel1 @ChrisTheDBA @suzanneccnc

**Comment by jhibbets** [comment]
@natalienoel1 is going to merge Past Attendees - Datapalooza, Open Data Challenge, 2016 Data for Decisions and CityCamp NC 2016 attendees list (with event segmentation), then schedule this email for Monday morning, august 14.

**Comment by jhibbets** [comment]
@natalienoel1 would be great to do #517 before this goes out on Monday.

**Comment by jhibbets** [comment]
Blog post is ready and published announcing NC Open Pass: http://citycampnc.org/2017/08/14/get-your-2017-nc-open-pass/

**Comment by natalienoel1** [comment]
Need credit card number to add more credits to Mailchimp!  @jhibbets

**Comment by jhibbets** [comment]
Hmmm...I bought 1,000 credits for like $50, I thought that should have been
enough to last us a while. When I log in it says: *965* credits remaining
