### ISSUE TITLE
pre-event email series for current registrants

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#411]
7-9 days out: leading up to the event, what do registrants need to know? how can we get them excited and make sure they feel prepared to engage? 

1 day out: logistics info - venue, timing, where to park, what to expect for food, schedule, etc.

**Comment by jhibbets** [comment]
@natalienoel1 Hoping you can prepare email do go out via event bright that will also double as blog post. We'll need three emails/blog post:
1) Get ready for CityCamp NC lightning talks (post/send on Wednesday morning)
2) CityCamp NC day 2 - smart cities, open data, and the (un) conference (post/send on Thursday at 9pm)
2) CityCamp NC code sprint and NC Datapalooza open data competition (post/send on Friday at 5pm)

Let me know if you have and questions. We probably can find some past examples. But each message should include details on venue, parking, link to our schedule and speaker, and what to bring / expect.

**Comment by jhibbets** [comment]
@natalienoel1 very important that we lead with mentioning our code of conduct and link to: http://citycampnc.org/about/code-of-conduct/

**Comment by natalienoel1** [comment]
@jhibbets Great. I can definitely get these out and ready to go.  Wondering if we could talk about this tonight? Want to make sure it has all the information you would like it to and if you have a past email that would be helpful as well!

**Comment by jhibbets** [comment]
Happy to stay on the call extra if needed, happy to discuss.

**Comment by natalienoel1** [comment]
Yes, that would be great!

**Comment by jhibbets** [comment]
Showed @natalienoel1 the emails from Eventbright last year, there are actually 4 emails to send out. 0) Get ready for CityCamp NC email.

**Comment by jhibbets** [comment]
Draft is here: https://docs.google.com/document/d/12MLy9v1mobxjUg7dflCIhKyUFecavA0HdAzEYhQXSNY/edit

**Comment by jhibbets** [comment]
@natalienoel1 I copied the doc you sent me to the marketing folder and made some updates. These should be good to go: https://docs.google.com/document/d/12MLy9v1mobxjUg7dflCIhKyUFecavA0HdAzEYhQXSNY/edit If you can get them scheduled in Eventbright and Wordpress, that would be a huge help! Thanks

**Comment by natalienoel1** [comment]
@jhibbets Awesome. Thank you! I will schedule these out!

**Comment by jhibbets** [comment]
@natalienoel1  Just got the first email. But I don't see the others in Mailchimp. When those are scheduled we can close the card, thank you

**Comment by natalienoel1** [comment]
I have scheduled all of the emails in eventbrite but am not able to login to wordpress to schedule those out through blogs for some reason.

I see you mentioned mailchimp? I thought we were doing just eventbrite and wordpress.

**Comment by natalienoel1** [comment]
@jhibbets ^^

**Comment by jhibbets** [comment]
@natalienoel1 sorry, I meant in eventbright. But per our discussion on Monday, we should have one more mailchimp email going out today for "last chance to register"

We can figure out the WordPress login during the marketing call today

**Comment by natalienoel1** [comment]
@jhibbets Not a problem. And yes that will be sent out around 11.

**Comment by jhibbets** [comment]
Update: waiting on confirmation from @natalienoel1  that see can log into WP to finish this task.

Note: I added a copy of the first email to EventBright to resend to net new registrants from today and it will send at noon tomorrow.
