### ISSUE TITLE
find press release contacts for nc open pass press release

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#415]

**Comment by ashumz** [comment]
@suzanneccnc assigning this one to you, since we talked awhile back about you being interested in helping with a press release :)

**Comment by suzanneccnc** [comment]
Here is a list from 2016 of press outlets/contacts: https://docs.google.com/document/d/1Aw7LZDCJXx-RW-G8sTShjwpWZgkpzJAgIJrBc3TbhyE/edit Any updates @ChrisTheDBA @jhibbets @natalienoel1 @ashumz ?

**Comment by jhibbets** [comment]
If anyone has a few spare cycles to send our press release to any press, that would be great.
