### ISSUE TITLE
create nc open pass press release

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#416]

**Comment by jhibbets** [comment]
Not sure if this is what you're looking for, but here is a blog post announcing NC Open Pass : http://citycampnc.org/2017/08/14/get-your-2017-nc-open-pass/ -- it's live a published.

**Comment by jhibbets** [comment]
We might have someone who can help with this,  Lindsey Carbonell from Reese News Lab

**Comment by jhibbets** [comment]
@natalienoel1 @suzanneccnc I won't have the bandwidth to help with this, if we don't have something for early next week, then it's probably not worth doing this

**Comment by suzanneccnc** [comment]
I can tackle it this weekend, but not before. If @natalienoel1 has the
bandwidth before, then please jump in.

**Comment by suzanneccnc** [comment]
DRAFT uploaded to Marketing/Communications folder: https://drive.google.com/drive/u/0/folders/0BwjOr-60lG0lRHpZWjRsZTMzenc

**Comment by ChrisTheDBA** [comment]
Consider last year's https://docs.google.com/document/d/1zrfArCBsMIr0nrbXaWeL10ZeP4JgyTMf0K0v3OupFWE/edit?usp=sharing

**Comment by jhibbets** [comment]
I've made a few edits and added this to WordPress, ready to publish after @suzanneccnc  and @natalienoel1 review - http://citycampnc.org/?p=2935&preview=true Great start Suzanne.

**Comment by suzanneccnc** [comment]
Can't figure out WordPress access. Can you send link to our wordpress
account?

**Comment by jhibbets** [comment]
http://citycampnc.org/wp-admin

**Comment by suzanneccnc** [comment]
It can't be this hard...are you sure I have a wordpress account? I've tried
every combination or email/username/password, but no go. I'm sure your
edits are awesome. Go for it.
Best regards,
Suzanne

**Comment by jhibbets** [comment]
Username is
*suzannebeaumont
<http://citycampnc.org/wp-admin/user-edit.php?user_id=10&wp_http_referer=%2Fwp-admin%2Fusers.php>*
I'll reset your password
*
<http://citycampnc.org/wp-admin/user-edit.php?user_id=10&wp_http_referer=%2Fwp-admin%2Fusers.php>*

**Comment by jhibbets** [comment]
Let me know if you did *not* get a password reset email. I just did it.
