### ISSUE TITLE
Purchase banners and/or flags

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#419]
Once we have the logo design finalized start shopping the purchase of these signs

**Comment by dtraleigh** [comment]
I inquired with Capital Flag and Flagpole and they need 5 weeks lead time to create the flag. Can we set a deadline for the logo of August 23?

**Comment by dtraleigh** [comment]
For the flag, we can choose a traditional rectangle shape or trapezoid shape. The "look" of it depends on how we hang it. A trapezoid will look "flat" when at a 45 degree angle while a rectangle needs to be hung on a pole at 0 degrees.

Attached is a diagram of a First Friday flag hung at an angle. I vote for this one.
![nash_hall_FF_flag.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5564f79571c5690d009928d2/125516c66e82c728ace21e0d46e695892bbd8ba883e580658262f6982841653f6b14b1247a80e03cfd183954590b1baf40585e47f9fd892aa1e26970880d5ae4d6640966da2f53fde6d640e258f075c95d8fa4bf8b46c1ed3d25e38c8c4f3e1f06108ced10.JPG)

**Comment by ChrisTheDBA** [comment]
![IMG_2041.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/547f03d3c1ffe602001c5269/125516c66e82c728ace21e0d46c1b9bd1cd0d3fddeabf301b44fff9e2c4533317346f67d7480b079ef1328545b5f4fab150d5f46ada8802cafe02e6c981e5ab38532022d8c6853beb2901db90bbb258b4e80beba8d48c8ee3923f5c6.JPG)

Something like this would be great. reusable.

**Comment by ChrisTheDBA** [comment]
This is what I want to order.
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/547f03d3c1ffe602001c5269/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f52f75d6b278ee112e555f5e49f814585d15adf08e22f0a42062c80d55b98e30063e937f03a6aa811eb500bf208a4981bfbb8a45c2e13e37aa.PNG)

**Comment by carsi** [comment]
Can I get the specifications for size and output to design this to? Thanks!

**Comment by carsi** [comment]
Also, is this in addition to or in lieu of the flag Leo is ordering?

**Comment by ChrisTheDBA** [comment]
This would be in addition to the Flag. For anywhere there isn't a 45 deg
flag pole like ATO and inside the building(s).

The Vistaprint page that I mocked up had 2.5' x 6' and 2.5 x 4'. I like the
6' one. Price is $160(might need stand so $$$)

Chris Mathews

**Comment by dtraleigh** [comment]
Does this item include banners/materials with sponsors on them? What do we think the drop dead date is for sponsors that need to go on printed material?

I ask cause Ipreo seems very possible to sponsor but they are stringing this out far longer than I feel it should.

**Comment by dtraleigh** [comment]
I'm placing the order on Friday 8/11 for the flag.

**Comment by dtraleigh** [comment]
Flag order is finally placed!

**Comment by carsi** [comment]
🚩🚩🚩🚩🚩🚩🚩
