### ISSUE TITLE
create event material to hand out at events

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#422]
something like a postcard or even a sticker with combined citycampnc/ncdatapalooza logos, dates, tag line or brief explanation. ex of target audience: nc data rescue events

**Comment by snewt-n** [comment]
Do we have a sticker person already here in the area? I have to assume someone has one. Thoughts on magnets? Do we have a prototype of combined logos or just Jason's ascii?

**Comment by ChrisTheDBA** [comment]
We have a supply of stickers and pins.Not sure of number.

No one local, sticker mule in the past.  Budget is a little tight right now
until funds come in.So we might have to hold off. Magnets is an option if
we have the money.

 The combined logo and all others are on google drive.

Chris Mathews
