### ISSUE TITLE
NC Open Pass at Creative Mornings RDU

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#435]
reach out to Jonathan Opp to pitch having NC Open Pass present at August Creative Mornings. From 7/10 planning meeting, one idea is to use the GDI/Wake Forest Open Data Portal story; maybe include ESRI somehow.

**Comment by carsi** [comment]
Creative Mornings has a theme for their speakers each month (the theme for July is Equality, for example). I couldn't find the theme for August, but it will be a more effective pitch to Jonathan Opp if the story we want to tell conforms to August's theme.

**Comment by suzanneccnc** [comment]
Agreed, however, the theme is usually not announced until the first week of
the month. The pitch to Jonathan will be that NC Open Pass (CityCamp,
DataPalooza) story can support many stories/themes: equality (open data for
all, all welcome), innovation, bravery (unconference), empowerment, etc.
Best regards,
Suzanne

**Comment by suzanneccnc** [comment]
Met with Sarah Powers, Executive Director, Raleigh Arts, she also see some a fit between CiryCamp and CreativeMornings. Still flummoxed on how to move this forward; may be an effort for next year.

**Comment by carsi** [comment]
The theme for August is Genius

https://creativemornings.com/blog/august-is-genius

If we'd like to move forward with this, we can pitch Jonathan on CityCamp's cross-pollination between people during the event, learning from our mistakes of the past to refine the event every year, etc. May be something @jhibbets can talk about depending on his availability.

**Comment by jhibbets** [comment]
@suzanneccnc as of right now, I'm available on August 25.

**Comment by carsi** [comment]
It looks like they've already picked a speaker for this month. We should
figure out how this works for another talk in the next year, or partner
with CreativeMornings RDU to promote NCOP/Datapalooza/CCNC to creatives. I
can email Jon Opp to see how we can partner together (or @suzanneccnc
<https://github.com/suzanneccnc> if you've already contacted him, I don't
want to barge him with emails from us).

**Comment by suzanneccnc** [comment]
Sent Jonathan Opp an invitation to do a lightening talk.

**Comment by carsi** [comment]
Great, thanks!

**Comment by suzanneccnc** [comment]
So , this is not happening for this year, but lets keep it on the backlog for next year.
