### ISSUE TITLE
consider Carroll's Kitchen as food vendor

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#439]
www.carrollskitchen.org Good cause; great food; they do catering. Contact: Teresa Garrett, Program Director

**Comment by ChrisTheDBA** [comment]
need to takein to consideration price. Breakfast is $110 for 10 people.
That comes out to +$1400 for breakfast. Lat year brekfast cost $500 for
both days. Lunch is $12 per boxed lunch sandwich. We did hot lunch both
days for $9/person.

We need to see if we can get price down.

Chris Mathews

**Comment by ChrisTheDBA** [comment]
Prices are kind of high as stated above. Also didn't seem too into Saturday catering.

**Comment by ChrisTheDBA** [comment]
has anyone seen about getting the price per head down?
