### ISSUE TITLE
Table layout for Nash Hall

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#449]
Create a plan ahead of time about how to lay our the tables and chairs during the Friday speaker session and afternoon unconference.

**Comment by dtraleigh** [comment]
Here's my  idea for this year. Any feedback would be appreciated.

https://docs.google.com/document/d/1otLQKA8D-SzYyC8psRUOpPDZcSFqo5iTDl67qQ19OWk/edit?usp=sharing

**Comment by jhibbets** [comment]
Looks great @dtraleigh
