### ISSUE TITLE
clarify NCOpenPass vs CityCampNC and NC DataPalooza

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#451]
When are we using combined website (www.ncopenpass.com) vs. legacy individual ones? When are we using new "stacked" logo vs. legacy logos? please help fill out matrix: https://drive.google.com/drive/u/0/folders/0BwjOr-60lG0lTklRNHZKN1RuSjg

**Comment by suzanneccnc** [comment]
Deadline for MAIN event info is noon today.

**Comment by carsi** [comment]
@suzanneccnc Can you recreate the matrix in Google Sheets? I cannot open xslx files. 

Great idea. Thanks!

**Comment by jhibbets** [comment]
Let's discuss the details on when to use what on the call tonight. For the
MAIN event, I would recommend we submit NC Open Pass details in addition to
CityCamp NC, to help give Datapaolloza some love even though its outside of
the September gathering.

**Comment by suzanneccnc** [comment]
Done!

**Comment by jhibbets** [comment]
oops - I put this on the wrong card, adding here and happy to discuss this evening.

RE: are we using this logo for everything? My initial feeling is that we should use this logo to promote NC Open Pass and use other event logos to promote each individual event. We are essentially running 4 simultaneous campaigns: Drive reg for NC Open Pass, drive reg / promote for Civic Spark Day, drive reg / promote for NC Open Pass, drive reg / promote for NC Datapalooza. No easy effort for sure, but we're gonna kill it! Feedback welcome if anyone feels like we should approach this in a different way.
