### ISSUE TITLE
Update 2017 Prospectus with Civic spark day

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#459]

**Comment by jhibbets** [comment]
Need logo from @smcclenn - please add to 2017  > Sponsor > Logo folder

**Comment by ChrisTheDBA** [comment]
Prospectus updated and ready for review

**Comment by jhibbets** [comment]
I've gone through it and the changes look ed good to me. One thing to note, I change Code for the Triangle to Triangle Code for America to match the meet-up page to avoid any confusion.
