### ISSUE TITLE
Connect Instagram with NC Open Pass Hootsuite account

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#460]

**Comment by jhibbets** [comment]
waiting on correct lastpass to come through

**Comment by jhibbets** [comment]
@ChrisTheDBA  I never got anything for this, can you share the credentials via LastPass? Or did not get in either?

**Comment by ChrisTheDBA** [comment]
Double check. My LP says it is shared with you. I also resent it.

**Comment by jhibbets** [comment]
Looks like Hootsuite limits us to 3 social networks. Otherwise it's $20 / month. I've rather have both twitter accounts and facebook in the same place. Instgram seems more like a day of social postings. We can do a free 30-day trial starting in September if we want and pay for a month in November.
