### ISSUE TITLE
Table covers - what color?

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#473]
Plan is to use the same kind of table covers (from dollar general) as last year. Maybe a different color than the light green last year.

I propose blue (similar to the dark blue t-shirts last year) but will wait until we pick t-shirt colors this year.

**Comment by TaxLadyTracy** [comment]
Green is our color so Green they shall be.

**Comment by dtraleigh** [comment]
Ordered.
