### ISSUE TITLE
Send Sarah Powers call for Lightning Talk

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#475]
Sarah Powers, Executive Director, Office of Raleigh Arts, is interested in doing a lightening talk. Her office is kicking off an Arts & Tech collaborative initiative, so her talk would be mutually beneficial.

**Comment by ChrisTheDBA** [comment]
Sounds interesting. What is her talk about? It will still have to be submitted and weighed against the other submissions.

**Comment by suzanneccnc** [comment]
Do we have an application that we can send her? She has lots of ideas and
experience with the intersection of art/tech/community.

**Comment by jhibbets** [comment]
The Call for speakers is not ready yet.

**Comment by ChrisTheDBA** [comment]
Added note to speaker notes doc

**Comment by suzanneccnc** [comment]
Follow-up email with a link to the form sent!
