### ISSUE TITLE
create call for speaker material

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#477]
need material to send to potential speakers as well as timeline: application deadline, decision date, confirmation date. Do we have material from last year that we can use as a starting point?

**Comment by jhibbets** [comment]
Call for speaker form is here: 
https://docs.google.com/forms/d/e/1FAIpQLSdQmD46kNRdQmhhTUMCr0aLH_13R7yRFlyecIWMCXhJ2Ctedg/viewform

**Comment by jhibbets** [comment]
call for speaker blog post is ready and scheduled to publish on August 15 @ 7am:
http://citycampnc.org/2017/08/15/citycamp-nc-2017-call-for-lightning-talk-speakers/

Committee members can now point to the existing Google Form

**Comment by suzanneccnc** [comment]
Is the idea to wait until blog post goes up to send link to potential speakers?

**Comment by jhibbets** [comment]
You can send the webform to people now. The idea behind the delayed blog
post is to spread out content on the blog. There is a post published this
morning to promote NC Open Pass registation.
