### ISSUE TITLE
[phase 1: august 8th] announce nc open pass early bird reg on twitter

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#479]
Set-up some social media to announce NC Open Pass early bird

**Comment by jhibbets** [comment]
This is going out today to a list of 31 folks. @natalienoel1 should be sending this out in the next 30 minutes

**Comment by jhibbets** [comment]
Strike he previous comment, meant for #480

**Comment by jhibbets** [comment]
You can use this post - http://citycampnc.org/2017/08/14/get-your-2017-nc-open-pass/ or point to NC Open pass site (more direct)
