### ISSUE TITLE
[phase 1: august 4th/7th]  email initial openpass contacts who signed up on google form to let them know about early bird reg *FOR NC OPENPASS*

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#480]
from jason: 
email initial NC Open Pass list of folks to let them know registration is open and they are the first to know

The contacts are here and need to be uploaded to mailchimp: https://docs.google.com/forms/d/1pygO5X-TexMoHcs7Gb_3h_w_0tFe1mtrxqv3bTFmZps/

**Comment by ashumz** [comment]
blocked until #482 is complete

**Comment by ashumz** [comment]
@natalienoel1 let's consider this 'phase 1' registration announcement, exclusive to those interested in openpass. 

since these people specifically signed up for NC Openpass updates, I think we can abstract the citycamp/datapalooza/openpass confusion and tell people what events are included (civic spark day/citycamp/datapalooza) and the pricing for openpass ONLY.

we can also go ahead with announcing the availability of the openpass registration on twitter once that email sends out.

in "phase 2", when we reach out to email *all* citycamp/datapalooza previous attendees, that's when we really need the clarification on pricing table and registration options available on a citycamp registration announcement blog.

@jhibbets does this sound like what you had in mind?

**Comment by jhibbets** [comment]
Yes. Sounds great. Let's do it. The other general announcement can include
other reg details. The idea is to have exclusive registration for nc open
pass for a certain time before other events reg opens up.

**Comment by natalienoel1** [comment]
@ashumz Can we jump on a call early tomorrow? I got into mailchimp but just want to brainstorm with you on what this email should look like and then I can send it out asap tomorrow.

**Comment by jhibbets** [comment]
This is going out today to a list of 31 folks. @natalienoel1 should be sending this out in the next 30 minutes

**Comment by jhibbets** [comment]
Newsletter is out. Good work @natalienoel1
