### ISSUE TITLE
share access to mailchimp through lastpass w marketing team members

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#482]
natalie needs access for mailchimp   through lastpass

make sure ashley's correct email is invited (ashley.mcclelland@ibm.com)   with access to mailchimp as well

**Comment by jhibbets** [comment]
@ashumz @natalienoel1 please confirm you got the share. For whatever reason, this wasn't in the NC Open Pass folder, which is why I missed it last week when I did all this stuff ;)

**Comment by natalienoel1** [comment]
Yes, I got it access! Thank you! @jhibbets

**Comment by natalienoel1** [comment]
Just tried getting on Mailchimp and it says the username doesn't exist.

**Comment by jhibbets** [comment]
@natalienoel1 I had an old password cached on MC, so the first time I tested this, I got the same error you got. If you go to lastpass and click "launch" it should have the correct username in lastpass, and I had to paste in the new passwd. Give that a try and let me know if you can get in.

**Comment by natalienoel1** [comment]
Still not able to access it!

**Comment by natalienoel1** [comment]
@jhibbets It now says the password is incorrect and I'm not sure what the updated one is.

**Comment by jhibbets** [comment]
@natalienoel1 I don't know why its not working for you, so sorry. The password is pretty long and should be 15+ characters.

**Comment by jhibbets** [comment]
@natalienoel1 I literally had to go into LastPass, view the passwd, copy it, and paste it into MailChimp password box in order to log in, but I thought I was having issues because of the cached passwd from last year.

**Comment by ChrisTheDBA** [comment]
My .02. I have two MC logins one is login.mailchimp.com and the other is
just mailchimp.com (both citycampnc). the login.mailchimp does not work the
other does.

Chris Mathews

**Comment by natalienoel1** [comment]
ah I FINALLY got in. Try #100 but it works! @jhibbets @ChrisTheDBA

**Comment by jhibbets** [comment]
I see what happened. We have two mailchimp acocunts. One for Code for Ral and on for Open Pass. When I created the lastpass share for open pass, it copied the credentials for the other one. there were literally two usernames and two passwords on the share. I removed the duplicates so things should be better now.
