### ISSUE TITLE
[phase 2: august 10th] create a pricing table for nc openpass and encompassed events for initial blog post

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#483]

**Comment by ChrisTheDBA** [comment]
On or before Sept 4th
	NC OpenPass		Seperately
	40			                  45 (20+25)
	
After Sept 4th
	NC OpenPass		Seperately
	50			                 55(20+35)

**Comment by jhibbets** [comment]
I don't understand what is needed here. The NC Open Pass prices are listed
on the site. We don't break it down by each event.

**Comment by suzanneccnc** [comment]
There is no good, easy user journey for the ticketing process. On the Marketing call, there was  much confusion stemming from...how many ticketing portals (3: NCOpenPass, CityCampNC, NCDataPalooza), how many ticketing periods (2: Early Bird until Sept. 4, regular thereafter), how many ticket price tiers (3: Students (free), Government Employees (50% discount), Everyone Else (full price)), and how many attendee actions required to complete ticketing process (1 if from CityCampNC or NC DataPalooza  ticketing portals, 2 if from NC OpenPass portal), and finally, no automated notification of way to save if purchaser buys CityCampNC and NC DataPalooza  separately). Look how much space was needed to explain that...not good.

**Comment by carsi** [comment]
Agree with Suzanne.

It is true that NC Open Pass prices are listed, but it is unclear how much
these events cost a la carte and how much of All Things Open is discounted
according to the NC OpenPass website.

Also, there are Early Bird NC Open Pass Prices even though by September 4,
Civic Spark Day will be over so there will be even less value in NC Open
Pass.

As Ashley mentioned on the Marketing call, it seems like a lot of racket to
get maybe $5 off all of the events, and risk being excluded from these
events (like Suzanne mentioned happened to her last year) if you paid for
the NC Open Pass on eventbrite and did not know you needed to re-register
for CityCamp NC, NC DataPalooza, All Things Open, and Civic Spark Day with
a special code.

Several of these issues may need to wait to be resolved by the New Kind
rebrand, but we should at least communicate clearly *how much each event
costs individually, explain how to get the discount, and link to those
individual eventbrites on the NC OpenPass website.*

**Comment by jhibbets** [comment]
pricing table has been started:
https://docs.google.com/spreadsheets/d/1dsxhEzCRtWbMmyyESuz-cQzzDuh0vnrDiEFVXliskm8/edit#gid=0

I've asked @zachambrose to help with the Datapalooza details (see below) that I started but I am not sure if they are accurate, hence they are italicized int eh doc.

- when do we plan to launch NC Datapalooza stand-alone registration?
- what do we charge? (I seem to remember $35)
- do we have any option like gov't or student rates?

**Comment by jhibbets** [comment]
pricing table has been updated by @zachambrose and is ready for review. We can discuss on tonight's call.
