### ISSUE TITLE
[phase 2: aug 10th] 'registration is open' blog post on citycamp blog

### ISSUE THREAD

**Issue by ashumz** [ncopenpass/NCOpenPass#484]
a few things we need to figure out from today's marketing sync and clarify in a blog post announcing registration:
- pricing table for all events for an initial 'registration is open' blog post (why register for nc open pass vs citycamp by itself vs datapalooza by itself?) 
- where we're headed with unifying these events under a single brand 
- how registration works (register in one place, get coupon code for individual event registrations so you can customize your registration -- eg: tell us which days you're going to citycamp) -- @jhibbets is there any way we can use a single eventbrite for this experience or is it too late at this point? I can look into options once I have LastPass access

**Comment by ashumz** [comment]
blocked until we have clarity on pricing table and registration options - @jhibbets I am happy to work on this with you

**Comment by jhibbets** [comment]
@ashumz re: using one registration, I'm open to creating a better user experience. Last year was a trial run for NC Open Pass. When I created the Eventbright, I tried doing multiple events using the interface, but it seemed even more confusing. Part of me feels like sense we've already started to just keep moving. If there is a better way to do it before we send out mass emails to folks to register, let's figure it out on tonights call.

**Comment by ChrisTheDBA** [comment]
Plus from a logistics standpoint we need headcount for each event and each
day of the events. Also need info on any special dietary needs.

I have talked a few others about the sigh up process from last year and
most like the updates. Of course with we had events spread over more of the
year too.

Chris Mathews

**Comment by jhibbets** [comment]
Pricing table is here: https://docs.google.com/spreadsheets/d/1dsxhEzCRtWbMmyyESuz-cQzzDuh0vnrDiEFVXliskm8/edit#gid=0

**Comment by jhibbets** [comment]
I'm hoping to work on this Monday so we can push out on Tues/Wed

**Comment by jhibbets** [comment]
Done: http://citycampnc.org/2017/08/14/get-your-2017-nc-open-pass/
