### ISSUE TITLE
Lunch - Friday

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#489]
Choose vendor. menu

Moe's - Tacos
Noodles & Co

**Comment by ChrisTheDBA** [comment]
Moe's taco bar has been very popular and reasonably priced.

**Comment by jhibbets** [comment]
Taco bar is awesome. Amardillo Grill might be a good alternative. There
queso is delicious.

**Comment by dtraleigh** [comment]
No need to reinvent every meal. I vote Moe's for Friday lunch.

**Comment by dtraleigh** [comment]
Moe's for Friday lunch.
