### ISSUE TITLE
Ask Nicole Raimundo to judge

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#503]

**Comment by ChrisTheDBA** [comment]
Sent ask letter. She is on vacation and will likely require a followup.

**Comment by ChrisTheDBA** [comment]
Out of town on Sept 30, happy to do either of the other days. Also thinking about speakers for us!

**Comment by zachambrose** [comment]
@ChrisTheDBA  is going to ask about judging at DataPalooza finale.

**Comment by zachambrose** [comment]
Hi, Chris. Any news on Nicole judging at the Finale?

**Comment by ChrisTheDBA** [comment]
I will ping her. got a soft commit.

Chris Mathews

**Comment by zachambrose** [comment]
Nice work @ChrisTheDBA
