### ISSUE TITLE
Stand up banner for event and other events

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#505]

**Comment by carsi** [comment]
Did you need me to design this? It wasn't clear but I'd be happy to do it
if someone can give me size dimensions, information, and dpi.

**Comment by ChrisTheDBA** [comment]
I didn't want assume. :)

Dimensions are 82" tall by 36" wide. I'd like the Code for Raleigh Logo and
NC OpenPass, CityCamp NC, and NC DataPalooza "and maybe "Building Community
for a Better Tomorrow through civic design, technology and data."

high enough dpi to look good at that scale.

You should have the three event logos and I have the CFR logo on my home
computer - I will upload. Let me know about if the format doesn't work for
you and I will reach back to person who designed it.

Chris Mathews

**Comment by jhibbets** [comment]
Serial comma and caps: "Building community for a better tomorrow through
civic design, technology, and data."

**Comment by carsi** [comment]
@ChrisTheDBA @jhibbets OK

**Comment by ChrisTheDBA** [comment]
I've uploaded the CFR logos I have to GOogle Drive

**Comment by ChrisTheDBA** [comment]
@carsi  Do you need anything else to begin this?

**Comment by carsi** [comment]
What should be the output for this banner?

**Comment by ChrisTheDBA** [comment]
I would think whichever has the resolution to not look bad when BIG :)

We support a variety of file formats for uploaded designs.
Adobe Acrobat 9 Document (*.pdf) (recommended)
Adobe Illustrator CS3 Artwork (*.ai) (recommended)
Adobe Photoshop CS3 Image (*.psd) (recommended)
Bitmap Image (*.bmp)
GIF Image (*.gif)
JPEG Image (*.jpg,*.jpeg)
Microsoft PowerPoint 2010 Document (*.ppt)
Microsoft Word 2010 Document (*.doc)
PCX Image (*.pcx)
PICT Image (*.pic,*.pict,*.pct)
PNG Image (*.png)
PostScript Document (*.ps)
TIFF Image (*.tif,*.tiff)

**Comment by carsi** [comment]
Resolution is different from file output. Thanks!

**Comment by carsi** [comment]
Here are three options:
<img width="1155" alt="screen shot 2017-08-15 at 6 21 30 pm" src="https://user-images.githubusercontent.com/3422850/29339113-bc27dda6-81e6-11e7-8eb9-8a5edb12145b.png">

**Comment by ChrisTheDBA** [comment]
I had wanted the logos and Code for Raleigh bigger and above.I the middle
and then the left.I guess I am looking for a Code for Raleigh with the
events secondary and since civic spark is durham not include that

Chris Mathews

**Comment by jhibbets** [comment]
I like the middle one too!

**Comment by carsi** [comment]
Each logo is already at least 24 inches wide so we should not make them bigger so there is enough space between the logos.

Also, this is for NC Open Pass, right? If so, NC Open Pass should be the dominant logo and Code for Raleigh secondary. Civic Spark Day is part of NC Open Pass, Raleigh or not. 

On ncopenpass.com, there is a blurb at the bottom that reads "NC Open Pass is a partnership between Code for Cary, Code for Durham, Code for Raleigh, and NC DataPalooza." Is this still accurate? If so, should we include Code for Cary and Code for Durham as well?

**Comment by ChrisTheDBA** [comment]
No, I have been talking all this time about a Code for Raleigh banner, Similar to the one I showed that Code for Greensboro has. Sorry about the confusion.

**Comment by carsi** [comment]
What is the use case for this banner?

**Comment by ChrisTheDBA** [comment]
Don't mean this to be snarky, but...let people know who we are when we are
at events. Some specifics are Brigade Congress in Philly, ATO, Creative
Mornings, Raleigh Chamber, Innovate Raleigh,

Chris Mathews

**Comment by jhibbets** [comment]
I'll add that it's Chris, Tracy, and sometime me at the table/booth. So
it's code for raleigh specific,  hence the ask for specific logos.

**Comment by ChrisTheDBA** [comment]
ordered
