### ISSUE TITLE
Speaker request: Miguel A. Gamino Jr. NYC Chief Technology Officer

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#509]

**Comment by ChrisTheDBA** [comment]
Bill G knows him and will introduce if we want.

**Comment by jhibbets** [comment]
I pinged him on Twitter but could use his email. And intro from Bill to me
would be perfect too.

**Comment by ChrisTheDBA** [comment]
We have a conversation started on LI

**Comment by jhibbets** [comment]
Details have been sent to Miguel and his team

**Comment by jhibbets** [comment]
Thank you for the opportunity, but unfortunately, Miguel has a conflict on the 29th.
