### ISSUE TITLE
Speaker request: Smart city panel ideas

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#511]

**Comment by jhibbets** [comment]
@ChrisTheDBA looks like @reidserozi isn't interested in responding, can  you help out here and get some thoughts from Bill Greeves?

**Comment by ChrisTheDBA** [comment]
Terry Yates is the TOC contact for this. Will call on Wednesday.

Chris Mathews

**Comment by reidserozi** [comment]
Wait! What? Not interested in responding to what?

**Comment by ChrisTheDBA** [comment]
Can you help corral the participants or make intros for us. To some of the people you are working with. From the email we know Jim and Deante' but others  - think regional or statewide.
