### ISSUE TITLE
Import CityCamp 2013 and 2015 attendees

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#517]
@natalienoel1 can you get these details before we send the email ou ton Monday:

1) Export CityCamp NC 2013 list from EventBright into CityCamp NC News
2) Export CityCamp NC 2015 list from EventBright into CityCamp NC News

Ref: https://docs.google.com/document/d/1WoNiCYgh_zugp4uCRlH1sy-Lw19Ym2kAWfFlzHknNNA/edit#heading=h.sksbp47zznkk

**Comment by natalienoel1** [comment]
@jhibbets Done!
