### ISSUE TITLE
Onboard Lory Mills

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#524]
this is a repeat of issue added today, but I inadvertently "closed" then "archived" it. So.

Lory would like to help with NC Open Pass, especially with the Data and Challenges work. 

I have added her info to the "Organizers Contact Info" spreadsheet

**Comment by zachambrose** [comment]
I added her to the Google Group.

**Comment by zachambrose** [comment]
And Bill's  Committee on the project plan
