### ISSUE TITLE
Test FB live with Mevo

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#528]
Let me know if you'd like to be a part of this.

**Comment by aikimark** [comment]
I contacted my A/V guy, Eric Leavy, and he wasn't familiar with Mevo.  He did say that audio was usually the biggest determinant of content quality (streaming or recorded).

**Comment by ChrisTheDBA** [comment]
We have two options on the table for Thursday.

1) Trophy will donate a 1/6 keg(40 pints) we setup and pour and still need
to find 3 more kegs

2) Brice's 4 x 1/6 kegs for $320($80/keg), they setup and provide
cicerone(s).

For Friday we will probably want to stick with Little City to support the
area with the fire damage.

Chris Mathews

**Comment by ChrisTheDBA** [comment]
Let me know what I need to do!!!

**Comment by dtraleigh** [comment]
What is the Facebook login? Would it be weird to test it there or should we
use a personal account?

**Comment by ChrisTheDBA** [comment]
I will need to figure that out

Chris Mathews

**Comment by jhibbets** [comment]
Added you as an editor to the FB page.

**Comment by dtraleigh** [comment]
I'm planning to drop by HQ Raleigh next week, Friday the 25th around 3pm to do an on-site test of the Mevo. If anyone is nearby and wants to hang out, come on down. If anyone can be made available virtually to watch the test stream and offer live feedback (so I can test settings and such) that would be helpful also. 

Let's say we get there at 3, kick off the stream around 3:15 and test it for 15-30 minutes depending. More details later.
