### ISSUE TITLE
Draft recap of meeting with Mayor

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#529]
For posting on Friday, August 18

**Comment by jhibbets** [comment]
Draft is done, once @zachambrose reviews (please add anything I missed), I'll add this to wordpress and schedule: https://docs.google.com/document/d/1-0AW4Gp-PAlErChQS4wy28xUFRkkvF3qkA1SLnw3ccs/edit

**Comment by jhibbets** [comment]
FYI: @ChrisTheDBA has reviewed

**Comment by zachambrose** [comment]
I think that's got it.
