### ISSUE TITLE
Promote call for speaker

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#535]
Please promote Call for speakers via newsletter and social media. Blog post will publish on Aug 15 at 7 am.

http://citycampnc.org/2017/08/15/citycamp-nc-2017-call-for-lightning-talk-speakers/

**Comment by wildca01t** [comment]
@jhibbets = Brasco has a company newsletter going out mid-late week. I'll add in promo/call for speaker. Note: Please check this lightning talk speaker weblink on Citycamp's site. It said broken twice. 
Thx.

**Comment by jhibbets** [comment]
+1 on newsletter, thanks.

The post isn't live yet, you need to be logged in to view it. It will
publish tomorrow morning.

**Comment by jhibbets** [comment]
@ashumz @natalienoel1 Reminder to get some social media set up for this - time sensitive (Deadline is Aug 28)
