### ISSUE TITLE
Check and update sponsorship tiers on websites

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#541]

**Comment by zachambrose** [comment]
@jhibbets For NC Open Pass, Wake Econ Dev isn't onboard as a sponsor, Raleigh Econ Dev should be Gold

**Comment by zachambrose** [comment]
@ChrisTheDBA  For City Camp, Raleigh Econ Dev should be gold,  HQ Raleigh is  Gold, Data.world is silver.

**Comment by zachambrose** [comment]
@wildca01t Neomonde has agreed to sponsor yet.  Data.world is silver.

**Comment by ChrisTheDBA** [comment]
moved HQ to gold and still don't have data.world. Raleigh is at platinum for donation plus in-kind and to apologize for confusion at last years event

**Comment by zachambrose** [comment]
I updated Raleigh to Platinum in the sponsorship sheet.  @wildca01t  can you change Raleigh to Platinum on the DataPalooza website?

**Comment by zachambrose** [comment]
Data.world's logo is in the folder and they can be added as a silver sponsor for DataPalooza and City Camp.

**Comment by jhibbets** [comment]
NC Open Pass is updated with all these items. @wildca01t please close this once you finish your updates.
