### ISSUE TITLE
Brewery meetup Saturday

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#543]
Looks like Saturday afternoon has been proposed as a date. Here is a Doodle with proposed times... https://doodle.com/poll/r7dhv2yuexwimxn5

**Comment by ChrisTheDBA** [comment]
1822 Garner Station Blvd, Raleigh, NC 27603

**Comment by dtraleigh** [comment]
Does Brice's have Wifi? I can bring the Mevo.

**Comment by TaxLadyTracy** [comment]
I believe they do and we also have a mifi that can be used.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Leo Suarez <notifications@github.com> Date: 8/16/17  9:32 AM  (GMT-05:00) To: codeforraleigh/NCOpenPass <NCOpenPass@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [codeforraleigh/NCOpenPass] Brewery meetup Saturday (#543) 
Does Brice's have Wifi? I can bring the Mevo.



On Mon, Aug 14, 2017 at 6:34 PM, Chris Mathews <notifications@github.com>

wrote:

**Comment by ChrisTheDBA** [comment]
Going to call Doodle closed. We have three attending I say we meet at 2-2:30 on Saturday at Brices to sample the beer and check out the Mevo. All are still welcome to attend.
