### ISSUE TITLE
Update menu>speakers to include 2017 speakers

### ISSUE THREAD

**Issue by snewt-n** [ncopenpass/NCOpenPass#548]
blocked by getting 2017 speakers

**Comment by jhibbets** [comment]
I don't understand what update menu means.

**Comment by snewt-n** [comment]
Oh! I should've been more clear. On the website, the menus from the banner/header/top don't currently include 2017. See image:
![speaker menu.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59887ffd7b5cff001f24a278/125516c66e82c728ace21e0d46fb849f228986bbcfe4ba4db11fbcd6395428792c07b7692ac7b67ebb4728505f5e4da945585e43a8ac8929f7e73577830a19f1c32f0e2a92624cf5f2d75dad0ba8228d4584b3bc894bc9ef3927ee8c894c2c53.png)

**Comment by ChrisTheDBA** [comment]
The headings link to the current year pages . maybe it would be clearer to add "2017" to those pages? I updated the site. How does it look?

**Comment by jhibbets** [comment]
We usually add 2017 when we back date the website

**Comment by jhibbets** [comment]
Closing: Adding a 2017  menu will cause duplicate pages ad the main page is the current year.
