### ISSUE TITLE
Ask Natalie about developing social media plan

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#555]

**Comment by ChrisTheDBA** [comment]
please don't forget our sponsors/partners! :)

**Comment by jhibbets** [comment]
Note: we can set this up for the three remaining events, CityCamp, ATO, and
DataPalooza and have everything scheduled.
Jason

**Comment by wildca01t** [comment]
I reached out to Natalie Noel at HQ, just waiting for a response. Natalie handles all of HQs social media.
