### ISSUE TITLE
Access to Eventbrite for Chris M

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#557]
Need for getting the at event logistics planned out

**Comment by ChrisTheDBA** [comment]
my password is bad.

**Comment by jhibbets** [comment]
reshared

**Comment by jhibbets** [comment]
Close if it worked, otherwise I'll investigate more

**Comment by ChrisTheDBA** [comment]
It didn't work. Taking offline
