### ISSUE TITLE
Get keynote details from Stephen Larrick

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#560]
Speaker/judge form sent on 8/18
Should get w/o 8/21
Will promote w/o 8/28

**Comment by ChrisTheDBA** [comment]
Im stupid what does w/o mean?

Chris Mathews

**Comment by suzanneccnc** [comment]
What speaker/judge form?!?!? Need to get that to Ralph Perrine...

**Comment by jhibbets** [comment]
@christhedba week of
@suzanneccnc in the speaker folder ;) -
https://docs.google.com/forms/d/1IQl25hlxP9Nxht2SetBy3kHnAVhrummL28NkSwuDUv4/edit?usp=drive_web
