### ISSUE TITLE
List of all blog posts on WordPress

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#562]
I'm trying to figure out how to get a public view of all our blog posts. When I go here: http://citycampnc.org/latest-news/ some of the newer posts aren't showing up. I believe it's because that page is bringing in posts that are tagged Latest News 2016. So I'm think we should:
- show all blog posts on that page
or
- merge latest news and latest news 2016 tags together and using latest news as a tag that all posts should have
or
your idea

I think having  latest news and latest news 2016 tags is confusing.

**Comment by ChrisTheDBA** [comment]
As discussed, do we need to just change the tags on develop a separate.

**Comment by ChrisTheDBA** [comment]
Going to tackle a blog page.
