### ISSUE TITLE
Confirm Coffee if CoM

### ISSUE THREAD

**Issue by TaxLadyTracy** [ncopenpass/NCOpenPass#572]
Make sure they order extra cups and beans the week before our event.

**Comment by dtraleigh** [comment]
Asked. Waiting for reply.

**Comment by dtraleigh** [comment]
Here is the coffee statement.

"As for coffee, we will have coffee grounds and the carafes, but ya’ll will need to bring everything else (cups, stirrers, creamer, sugar, etc). "

**Comment by dtraleigh** [comment]
@TaxLadyTracy Did you see this?

**Comment by TaxLadyTracy** [comment]
No I did not.  But you have assured me that we are good :)

**Comment by TaxLadyTracy** [comment]
Ok, I will have to go buy all of this.  Good thing I like shopping right :)

**Comment by dtraleigh** [comment]
oh I didn't know that! I'll send you more things to buy in a few!!!! ;)

**Comment by TaxLadyTracy** [comment]
Get me the list now!!  You know how I am about deadlines.  You may want to email me directly though because I get lost on this board.

**Comment by TaxLadyTracy** [comment]
I am going to leverage my "hook-ups" for some of this stuff so we don't waste money.

**Comment by dtraleigh** [comment]
I was joking. Just coffee supplies please. If you have that on your list, I
can close this card.

**Comment by dtraleigh** [comment]
Were coffee items purchased?
