### ISSUE TITLE
Get Ipreo logo and twitter handle

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#576]

**Comment by dtraleigh** [comment]
https://twitter.com/InsideIpreo
![Ipreo-logo.gif](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5564f79571c5690d009928d2/125516c66e82c728ace21e0d46c18488268dcea580eeb001e81fe086264c22703d46f96925d3e72dec132b505c5a4aac405f0b11fcfbd87aafb13526984019af80330b2b9b645bf9fa9015ad00b22a8a4a85b3ba8f4ac9ed3e2cef8d9d02.gif)

**Comment by dtraleigh** [comment]
@zachambrose Is this good?

**Comment by zachambrose** [comment]
Perfect.  @wildca01t Can you add to the DataPalooza sponsor page?
