### ISSUE TITLE
Remove ESRI from website sponsorship section

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#577]

**Comment by ChrisTheDBA** [comment]
Removed from CityCamp site

Chris Mathews

**Comment by jhibbets** [comment]
NC Open pass updated. Note: I just commented that HTML out for now.

**Comment by wildca01t** [comment]
Updated on NC Datapalooza - ESRI removed. @zachambrose

**Comment by ChrisTheDBA** [comment]
Looks like we have removed. but we can't untweet.
