### ISSUE TITLE
Build EventBrite for CityCamp NC registration

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#578]
Note: I'm going to move (copy) this over to the NC DataPalooza EB to have everything in one location

**Comment by ChrisTheDBA** [comment]
Please include t-shirt question and food alergies

Also it would be nice to have demographics(optional of course) about the
people registering such as occupation, industry

Chris Mathews

**Comment by jhibbets** [comment]
Draft eventbright created, both of the questions are part of reg.
