### ISSUE TITLE
Order Saturday Lunch - Manhattan Cafe

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#585]

**Comment by dtraleigh** [comment]
Manhattan Cafe is booked. 15 boxed salads and 45 premium sandwiches. They will deliver at 11:30. 

By Thursday (9-28) we need to tell them how many veggie options we need, if any.

**Comment by ChrisTheDBA** [comment]
I thought we increased to 80 lunches. If we didn't...my bad. Can we still do 15 salad/10 veggie sandwich and 55 premium w/ meat?

**Comment by dtraleigh** [comment]
I may have missed that. Either way, plenty of time to increase it. I will
do that tomorrow.
