### ISSUE TITLE
pay Brice's

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#589]
Meet up with Kris and reserve their services

**Comment by aikimark** [comment]
When are you planning to go over there?

**Comment by ChrisTheDBA** [comment]
Don't know. I plan on going over giving him my CC, signing the agreement
and leaving. Going to be pop in and pop out.

Chris Mathews

**Comment by aikimark** [comment]
When is he usually there?

**Comment by ChrisTheDBA** [comment]
I don't know. he is in and out.

**Comment by ChrisTheDBA** [comment]
Put down 50%. contact is David
