### ISSUE TITLE
Archive CityCamp NC 2015 items

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#59]

**Comment by ChrisTheDBA** [comment]
I've got sponsors/press moved to a sub -page

**Comment by jhibbets** [comment]
Still need to do:
http://citycampnc.org/venue/
http://citycampnc.org/speakers/
http://citycampnc.org/hackathon/

**Comment by suzanneccnc** [comment]
So sorry to miss tonight. I'm sharing my car with my teen daughter this
week and the schedule just didn't work out tonight. I'm worried that we are
getting into crunch time for some of our marketing efforts. I'll do my best
to catch up this week.
Best regards,
Suzanne
