### ISSUE TITLE
request quote from compost now

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#590]
request quote for composting, recycling services, provision of products (plates, cups, napkins, utensils). explore in-kind donation sponsorship.

**Comment by ChrisTheDBA** [comment]
Alternately, if the cost is high. Can we get them elsewhere/

**Comment by suzanneccnc** [comment]
Partial quote received. Logistically, their service will not work this year as they cannot pick-up at end of day Friday or Saturday. Here is part of the quote:
[Suzanne Beaumont_Compostables Pricing - 9.1.17.pdf](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57156c76d8213d0e008bf6ba/125516c66e82c728ace21e0d46db8180228c8daccfcbba42b150ff9a3d79047c2414ac386484e124ba513b311d061df51f0f4f59ecf0972ab8b73b62964e4baf8e370a27822f1bbebd844bea02bb208a4c80b2bc8b4b94bd3d27b6da8648374817049bbd0c6bf4c6169112a309f34747a51b3c62e376327a439c177524696122b9b1.pdf)
![65 gal cart.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57156c76d8213d0e008bf6ba/125516c66e82c728ace21e0d46bec1da24838fe98ce8ad57e611b2843b492d762a10e17132d0b52cba112a515e5c4ba841595810a9f98b7af7bf3b79dc4e17ff933c0120996048e6edc00db513bb28814e80b6b88c48c8e13c2de78e8f5d73.JPG)
![ZeroHero.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57156c76d8213d0e008bf6ba/125516c66e82c728ace21e0d46d291882caa86bb80abf301b44fff9e2c4533317346f67d7480b079ef1328545b5f4fab150d5f46ada8802cafe02e6c981e5ab38532022d8c6853beb2901eb80bbb258b4b83b2b4834ec6e13d22f5c6.JPG)
