### ISSUE TITLE
Invite Town of Wake Forest officials

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#595]
all emails @wakeforestnc.gov
Mayor Vivan Jones mayor@
CIO, Tom LaBarge tlabarge@
Town Manager, Kip Padgett kpadgett@
Town Clerk, Deeda Harris dharris@
Commissioner, Greg Harrington gregharrington@
Commissioner, Brian Pate bpate@
Commissioner, Margaret Stinnett mstinnett@
Commissioner, Jim Thompson jthompson@
Dir. Downtown Dev, Lisa Hayes, lhayes@
Dir. Econ. Dev, Jason Cannon, jcannon@

In addition to email communication, personal invitation at Board of Commissioners meeting (Sept. 5, Sept. 19) is advisable.

**Comment by jhibbets** [comment]
Template is ready: https://docs.google.com/document/d/1h6v2nV0gQF5-RPSnEm9jm4qqHNrZhV-3hczgAIsZvfE/edit
