### ISSUE TITLE
recycling at HQ?

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#599]
Does HQ provide recycling containers for us? If not,  can we provide our own?

**Comment by dtraleigh** [comment]
They do not. Let me get in touch with them this week and see how we could
do this.

**Comment by dtraleigh** [comment]
HQ can collect compostable materials for us. I think we are close to being
100% for Thursday night.

Compostable items already planned are food and pizza boxes so if we make
sure that our plates and cutlery are compostable, we would be good to go.

The other side is the beer cups. Is Brice's providing or are we?

**Comment by TaxLadyTracy** [comment]
We will provide Red Solo Cups :)

**Comment by TaxLadyTracy** [comment]
Donatos provides all the plates/napkins for dinner not sure if they are compostable but they are FREE or included in the price we pay.

**Comment by dtraleigh** [comment]
12 oz. compostable cups can be had for $10 per 50. In Raleigh, the solo cups (plastic #6) is not accepted by their recycling so these would go in the trash.

Can we vote on this?

**Comment by ChrisTheDBA** [comment]
Can you send a link w/ picture? Remember the reason we have red solo cups
because most people drank water from disposable bottles and not fill cups.
Attendee behavior is just that.

If we buy these cups this year we could probably use them for a couple of
years. that's not necessarily a bad thing.

Chris Mathews

**Comment by carsi** [comment]
Attendees drink out of what you give them. If we get compostable cups for beers, they will drink out of the compostable cups. For a small amount of money, we can be good stewards of the earth and set a good example.

**Comment by TaxLadyTracy** [comment]
I will double check with Brice's to see if they are bringing cups, I know they have certain sizes for the pouring.  We have lots of leftover cups from last year so it would be a $0 expense if they are not provided.  I just checked and they are #6

**Comment by dtraleigh** [comment]
This is what I'm proposing.

Repurpose 100% Compostable Plant-Based Clear Cold Cup, 12-ounce  (50 Count)
https://www.amazon.com/dp/B00NNR3S3S/ref=cm_sw_r_cp_apa_GDFPzbA11G6ME

Actually, my opinion is to first use what we have THEN go green. The damage
is done if we already have plastic cups. (Just my opinion)

**Comment by ChrisTheDBA** [comment]
Those look a lot better than what I was looking at. Thanks Leo & Amazon.

I will also note that my other comment was about Nash Hall where the only
water supply is from the mop sink. We used bottle water and water brought
from home.

Chris Mathews

**Comment by dtraleigh** [comment]
Nash Hall is an entirely different dynamic I think. Can we break that off
on another waffle card?

Let's keep this thread on Thursday night's event at HQ, which I think we
can make it 100% compostable.

If donato's provides paper plates, napkins, those are compostable. Any
plastic cutlery is typically not.

**Comment by suzanneccnc** [comment]
I like making a move to 100% compostable (/recyclable) for the Thurs night
event. It's the smallest event duration so easier to be successful. My
2-cents. Thanks for the research Leo!

**Comment by carsi** [comment]
Agree with @suzanneccnc, it will be cool to do 100% compostable for at least one part of the event. We might need to explain on Thursday night to guests what is compostable (everything?!) but it will be worth the education for some. Thanks @dtraleigh and @ChrisTheDBA!

**Comment by dtraleigh** [comment]
I've ordered the compostable cups. We'll use them Thursday night. With Donato's and the pizza boxes being naturally compostable, we should be pretty close to 100% compostable all night. Just discourage plastic forks and knives and we should be there!

I'm closing this item

**Comment by suzanneccnc** [comment]
Awesome! Remind me, does HQ do the composting or will we need to collect
and dispose of it?

**Comment by dtraleigh** [comment]
HQ can collect. They subscribe to Compost Now so they will eventually take
everything away.
