### ISSUE TITLE
Final payment to Brice's

### ISSUE THREAD

**Issue by TaxLadyTracy** [ncopenpass/NCOpenPass#613]
9/27 make final payment to Brice's.

**Comment by aikimark** [comment]
I went by Brice's on Sunday and talked with David.  The current list will be:
* Hoppy Wheeet
* Breakfast Stout
* Belgian Tripel
* That Boy Belgian Pale Ale

I will return to Brice's in a couple of weeks to taste the Pale Ale.

Note: the Rosemary & Peach Saison will NOT be available for our event :-(
