### ISSUE TITLE
remove Saturday's recycling/compostable material

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#636]
All material must be removed from Nash Hall at the  end of each day.

**Comment by suzanneccnc** [comment]
City of Raleigh does not accept compostable material. However, Compost Now offers the following: (from Nick at Compost Now) "We're not located very far from the event (Boylan Heights) so you all can drop off the compostables at our office at the end of each day! We would leave out collection containers where yourself, or someone else, could leave them outside. Based on your estimated volumes the cost of this service would be $60. "  Do we have the budget for this? @ChrisTheDBA  @jhibbets  @zachambrose

**Comment by ChrisTheDBA** [comment]
$60 is not a problem, but the price list of the utensils, cups and plates
was about $800. That is would be pushing it. Can you go with offering the
recycling this year and looking at adding the composting next year?

Chris Mathews

**Comment by ChrisTheDBA** [comment]
Sent email asking lunch vendors whether the supplies they provide are
compostable.

Chris Mathews

**Comment by suzanneccnc** [comment]
done and done
