### ISSUE TITLE
NC Re-Entry project blog post

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#641]
Natalie to reach out to Jason Marshall for NC Re-Entry project blog post to highlight that for featured project on Saturday (in addition to open data challenges)

**Comment by jhibbets** [comment]
@marshallj did this ever materialize?

**Comment by marshallj** [comment]
We have this if it is relevant: http://blog.codeforgreensboro.org/progress-learning-at-the-nc-reentry-resources-hub-hack-day/
