### ISSUE TITLE
Create flyer to promote events

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#650]
No budget for printing these, but folks could grab the file off of drive and print / distribute in their office or other places

**Comment by carsi** [comment]
We can also do a digital release of this on social media. What kind of content do you want on these? I assume this is for NC Open Pass in general.

**Comment by carsi** [comment]
<img width="884" alt="screen shot 2017-08-30 at 5 14 50 pm" src="https://user-images.githubusercontent.com/3422850/29895352-cde40058-8da6-11e7-9968-184dcef25eab.png">
I took some content from both websites. I also made a CityCamp NC poster in case that is what you really meant @jhibbets

I might not be able to get to revisions until next week but this is a start. If anyone wants to build on top of it I can add the file to Drive (or you can start over).

**Comment by snewt-n** [comment]
Thank you, Carsi! 

I thought maybe one which kind of explained what we're about, too? 

https://drive.google.com/open?id=0B3qfKOo1GXIGQWR5ajNZYXJ6Q2s

**Comment by carsi** [comment]
@snewt-n This is a really cool idea! Maybe we can separate the Q&A out to be single questions/answers and release them on social media or the blog to be more easily consumable! I can create a template for this later today if that sounds good. :)

**Comment by snewt-n** [comment]
We can do that, certainly! That sounds also like a cool thing. 

I wanted a flyer to get the demographic of people who are missed by our social media - who are curious and may want to help but aren't following us. So a full page printed item. If this isn't it, can someone help me shape it into something more like they were thinking, so that I can print out a few (less than 30) and put them in relevant places?

**Comment by carsi** [comment]
I can do a graphics printer-friendly version today with minor revisions so
you can print them out and distribute in relevant places.

**Comment by dtraleigh** [comment]
This would be great as I wanted to put some around my office.

**Comment by carsi** [comment]
https://drive.google.com/drive/u/0/folders/0BwjOr-60lG0lRHpZWjRsZTMzenc
I added the schedule information to give people more of an idea of when they want to show up if they don't want to go to the whole unconference, and it's now in black and white so most people can print it without using too much ink. 

@snewt-n I tried to keep as much of the information you provided! The dialogue provided a friendly tone, which I thought was nice. :) Shortened and reformatted a few things.

**Comment by snewt-n** [comment]
YES! Thank you @carsi it's great. It's really @suzanneccnc's language, I borrowed heavily from her press release to make it. Should we move this to closed?

**Comment by ChrisTheDBA** [comment]
Can we remove the part about registering for ncopenpass.com and just drive registration to citycampnc.org for now.

**Comment by carsi** [comment]
@ChrisTheDBA 👍 Done and reuploaded on Drive as the same file name

**Comment by ChrisTheDBA** [comment]
@carsi Looks great, thanks

@all is there a plan for distributing these?

**Comment by snewt-n** [comment]
I was planning to print about 25 and some pins, put them on bulletin boards at parks & breweries around, but not sure anyone else's game plan

**Comment by jhibbets** [comment]
I distributed in Red Hat Tower today.
