### ISSUE TITLE
Thank you message for our partners

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#666]
In the past, we have done thank you notes to each sponsor. Very individualized. Nice.

I have come across a couple of takes on this this we can consider.

1) Put all logos on an 11x14 sheet of paper and get all participants to sign it.

2) Take a group photo with logo posters and send those to partners

**Comment by snewt-n** [comment]
I really like the idea of signed by participants. Group photo could be a good -they can frame this- thing, if they want it to be. Do we have participants sign a photo release on sign up? If not, we should stick to signed logo paper I think?

**Comment by ChrisTheDBA** [comment]
I don't know we have ever gotten a written release but we have been using pictures from the events for the past 7 years. 

@snewt-n can you take a crack at adding that as a general "by attending this event, you give the organizers, blah. blah, blah" or do figure out if we need a more formal release.
You open the can, so you have first crack at the worms. :)

**Comment by snewt-n** [comment]
Happily!

**Comment by ChrisTheDBA** [comment]
ATO has this covered under their terms and CoC. https://allthingsopen.org/code-of-conduct/
