### ISSUE TITLE
Add smart cities panel to speaker page

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#669]
Waiting to finalize speakers

**Comment by ChrisTheDBA** [comment]
Waiting on one more confirmation.

Chris Mathews

**Comment by ChrisTheDBA** [comment]
Sent request for speaker info  and head shot 9/7.

**Comment by jhibbets** [comment]
Just checking, you sent them to our speaker form?

**Comment by ChrisTheDBA** [comment]
Yes

Chris Mathews

**Comment by ChrisTheDBA** [comment]
Everyone except for greeves. squirrel!

**Comment by jhibbets** [comment]
@ChrisTheDBA can we grab bill's profile from previous years?

**Comment by ChrisTheDBA** [comment]
I have a meeting with him in the morning I will get it.

Chris Mathews

**Comment by ChrisTheDBA** [comment]
All info is on. Have at it.

**Comment by ChrisTheDBA** [comment]
I added the panel and redid the page with the CMS. Let me know

**Comment by jhibbets** [comment]
Do we have all the their twitter handles? (please do not use page builder for the speaker page)

**Comment by jhibbets** [comment]
Thanks @ChrisTheDBA
