### ISSUE TITLE
Triangle CfA promo

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#672]
Natalie - please add this to the marketing plan so we remember to do this in future years

**Comment by jhibbets** [comment]
Sent to meet-up group members on 9/6

**Comment by ChrisTheDBA** [comment]
@jhibbets Did you setup a meetup or send an e-mail to the mailing list?

Chris Mathews

**Comment by jhibbets** [comment]
Email to the mailing list. I can set-up an event meet-up too like we've
done in the past.
