### ISSUE TITLE
Approve, publish, and send out press release

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#689]
Draft is here: http://citycampnc.org/?p=2935&preview=true

**Comment by natalienoel1** [comment]
@ChrisTheDBA Can you give me more information so I can tweet about this?

**Comment by natalienoel1** [comment]
@jhibbets I am not able to see the draft

**Comment by jhibbets** [comment]
@natalienoel1 this was published today http://citycampnc.org/2017/09/25/seventh-annual-citycamp-nc-civic-technology-unconference/
