### ISSUE TITLE
Add food options to logistics sheet

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#690]
...or tell me where to find it without sifting through waffle cards

I'm trying to build out the schedule, please add the catering and high level menu so I can add to the webpage

https://docs.google.com/spreadsheets/d/156IMrwWhpbRWy-TSvwplt6DNpCebgT7oV5MXU6iaa6o/edit#gid=4

**Comment by dtraleigh** [comment]
Added.
