### ISSUE TITLE
Update logistics schedule

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#691]
https://docs.google.com/spreadsheets/d/156IMrwWhpbRWy-TSvwplt6DNpCebgT7oV5MXU6iaa6o/edit#gid=13

**Comment by jhibbets** [comment]
FYI @dtraleigh made some update here, review, update and close the ticket when you're done

**Comment by dtraleigh** [comment]
Added more clarity to the schedule.
