### ISSUE TITLE
Need DataPalooza team forms and judging criteria

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#694]
I need links to the:
Team submission form
Open data competition judging criteria

to update the schedule page

**Comment by bilscanlon** [comment]
Here is the link to the one pager for teams to prepare for ATO:
https://docs.google.com/document/d/1-lveBlkwKyjfF8butl_c4BU9pxvnzetX9UEhOzYv1Vo/edit?usp=sharing

**Comment by bilscanlon** [comment]
I'll have the other drafts ready for review before the meeting.

**Comment by bilscanlon** [comment]
Initial team submission form.  This needs some additional information based on updated prize information and I wanted to confirm the locations but the main substance is ready:
https://docs.google.com/document/d/1fuzhNgnuPEYOfmCjCrs0eQfAr-rS1-wQDTCgBBsgSz4/edit?usp=sharing

**Comment by bilscanlon** [comment]
Updated judging criteria.  I will send to data team for review and we can finalize it with planning team:
https://docs.google.com/document/d/1gXoWZXESjLM5lvBniRPrYzHLoY5G5pmAug-yLNuoIqQ/edit?usp=sharing

**Comment by zachambrose** [comment]
Thanks, Bill.
