### ISSUE TITLE
Schedule change requests

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#695]
Please submit your schedule change requests to this issue (planners only)

View: http://citycampnc.org/schedule/

**Comment by ChrisTheDBA** [comment]
Change breakfast to pastries and fruit. Same for Saturday morning.

**Comment by jhibbets** [comment]
Breakfast text updated

**Comment by jhibbets** [comment]
@zachambrose intro to open data added 10:10-10:15

**Comment by jhibbets** [comment]
@dtraleigh Added to schedule (Friday) - 7:00pm – 8:00pm — Networking at Tobacco Road Sports Cafe, 505 W Jones St, Raleigh, NC 27603

**Comment by ChrisTheDBA** [comment]
@jhibbets @dtraleigh We actually have Google Fiber space to until 8 PM per Tia.

**Comment by zachambrose** [comment]
Sounds good for open data.  @bilscanlon do you want me to do anything for the presentation or do you have it?

**Comment by bilscanlon** [comment]
Thanks Zach.  I think I can do it solo since it is only 15 minutes but I'd appreciate your input into what to cover.  I'll put out a draft of the presentation / talking points at some point this week to get input.

**Comment by dtraleigh** [comment]
For the after party at Google Fiber, how about we schedule it from
5:30-7:30, with someone thanking everyone at 7:30, encouraging them to keep
things going across the street at Tobacco Road, and the vendors will start
packing up. We should then be out of there before 8pm.

**Comment by jhibbets** [comment]
Schedule is updated: http://citycampnc.org/2016/09/23/friday-september-23-unconference-schedule-the-grid/
@dtraleigh networking social times updated
@bilscanlon can you cover that in 10 minutes from 10:10-10:20?

**Comment by dtraleigh** [comment]
Looks good. Thanks.
