### ISSUE TITLE
Add Google Fiber networking event promtion to CityCamp NC blog

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#703]
Working on getting this from Tia.

**Comment by jhibbets** [comment]
@natalienoel1 do we have a content schedule and / or when could I schedule this if I get it by Wednesday

**Comment by jhibbets** [comment]
We are not going to get this, so I made a meet-up instead.

**Comment by natalienoel1** [comment]
okay got it
