### ISSUE TITLE
Create signage, etc. about recycling etc.

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#707]
Make signs/posters to identify what should go in recycling, compost, trash.

Make signs/posters to show where recycling, compost, and trash containers are within venue.

Create a blurb about our efforts to tilt toward green

**Comment by carsi** [comment]
@suzanneccnc Do you still need help on this?

**Comment by suzanneccnc** [comment]
Hi Carsi,
Yeah, I think I do. My job is eating me alive, so I don't have the extra
cycles that I thought that I would. I can create a PSA to be given each
day, including @HQ, to 1) highlight the go-green effort, 2) direct
attendees to recycle/bin locations, 3) identify which items go where - like
literally hold up a plate/cup/utilsel/napkin/bottle/can and say where it
goes. Then, make signs to attach to each collection bin that show which
items go where.

The PSA can almost be done off-the-cuff, but I'll write something. The bin
signage can be really simple...along the lines of "CityCampNC is going
green!! These things go here:" then staple the items to the sign. Throw on
a CityCampNC logo and call it good. Thoughts?

**Comment by carsi** [comment]
Sounds good Suzanne. Sorry to hear about your job situation. If you write
some copy, I can create the signs? Do you have access to a printer once I
am doing making them?

**Comment by ChrisTheDBA** [comment]
Thanks all the major signage has gone to the printers. We'll need to print
these locally.

Chris Mathews

**Comment by carsi** [comment]
These can be letter size and printed wherever someone has access to a
regular printer. I do not have access to a printer.

**Comment by suzanneccnc** [comment]
Hey Carsi! Thanks so much. Yes I have access to a printer. I just uploaded
a quick swag to the Marketing/Com drive folder ("CityCampNC
RecyclingComposting Statement"). Edit at will!!!

**Comment by carsi** [comment]
Hey @suzanneccnc is this what you were thinking? https://drive.google.com/drive/u/0/folders/0BwjOr-60lG0lRHpZWjRsZTMzenc

**Comment by suzanneccnc** [comment]
Yes! Fantastic!! Sorry for missing this in the flurry of the afternoon.
Best regards,
Suzanne

**Comment by suzanneccnc** [comment]
signage printed; will bring along with bins on Friday
