### ISSUE TITLE
Laptop to run the presentations

### ISSUE THREAD

**Issue by dtraleigh** [ncopenpass/NCOpenPass#710]
and what cables/connectors are needed, general AV logistics.

I can volunteer a Windows laptop with powerpoint.

**Comment by jhibbets** [comment]
Most slides should be PDF or Google Slides

**Comment by dtraleigh** [comment]
Nash Hall has an HDMI cable that we need to connect to. They have an HDMI to Lightning dongle also.

**Comment by jhibbets** [comment]
FYI - I'm getting the slides together. 

Do we have a clicker?
We will also need a volunteer to 
a) run the slides for lightning talks
b) be a time keeper

**Comment by dtraleigh** [comment]
We purchased a clicker a few years ago so it should be in the "bins of
stuff."

**Comment by ChrisTheDBA** [comment]
Couldn't locate. new purchased
