### ISSUE TITLE
Add Raleigh Main Events to the CityCampNC Partners page

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#737]
Add Raleigh Main Events to the CityCampNC Partners page as a Community Partner.

**Comment by suzanneccnc** [comment]
twitter handle @raleighMAIN

**Comment by jhibbets** [comment]
Good call

**Comment by ChrisTheDBA** [comment]
I don't have a logo and I need a website not a twitter handle

**Comment by snewt-n** [comment]
http://www.raleighmainevents.com/

http://raleighmainevent.com/wp-content/uploads/2016/07/MAIN_logo.png

?

**Comment by jhibbets** [comment]
http://www.raleighmainevents.com/
