### ISSUE TITLE
Build slide deck for Friday

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#757]

**Comment by suzanneccnc** [comment]
Include slide for "going-green". @carsi this needs to be done as well. Can
you handle along with recycling/composting signage?

**Comment by carsi** [comment]
@suzanneccnc Yes, I can also do this. Can you give me copy and size
specifications/location of the slide deck in Drive?

**Comment by carsi** [comment]
Are we good on the "going green" slide then? @jhibbets @suzanneccnc
