### ISSUE TITLE
Cross post NC Re-entry post

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#771]
We probably don't need all the pictures, but Jason Marshall said we could use this if we needed it:

http://blog.codeforgreensboro.org/progress-learning-at-the-nc-reentry-resources-hub-hack-day/

Author should be Jason if we have him on Wordpress, otherwise, set it to admin and add a line with a guest post byline - "Guest post by Jason Marshall, Code for Greensboro"

Also, please add attributions" "The post was originally published on blog.codeforgreensboro.org and re-published with permission" (Add a link to the post too)

**Comment by marshallj** [comment]
Eric Jackson and I collaborated on this blog post. Attribution needs to be "Guest post by Eric Jackson, Code for Asheville & Jason Marshall, Code for Greensboro"
