### ISSUE TITLE
water barrels for CoM

### ISSUE THREAD

**Issue by suzanneccnc** [ncopenpass/NCOpenPass#774]
I can bring filled water barrels with spigots to Church on Morgan. @taxladytracy Would that be a good thing?

**Comment by ChrisTheDBA** [comment]
We've already bought the water and we have igloo water coolers

Chris Mathews

**Comment by suzanneccnc** [comment]
OK. If the purchased water is in bottles, then water from barrels with spigots would cut down on recycling need. Purchased water can be returned. To clarify offer: 2 water barrels with spigots plus 2 refill jerry cans.

**Comment by ChrisTheDBA** [comment]
Can't be returned already submitted and reimbursed (water was purchased
weeks ago)

Chris Mathews

**Comment by suzanneccnc** [comment]
Got it.
