### ISSUE TITLE
Master slide deck is available for review / feedback

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#780]
I wasn't able to convert to Google Slides (time crunch) 

The intent is to mimic the schedule and have some visuals for speakers; I may add Twitter handles if I have time, but we have that available on the schedule page in a social media cheat sheet box

https://drive.google.com/open?id=0BwjOr-60lG0lb2gtbXM1RDhtTHc

**Comment by jhibbets** [comment]
Update Ben's headshot and adding social media, then handing off to @snewt-n for Thursday master deck creation/merge

**Comment by jhibbets** [comment]
updated slides are now on dropbox and drive:
- https://drive.google.com/drive/u/0/folders/0BwjOr-60lG0lV3Jaay1Ja2llM0k
- https://www.dropbox.com/home/Events/NC%20Open%20Pass/CityCamp%20NC%202017/Final_presentations

Working on mapping next, should only be a few minutes

**Comment by jhibbets** [comment]
@snewt-n here you go, let me know if you have any questions
Slide mapping:
- CCNC_2017.pdf - slides 3-11
- LT0-The_State_of_Open_Data-Mega_lightning_talk
- CCNC_2017.pdf - slide 12, 13
- LT1-Jason _Marshall-NC_Reentry_Resources_Hub_and_Brigade_Collaboration .pdf
- CCNC_2017.pdf - slide 14
- LT2-Jonathan_Opp-Creative_communities_and_the_power_of_storytelling.pdf
- CCNC_2017.pdf - slide 15
- LT3-Dr_Sarah _Windsor-STEM _Engagement_Hey _you.pdf
- CCNC_2017.pdf - slide 16
- LT4-Peter_Elbaum-Theres_a_Fee_For_That_A_Case_Study_in_Building_a_Public_Facing_Application.pdf
- CCNC_2017.pdf - slide 17
- LT5-Andre_Pierce-Bill_Scanlon-Environmental_Health_and_Safety_Director_Innovation_Partner.pdf
- CCNC_2017.pdf - slide 18
- LT6-Linda_Jones-Improving_Digital_Inclusion_Through_Design_Thinking.pdf
- CCNC_2017.pdf - slide 19
- LT7-Ben_Kittelson-Innovate_Durham_A_Public_Private_Innovation_Partnership.pdf
- CCNC_2017.pdf - slide 20
- LT8-Ryan _Thornburg-Using_Open_Data_to_Build_News_Tools_Products.pdf
- CCNC_2017.pdf - slide 21
- LT9-Melissa_Kennedy-Hacking_Government_Innovation.pdf
- CCNC_2017.pdf - slide 22

**Comment by jhibbets** [comment]
When you are done, please create a new file, CCNC_2017_master.pdf and add to either Drive or Dropbox, I can duplicate the file after its complete. Thanks!

**Comment by jhibbets** [comment]
@snewt-n slides 40 and 41 need to be switched. NC Rentry slides goes after @marshallj then Jonathon Opp, Then creative morning.

**Comment by snewt-n** [comment]
@jhibbets Yeah, I ended up putting in Jonathon Opp twice, and then promptly broke our document splitter. If someone has access to adobe full version, they can split that way, I put together what I could. I'm happy to share what I was successfully able to split/reassemble before I broke the splitter!

**Comment by jhibbets** [comment]
@carsi @natalienoel1 do either of you have full adobe suite to help here?

**Comment by carsi** [comment]
@snewt-n @jhibbets I can delete the duplicate Jon Opp slide and have the NC
Reentry slide before J. Opp

**Comment by snewt-n** [comment]
Got it worked out and updated the file

**Comment by jhibbets** [comment]
Slides look Fantastic. Go team.
