### ISSUE TITLE
Update team submission post with short summary of winning team(s)

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#799]
Update the team submission post with a brief summary of the winning team and any honorable mentions from the judged.

Update post at after the 3pm judging.

**Comment by jhibbets** [comment]
Add tags: hachathon, NC DataPalooza, CityCamp NC, NC Open Pass

**Comment by jhibbets** [comment]
Update. You don't need to add the category latest news 2016 @ChrisTheDBA just merged them together ;)

**Comment by suzanneccnc** [comment]
http://citycampnc.org/2017/09/30/nc-datapalooza-2017-open-data-competition-kickoff/

**Comment by dtraleigh** [comment]
Could we please use the photo with the sponsor board?

**Comment by ChrisTheDBA** [comment]
Yes. updating now

Chris Mathews
