### ISSUE TITLE
Prize money to Code for Durham

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#809]
The Are we represented team won the $1000 prize for CCNC. They decided collectively that the prize money will go to CfD for distribution.

**Comment by ChrisTheDBA** [comment]
Make sure we Xfer this money correct via Christopher Whitaker

**Comment by zachambrose** [comment]
Very cool!

**Comment by suzanneccnc** [comment]
Super comment on collaboration. We'll done!

**Comment by aikimark** [comment]
That's a nice gesture.  I look forward to watching the video of the presentations.

**Comment by aikimark** [comment]
I sent a thank-you email to Eric.

**Comment by ChrisTheDBA** [comment]
Which Eric? For what?

Chris Mathews

**Comment by aikimark** [comment]
Eric from Asheville.  He clarified that CfD is just holding the money for use by this project, if necessary.

**Comment by ChrisTheDBA** [comment]
Note sent to CfA for clarification on process
