### ISSUE TITLE
Transfer money to Code for Durham

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#812]
For Civic Spark Day. Is it $500 or $550?

**Comment by ChrisTheDBA** [comment]
550

Chris Mathews

**Comment by aikimark** [comment]
I'm confused.  I thought it was $1000.

**Comment by jhibbets** [comment]
This is a different topic from Civic Spark day

**Comment by jhibbets** [comment]
@ChrisTheDBA So CfA refunded my $550 to my AMEX. Do we need to initiate a transfer on our side? I had submitted an invoice / expense before. not sure if it was rejected or not.

**Comment by ChrisTheDBA** [comment]
Laura said they were reimbursed
