### ISSUE TITLE
Update Pendo logo on websites and sponsor slide

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#814]

**Comment by zachambrose** [comment]
The hot pink logo is in the logo folder in sponsorship.  Who is handling the sponsorship slide?

**Comment by ChrisTheDBA** [comment]
CCNC site is OK. Don't believe we have tasks for NCDP finale yet.

**Comment by wildca01t** [comment]
Completed. NCDP website Sponsor Pendo Logo added at Silver.
