### ISSUE TITLE
Create & Print flier for Centennial Rocks

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#820]

**Comment by ChrisTheDBA** [comment]
@carsi can you or @snewt-n do a similar handout to the one for CityCamp. Kind of a rush, Jason and Zach would like to have it by next Tuesday for an event at NCSU

**Comment by carsi** [comment]
I'm in Hong Kong and won't be available to help until the 18th of October.
The CityCampNC flyer is available in pdf form and if you have access to
Adobe Illustrator or some other softwares, you may be able to open and
modify it for your purposes. @snewt-n Do you happen to have availability to
help with this?

**Comment by zachambrose** [comment]
@snewt-n Here is the card.

**Comment by jhibbets** [comment]
I did this. https://drive.google.com/open?id=0BwjOr-60lG0lcGhUWGhvVk90MVE

**Comment by zachambrose** [comment]
I did this one for ATO. https://drive.google.com/open?id=0BxSvt4naKiIlYmpKTmh6aEVxR2M
