### ISSUE TITLE
Stand up banner for 10/10-10/11

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#825]
Get the banner to @jhibbets and @zachambrose

**Comment by zachambrose** [comment]
@jhibbets you're going to bring this to Innovators Program Demo Day, right?

**Comment by jhibbets** [comment]
yes

**Comment by ChrisTheDBA** [comment]
Easiest to bring to 10/9 meetup and hand off there. Leaving open to remind myself to put it in the car.

**Comment by jhibbets** [comment]
+1

**Comment by TaxLadyTracy** [comment]
I will send your easels then also.

**Comment by jhibbets** [comment]
Don't forget the orange lulu bag ;)

**Comment by ChrisTheDBA** [comment]
+1

Chris Mathews

**Comment by TaxLadyTracy** [comment]
Nah, I thought I'd keep the bag lol
