### ISSUE TITLE
Code for Raleigh meet-up on 10/9

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#826]

**Comment by ChrisTheDBA** [comment]
Can you get the room at red hat? I will bring the Birthday cake!

**Comment by jhibbets** [comment]
I just checked and we can have a room in the Annex. I will set-up the
Meet-up page for Monday night.

What time do we want to do it since we have our planning call. 7pm?

**Comment by ChrisTheDBA** [comment]
Can we do both at 6 PM. You can be on the call and I will start whoever comes with project support and then join as available.

I assume we are doing this to build support for NCDP projects and get last minute entries.

**Comment by jhibbets** [comment]
We can do 6pm. And yes, the whole point it to support the DataPalooza teams

**Comment by jhibbets** [comment]
Room is booked. Meet-up is scheduled and announced: https://www.meetup.com/Triangle-Code-for-America/events/243885673/

Let me know if you want anything added to it or just update the meet-up invite @zachambrose @ChrisTheDBA
