### ISSUE TITLE
order food for 10/9 meetup

### ISSUE THREAD

**Issue by ChrisTheDBA** [ncopenpass/NCOpenPass#841]

**Comment by aikimark** [comment]
So, there's a meetup on both Oct 9 and Oct 10?

**Comment by jhibbets** [comment]
Oct 10 is a Customer value workshop

**Comment by jhibbets** [comment]
@christhedba do we want to see if we can combine the two things? is this
asking too much of the teams to go to a meet-up and a workshop?

**Comment by aikimark** [comment]
That's a capital idea, Jason

**Comment by ChrisTheDBA** [comment]
@jhibbets Sounds good to me. We will be busy that night!

Chris Mathews
