### ISSUE TITLE
Write blog post about teams pitching at ATO

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#885]

**Comment by zachambrose** [comment]
Here is the form. It closes out at 5 tonight, but you can already grad names and descriptions for the teams that have signed up. https://docs.google.com/forms/d/19_J6RadWoQ91ypazlOxX99UERAYQwHsTfZMLy3SXu8M/edit#responses

**Comment by wildca01t** [comment]
@wildca01t add the youtube videos in a blog post of all 8 teams tomorrow.
