### ISSUE TITLE
Send mail chimp email about finalist

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#893]

**Comment by zachambrose** [comment]
Let's also push the early bird sign up.

**Comment by zachambrose** [comment]
@bilscanlon will email you the finalists Monday afternoon. Don't post it until we've announced it at the closing ceremony at 5:20. Let us know who is posting and Bill or I will text you once it's announced.

**Comment by wildca01t** [comment]
Syncing up with @natalienoel1 today

**Comment by natalienoel1** [comment]
Scheduled for 6pm!

**Comment by zachambrose** [comment]
Looked great!
