### ISSUE TITLE
Make final decision on event date

### ISSUE THREAD

**Issue by jhibbets** [ncopenpass/NCOpenPass#9]

**Comment by dtraleigh** [comment]
Working on something that might help us. Will need WPU's feedback also.
(Week of 3/14)

**Comment by dtraleigh** [comment]
Check this out:

https://docs.google.com/spreadsheets/d/1apKYfItQ49Nh0yZ733ZmxQXroU87F2hHYxUpm2D1I-g/edit?usp=sharing

**Comment by ChrisTheDBA** [comment]
Updated the spreadsheet the NC State Fair starts on Oct 13th. There is literally no weekend without something.

**Comment by ChrisTheDBA** [comment]
I will also be out of town Sept 5-11.

**Comment by ChrisTheDBA** [comment]
based on Leo's info/feedback I vote for Sept 22-24 per email.

**Comment by jhibbets** [comment]
So far, spetember 23/24 is looking good for me too. Just need to check my
work calendar.
