### ISSUE TITLE
Update judging criteria on NC DataPalooza website

### ISSUE THREAD

**Issue by bilscanlon** [ncopenpass/NCOpenPass#906]
I noticed that the Judging criteria on our website is out of date.  

can this page: http://www.ncdatapalooza.com/judging-criteria/

be updated with the information from this page: https://docs.google.com/a/ambrosestrategy.com/document/d/1M-NxgAmVJSAc5-sz5yvFhoE_zP4-qnqiOgVdwoDMk3E/edit?usp=sharing

**Comment by natalienoel1** [comment]
Done!
