### ISSUE TITLE
Write and placea TechWire piece

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#913]

**Comment by zachambrose** [comment]
I just talked with @jhibbets about this and he thinks it's definitely worth a run. Would be good to focus on three finalists and blockchain keynote.

**Comment by jhibbets** [comment]
Done:  https://docs.google.com/document/d/124Wl7czEhGDF55EpdM5z1U_UFODGj-3tvZ6my4kXj5A/edit#
