### ISSUE TITLE
Set up for Empire Eats

### ISSUE THREAD

**Issue by TaxLadyTracy** [ncopenpass/NCOpenPass#943]
per Kimberly need 8ft table area

**Comment by dtraleigh** [comment]
Let's use the HQ bar area for this.

**Comment by TaxLadyTracy** [comment]
Need that for beer and wine.

**Comment by dtraleigh** [comment]
Then we'll roll back some of the HQ tables for this then.

**Comment by TaxLadyTracy** [comment]
That was my thought just need someone other than me to know how much room
was needed.
