### ISSUE TITLE
Invite Cary and Raleigh elected officials

### ISSUE THREAD

**Issue by zachambrose** [ncopenpass/NCOpenPass#947]

**Comment by zachambrose** [comment]
@jhibbets can you send @ChrisTheDBA a copy of your email?

**Comment by jhibbets** [comment]
Subject: NC DataPalooza finale is on Monday 

I'm really excited to be involved with the 5th Annual NC DataPalooza on November 13th! What is NC Datapalooza? The event brings together coders, designers, entrepreneurs, the public and government to create positive change in the community through the use of open data.

After ideation and 7 weeks of work, three teams will compete at the DataPalooza finale on November 13th. The event is an initiative of HQ Raleigh and will be hosted at the HQ Capital Club Cannon Room on 16 West Martin Street in Downtown Raleigh from 5pm-8pm.

I know you're busy, so if your schedule permits, I hope you can join me in attending this year’s NC Datapalooza. 

Please register for free with the elected official ticket:

https://www.eventbrite.com/e/nc-datapalooza-2017-tickets-38259132094?aff=eac2

Regards,
Jason Hibbets
